<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Imlight.Common\Imlight.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SharpDX.Mathematics" Version="4.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Types\Generated\" />
  </ItemGroup>

</Project>
