<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Akka" Version="1.5.0" />
        <PackageReference Include="Akka.Remote" Version="1.5.0" />
        <PackageReference Include="LiteDB" Version="5.0.16" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Common\Imlight.Common.csproj" />
        <ProjectReference Include="E:\W101r\WizUnraveler\src\WizUnraveler\WizUnraveler.csproj" />
    </ItemGroup>

</Project>
