[Global Settings]
GameRevision = r766693.WizardDev

[Logging]
LogPath = ./logs/log.txt
; The minimum log level to be written to the log file. Valid values are: TRACE, DEBUG, INFO, WARN, ERROR, FATAL
LogLevel = DEBUG
LogFormat = {Level:u3} {CallingSpace} : {Message:lj} {NewLine}{Exception}
SeqSinkUrl = http://localhost:5341

[Login Server]
; The internal name for the login server. This is not a realm name.
LoginServerName = Imlight.Login
LoginServerPort = 12000
LoginPlayerLimit = 1000
MaxAllowedCharactersPerAccount = 6
; The time in seconds that a user can be AFK before being disconnected.
LoginAfkTimeout = 360
; The time in seconds between AFK checks.
LoginAfkCheckInterval = 60

[Game Server]
; The internal name for the game server. This is not a realm name.
GameServerName = Imlight.Game
GameServerPort = 12333
GameServerPlayerLimit = 1000
; The number of game servers that can be created.
MaxGameServersAllowed = 3
; The time in seconds that a session key is valid.
SessionKeyValidityTime = 28800

[Character]
StartingLevel = 1
StartingZone = WizardCity/WC_Streets/WC_Unicorn
StartingWorld = 1
BaseGoldPouch = 1000000
MaxLevel = 200
MaxInventoryItems = 75
MaxJewelsAllowed = 100
MaxFriends = 100
PetEnergyTickInSeconds = 10

[Patch Server]
; The internal name for the patch server. This is not a realm name.
PatchServerName = Imlight.Patch
; The port used by the patch server.
PatchServerPort = 12500
; The URL to the patch server.
PatchServerInternalUrl = http://patcher.phill030.de
; The time in seconds that the patch server will wait to reach the endpoint before timing out.
PatchServerInternalTimeout = 10
; The time in seconds that any given download will wait before timing out.
PatchServerDownloadTimeout = 360
LocalWadCachePath = ./cache

[Database]
PlayerDatabaseUrl =
PlayerDatabaseName = Playerdata
PlayerDatabaseCertificatePath = ../Certificates/playerdata.client.certificate.pfx
WorldDatabaseUrl = https://a.worlddata.ravendb.community
WorldDatabaseName = WorldData
WorldDatabaseCertificatePath = ../Certificates/worlddata.dev.certificate.pfx
AdminAccountUsername = admin
AdminAccountPassword = compsci
DatabaseMaxNumberOfRequestsPerSession = 16
DatabaseRequestTimeoutInSeconds = 90
DatabaseWaitForNonStaleResultsTimeout = 5
; The directory where the embedded database will be stored.
EmbeddedDatabaseDataDirectory = ../ImlightEmbeddedDatabase/
; The port used by the embedded database.
EmbeddedDatabasePort = 8080
; The time in seconds that the embedded database will wait to reach the endpoint before timing out.
EmbeddedDatabaseTimeoutTime = 90
; If true, a full RavenDb database will be used. The full database includes a dotnet runtime.
EmbeddedDatabaseUseFull = False
; The path to the full RavenDb. Only used if EmbeddedDatabaseUseFull is true.
EmbeddedDatabaseFullPath = ../RavenDB/Server/

[Advanced]
; Please only change these settings if you know what you are doing.
CharacterUploadIntervalInMinutes = 6
; The salt used to hash the session key.
SessionKeyHashInput = MAGIC_HATTER
PatchServerBufferSize = 4096
PatchServerUserAgent = KingsIsle Patcher
; The size of the buffer used by the session actor.
SessionActorBufferSize = 4096
; The thread pool size used by the session actor to send messages.
SessionActorSendPoolSize = 3
; The thread pool size used by the session actor to receive messages.
SessionActorReceivePoolSize = 3
; If true, the session actor will close on exception.
SessionActorCloseOnException = True
; The number of times the session actor will restart a service before crashing.
SessionActorServiceRetryCount = 3
; The time in seconds that the session actor will wait before restarting.
SessionActorServiceRangeRetry = 30
; The time in seconds that the server will send a heartbeat to the client.
KeepAliveInterval = 60
; The time in seconds the server will wait for a heartbeat response.
KeepAliveRspWaitTime = 4
; How many requests are allowed within the token bucket of the session actor.
SessionTokenBucketMax = 150
; How many new tokens are added to the token bucket per second.
SessionTokenBucketPerSecond = 50
; How many times the session actor will try to acquire a token before failing.
SessionTokenBucketFailedAcquisitionLimit = 5
; The time in seconds that the local wad cache will wait for the patch server to respond.
LocalWadCacheWaitForPatchServerTimeout = 10
