user.email=compundbread@gmail.com
user.name=Jay
filter.lfs.required=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
submodule.active=.
remote.origin.url=https://github.com/W101r/Imlight.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.main.remote=origin
branch.main.merge=refs/heads/main
lfs.repositoryformatversion=0
branch.WIP-8000-frontend.remote=origin
branch.WIP-8000-frontend.merge=refs/heads/WIP-8000-frontend
branch.WIP-0101-DynamicDeserializer.remote=origin
branch.WIP-0101-DynamicDeserializer.merge=refs/heads/WIP-0101-DynamicDeserializer
branch.WIP-1000-actor-model.remote=origin
branch.WIP-1000-actor-model.merge=refs/heads/WIP-1000-actor-model
branch.WIP-1001-login.remote=origin
branch.WIP-1001-login.merge=refs/heads/WIP-1001-login
branch.WIP-1002-login-rewrite.remote=origin
branch.WIP-1002-login-rewrite.merge=refs/heads/WIP-1002-login-rewrite
branch.WIP-8412-account-management.remote=origin
branch.WIP-8412-account-management.merge=refs/heads/WIP-8412-account-management
branch.WIP-1487-game-transition.remote=origin
branch.WIP-1487-game-transition.merge=refs/heads/WIP-1487-master-server
