//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Imlight.Internals.DML
{
    using System;
    public sealed class AISCLIENT_19_PROTOCOL : INetworkProtocol
    {
        public byte ServiceID { get; } = 19;
        public string ProtocolType { get; } = "AISCLIENT";
        public Int32 ProtocolVersion { get; } = 1;
        public string ProtocolDescription { get; } = "All Anti-Indulgence System Messages To/From the Client";
        // == RECORDS ==
        public INetworkMessage Dispatch(byte id)
        {
            switch (id)
            {
                case (1): return new MSG_AISMESSAGE();
                default: throw new InternalException($"No message was found at ID {id} for this protocol!");
            }
        }
        public sealed class MSG_AISMESSAGE : INetworkMessage
        {
            [DMLElement(DMLType.STR)] public String Message;
            [DMLElement(DMLType.UBYT)] public Byte Modal;
            public byte MessageOrder { get; } = 1;
            public byte ServiceID { get; } = 19;
        }
    }
}
