<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Akka" Version="1.5.0" />
    <PackageReference Include="Akka.Remote" Version="1.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\WizUnraveler\src\WizUnraveler\WizUnraveler.csproj" />
    <ProjectReference Include="..\Imlight.Common\Imlight.Common.csproj" />
    <ProjectReference Include="..\Imlight.Data\Imlight.Data.csproj" />
    <ProjectReference Include="..\Imlight.Net\Imlight.Net.csproj" />
  </ItemGroup>

</Project>
