<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Engine\Imlight.Engine.csproj" />
    <ProjectReference Include="..\Login\Imlight.Login.csproj" />
    <ProjectReference Include="..\Processor\Imlight.Processor.csproj" />
    <ProjectReference Include="..\Realm\Imlight.Realm.csproj" />
    <ProjectReference Include="..\StorageBackup\Imlight.Storage.Backup.csproj" />
    <ProjectReference Include="..\Storage\Imlight.Storage.csproj" />
  </ItemGroup>

</Project>
