akka {
  loglevel = "DEBUG"
  loggers = ["Akka.Logger.Serilog.SerilogLogger, Akka.Logger.Serilog"]

  actor {
      provider = remote

      mailbox {
        zone-priority {
          mailbox-type = "Imlight.CoreLib.Shared.Networking.ZonePriorityMailbox, Imlight.CoreLib"
        }
      }
  }

  remote {
    dot-netty.tcp {
      hostname = "127.0.0.1"
      port = 12999
    }
  }
}
