<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="WizUnraveler" Version="1.2.8.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Imlight.Common\Imlight.Common.csproj" />
    <ProjectReference Include="..\Imlight.Data\Imlight.Data.csproj" />
  </ItemGroup>

</Project>
