<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net10.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings></PropertyGroup><ItemGroup><ProjectReference Include="../../src/Imlight.CoreLib/Imlight.CoreLib.csproj" /><Compile Include="../../src/Imlight.Director/ResourceContainer.cs" Link="Production/ResourceContainer.cs" /></ItemGroup></Project>
