<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CodeDom" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Imlight.Common\Imlight.Common.csproj" />
    <ProjectReference Include="..\Imlight.Engine\Imlight.Engine.csproj" />
    <ProjectReference Include="..\Imlight.Generator\Imlight.Generator.csproj" />
    <ProjectReference Include="..\Imlight.Internals\Imlight.Internals.csproj" />
    <ProjectReference Include="..\Imlight.IO\Imlight.IO.csproj" />
    <ProjectReference Include="..\Imlight.Realm\Imlight.Realm.csproj" />
  </ItemGroup>

</Project>
