//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Imlight.Internals.DML
{
    using System;
    public sealed class LOGIN_7_PROTOCOL : INetworkProtocol
    {
        public byte ServiceID { get; } = 7;
        public string ProtocolType { get; } = "LOGIN";
        public Int32 ProtocolVersion { get; } = 1;
        public string ProtocolDescription { get; } = "Login Server Messages";
        // == RECORDS ==
        public INetworkMessage Dispatch(byte id)
        {
            switch (id)
            {
                case (1): return new MSG_CHARACTERINFO();
                case (2): return new MSG_CHARACTERLIST();
                case (3): return new MSG_CHARACTERSELECTED();
                case (4): return new MSG_CREATECHARACTER();
                case (5): return new MSG_CREATECHARACTERRESPONSE();
                case (6): return new MSG_DELETECHARACTER();
                case (7): return new MSG_DELETECHARACTERRESPONSE();
                case (8): return new MSG_REQUESTCHARACTERLIST();
                case (9): return new MSG_REQUESTSERVERLIST();
                case (10): return new MSG_SELECTCHARACTER();
                case (11): return new MSG_SERVERLIST();
                case (12): return new MSG_STARTCHARACTERLIST();
                case (13): return new MSG_USER_AUTHEN();
                case (14): return new MSG_USER_AUTHEN_RSP();
                case (15): return new MSG_USER_VALIDATE();
                case (16): return new MSG_USER_VALIDATE_RSP();
                case (17): return new MSG_DISCONNECT_LOGIN_AFK();
                case (18): return new MSG_LOGIN_NOT_AFK();
                case (19): return new MSG_LOGINSERVERSHUTDOWN();
                case (20): return new MSG_USER_ADMIT_IND();
                case (21): return new MSG_WEBCHARACTERINFO();
                case (22): return new MSG_USER_AUTHEN_V2();
                case (23): return new MSG_SAVECHARACTER();
                case (24): return new MSG_WEB_AUTHEN();
                case (25): return new MSG_WEB_VALIDATE();
                case (26): return new MSG_CHANGECHARACTERNAME();
                case (27): return new MSG_USER_AUTHEN_V3();
                case (28): return new MSG_LOGINLOGCHARACTERCREATION();
                default: throw new InternalException($"No message was found at ID {id} for this protocol!");
            }
        }
        public sealed class MSG_CHARACTERINFO : INetworkMessage
        {
            public byte MessageOrder { get; } = 1;
            [DMLElement("STR")] public String CharacterInfo;
        }
        public sealed class MSG_CHARACTERLIST : INetworkMessage
        {
            public byte MessageOrder { get; } = 2;
            [DMLElement("UINT")] public UInt32 Error;
        }
        public sealed class MSG_CHARACTERSELECTED : INetworkMessage
        {
            public byte MessageOrder { get; } = 3;
            [DMLElement("STR")] public String IP;
            [DMLElement("INT")] public Int32 TCPPort;
            [DMLElement("INT")] public Int32 UDPPort;
            [DMLElement("STR")] public String Key;
            [DMLElement("GID")] public UInt64 UserID;
            [DMLElement("GID")] public UInt64 CharID;
            [DMLElement("GID")] public UInt64 ZoneID;
            [DMLElement("STR")] public String ZoneName;
            [DMLElement("STR")] public String Location;
            [DMLElement("INT")] public Int32 Slot;
            [DMLElement("INT")] public Int32 PrepPhase;
            [DMLElement("INT")] public Int32 Error;
            [DMLElement("STR")] public String LoginServer;
        }
        public sealed class MSG_CREATECHARACTER : INetworkMessage
        {
            public byte MessageOrder { get; } = 4;
            [DMLElement("STR")] public String CreationInfo;
        }
        public sealed class MSG_CREATECHARACTERRESPONSE : INetworkMessage
        {
            public byte MessageOrder { get; } = 5;
            [DMLElement("INT")] public Int32 ErrorCode;
        }
        public sealed class MSG_DELETECHARACTER : INetworkMessage
        {
            public byte MessageOrder { get; } = 6;
            [DMLElement("GID")] public UInt64 CharID;
        }
        public sealed class MSG_DELETECHARACTERRESPONSE : INetworkMessage
        {
            public byte MessageOrder { get; } = 7;
            [DMLElement("INT")] public Int32 ErrorCode;
        }
        public sealed class MSG_REQUESTCHARACTERLIST : INetworkMessage
        {
            public byte MessageOrder { get; } = 8;
        }
        public sealed class MSG_REQUESTSERVERLIST : INetworkMessage
        {
            public byte MessageOrder { get; } = 9;
        }
        public sealed class MSG_SELECTCHARACTER : INetworkMessage
        {
            public byte MessageOrder { get; } = 10;
            [DMLElement("GID")] public UInt64 CharID;
            [DMLElement("STR")] public String ServerName;
        }
        public sealed class MSG_SERVERLIST : INetworkMessage
        {
            public byte MessageOrder { get; } = 11;
        }
        public sealed class MSG_STARTCHARACTERLIST : INetworkMessage
        {
            public byte MessageOrder { get; } = 12;
            [DMLElement("STR")] public String LoginServer;
            [DMLElement("INT")] public Int32 PurchasedCharacterSlots;
        }
        public sealed class MSG_USER_AUTHEN : INetworkMessage
        {
            public byte MessageOrder { get; } = 13;
            [DMLElement("STR")] public String Rec1;
            [DMLElement("STR")] public String Version;
            [DMLElement("STR")] public String Revision;
            [DMLElement("STR")] public String DataRevision;
            [DMLElement("STR")] public String CRC;
            [DMLElement("GID")] public UInt64 MachineID;
            [DMLElement("STR")] public String PatchClientID;
        }
        public sealed class MSG_USER_AUTHEN_RSP : INetworkMessage
        {
            public byte MessageOrder { get; } = 14;
            [DMLElement("INT")] public Int32 Error;
            [DMLElement("GID")] public UInt64 UserID;
            [DMLElement("STR")] public String Rec1;
            [DMLElement("STR")] public String Reason;
            [DMLElement("STR")] public String TimeStamp;
            [DMLElement("INT")] public Int32 PayingUser;
            [DMLElement("INT")] public Int32 Flags;
        }
        public sealed class MSG_USER_VALIDATE : INetworkMessage
        {
            public byte MessageOrder { get; } = 15;
            [DMLElement("GID")] public UInt64 UserID;
            [DMLElement("STR")] public String PassKey3;
            [DMLElement("GID")] public UInt64 MachineID;
            [DMLElement("STR")] public String Locale;
            [DMLElement("STR")] public String PatchClientID;
        }
        public sealed class MSG_USER_VALIDATE_RSP : INetworkMessage
        {
            public byte MessageOrder { get; } = 16;
            [DMLElement("INT")] public Int32 Error;
            [DMLElement("STR")] public String Reason;
            [DMLElement("GID")] public UInt64 UserID;
            [DMLElement("STR")] public String TimeStamp;
            [DMLElement("INT")] public Int32 PayingUser;
            [DMLElement("INT")] public Int32 Flags;
        }
        public sealed class MSG_DISCONNECT_LOGIN_AFK : INetworkMessage
        {
            public byte MessageOrder { get; } = 17;
            [DMLElement("BYT")] public SByte Warning;
        }
        public sealed class MSG_LOGIN_NOT_AFK : INetworkMessage
        {
            public byte MessageOrder { get; } = 18;
            [DMLElement("UINT")] public UInt32 BadgeNameID;
        }
        public sealed class MSG_LOGINSERVERSHUTDOWN : INetworkMessage
        {
            public byte MessageOrder { get; } = 19;
            [DMLElement("UINT")] public UInt32 Message;
        }
        public sealed class MSG_USER_ADMIT_IND : INetworkMessage
        {
            public byte MessageOrder { get; } = 20;
            [DMLElement("INT")] public Int32 Status;
            [DMLElement("UINT")] public UInt32 PositionInQueue;
        }
        public sealed class MSG_WEBCHARACTERINFO : INetworkMessage
        {
            public byte MessageOrder { get; } = 21;
            [DMLElement("INT")] public Int32 Name;
            [DMLElement("INT")] public Int32 Gender;
            [DMLElement("INT")] public Int32 School;
        }
        public sealed class MSG_USER_AUTHEN_V2 : INetworkMessage
        {
            public byte MessageOrder { get; } = 22;
            [DMLElement("STR")] public String Rec1;
            [DMLElement("STR")] public String Version;
            [DMLElement("STR")] public String Revision;
            [DMLElement("STR")] public String DataRevision;
            [DMLElement("STR")] public String CRC;
            [DMLElement("GID")] public UInt64 MachineID;
            [DMLElement("STR")] public String Locale;
            [DMLElement("STR")] public String PatchClientID;
        }
        public sealed class MSG_SAVECHARACTER : INetworkMessage
        {
            public byte MessageOrder { get; } = 23;
            [DMLElement("GID")] public UInt64 CharID;
            [DMLElement("UBYT")] public Byte Success;
        }
        public sealed class MSG_WEB_AUTHEN : INetworkMessage
        {
            public byte MessageOrder { get; } = 24;
            [DMLElement("STR")] public String Rec1;
            [DMLElement("STR")] public String Version;
            [DMLElement("STR")] public String Revision;
            [DMLElement("STR")] public String DataRevision;
            [DMLElement("STR")] public String CRC;
            [DMLElement("GID")] public UInt64 MachineID;
        }
        public sealed class MSG_WEB_VALIDATE : INetworkMessage
        {
            public byte MessageOrder { get; } = 25;
            [DMLElement("GID")] public UInt64 UserID;
            [DMLElement("STR")] public String PassKey3;
            [DMLElement("GID")] public UInt64 MachineID;
            [DMLElement("STR")] public String Locale;
        }
        public sealed class MSG_CHANGECHARACTERNAME : INetworkMessage
        {
            public byte MessageOrder { get; } = 26;
            [DMLElement("GID")] public UInt64 CharID;
            [DMLElement("WSTR")] public String NewName;
            [DMLElement("STR")] public String ServerName;
        }
        public sealed class MSG_USER_AUTHEN_V3 : INetworkMessage
        {
            public byte MessageOrder { get; } = 27;
            [DMLElement("STR")] public String Rec1;
            [DMLElement("STR")] public String Version;
            [DMLElement("STR")] public String Revision;
            [DMLElement("STR")] public String DataRevision;
            [DMLElement("STR")] public String CRC;
            [DMLElement("GID")] public UInt64 MachineID;
            [DMLElement("STR")] public String Locale;
            [DMLElement("STR")] public String PatchClientID;
            [DMLElement("UINT")] public UInt32 IsSteamPatcher;
        }
        public sealed class MSG_LOGINLOGCHARACTERCREATION : INetworkMessage
        {
            public byte MessageOrder { get; } = 28;
            [DMLElement("UINT")] public UInt32 Stage;
            [DMLElement("UINT")] public UInt32 Parameter;
        }
    }
}
