//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Imlight.Internals.DML
{
    using System;
    public sealed class MG3_MESSAGES_44_PROTOCOL : INetworkProtocol
    {
        public byte ServiceID { get; } = 44;
        public string ProtocolType { get; } = "MG3_MESSAGES";
        public Int32 ProtocolVersion { get; } = 1;
        public string ProtocolDescription { get; } = "Messages for MG3 MinigameWindow Mini-Game";
        // == RECORDS ==
        public INetworkMessage Dispatch(byte id)
        {
            switch (id)
            {
                case (1): return new MSG_MG3_CONNECT();
                case (2): return new MSG_MG3_MOVED();
                case (3): return new MSG_MG3_REWARDS();
                default: throw new InternalException($"No message was found at ID {id} for this protocol!");
            }
        }
        public sealed class MSG_MG3_CONNECT : INetworkMessage
        {
            public byte MessageOrder { get; } = 1;
        }
        public sealed class MSG_MG3_MOVED : INetworkMessage
        {
            public byte MessageOrder { get; } = 2;
        }
        public sealed class MSG_MG3_REWARDS : INetworkMessage
        {
            [DMLElement(DMLType.INT)] public Int32 score;
            [DMLElement(DMLType.STR)] public String gameName;
            public byte MessageOrder { get; } = 3;
        }
    }
}
