//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Imlight.Internals.DML
{
    using System;
    public sealed class QUEST_MESSAGES_52_PROTOCOL : INetworkProtocol
    {
        public byte ServiceID { get; } = 52;
        public string ProtocolType { get; } = "QUEST_MESSAGES";
        public Int32 ProtocolVersion { get; } = 1;
        public string ProtocolDescription { get; } = "Messages related to questing";
        // == RECORDS ==
        public INetworkMessage Dispatch(byte id)
        {
            switch (id)
            {
                case (1): return new MSG_ACCEPTQUEST();
                case (2): return new MSG_COMPLETEGOAL();
                case (3): return new MSG_COMPLETEPERSONA();
                case (4): return new MSG_COMPLETEQUEST();
                case (5): return new MSG_DECLINEQUEST();
                case (6): return new MSG_INTERACTNPC();
                case (7): return new MSG_NPCINFO();
                case (8): return new MSG_PERSONAINFO();
                case (9): return new MSG_QUESTOFFER();
                case (10): return new MSG_REMOVEGOAL();
                case (11): return new MSG_REMOVEQUEST();
                case (12): return new MSG_SENDGOAL();
                case (13): return new MSG_SENDNPCOPTIONS();
                case (14): return new MSG_SENDQUEST();
                default: throw new InternalException($"No message was found at ID {id} for this protocol!");
            }
        }
        public sealed class MSG_ACCEPTQUEST : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 MobileID;
            [DMLElement("STR")] public String QuestName;
            public byte MessageOrder { get; } = 1;
        }
        public sealed class MSG_COMPLETEGOAL : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 QuestID;
            [DMLElement("GID")] public UInt64 GoalID;
            [DMLElement("STR")] public String CompleteText;
            public byte MessageOrder { get; } = 2;
        }
        public sealed class MSG_COMPLETEPERSONA : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 MobileID;
            [DMLElement("GID")] public UInt64 QuestID;
            [DMLElement("GID")] public UInt64 GoalID;
            public byte MessageOrder { get; } = 3;
        }
        public sealed class MSG_COMPLETEQUEST : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 QuestID;
            [DMLElement("STR")] public String CompleteText;
            public byte MessageOrder { get; } = 4;
        }
        public sealed class MSG_DECLINEQUEST : INetworkMessage
        {
            [DMLElement("STR")] public String QuestName;
            public byte MessageOrder { get; } = 5;
        }
        public sealed class MSG_INTERACTNPC : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("STR")] public String ServiceName;
            [DMLElement("INT")] public Int32 Reinteract;
            [DMLElement("UINT")] public UInt32 ServiceIndex;
            public byte MessageOrder { get; } = 6;
        }
        public sealed class MSG_NPCINFO : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 MobileID;
            [DMLElement("STR")] public String Name;
            [DMLElement("STR")] public String Greeting;
            [DMLElement("STR")] public String PersonaMadlibs;
            public byte MessageOrder { get; } = 7;
        }
        public sealed class MSG_PERSONAINFO : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 MobileID;
            [DMLElement("GID")] public UInt64 QuestID;
            [DMLElement("GID")] public UInt64 GoalID;
            [DMLElement("STR")] public String GoalHyperlink;
            public byte MessageOrder { get; } = 8;
        }
        public sealed class MSG_QUESTOFFER : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 MobileID;
            [DMLElement("STR")] public String QuestName;
            [DMLElement("STR")] public String QuestTitle;
            [DMLElement("STR")] public String QuestInfo;
            [DMLElement("INT")] public Int32 Level;
            [DMLElement("STR")] public String Rewards;
            [DMLElement("STR")] public String GoalData;
            [DMLElement("UBYT")] public Byte Mainline;
            public byte MessageOrder { get; } = 9;
        }
        public sealed class MSG_REMOVEGOAL : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 QuestID;
            [DMLElement("GID")] public UInt64 GoalID;
            public byte MessageOrder { get; } = 10;
        }
        public sealed class MSG_REMOVEQUEST : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 QuestID;
            [DMLElement("GID")] public UInt64 NpcID;
            public byte MessageOrder { get; } = 11;
        }
        public sealed class MSG_SENDGOAL : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 QuestID;
            [DMLElement("GID")] public UInt64 GoalID;
            [DMLElement("UINT")] public UInt32 GoalNameID;
            [DMLElement("STR")] public String GoalTitle;
            [DMLElement("STR")] public String GoalLocation;
            [DMLElement("STR")] public String GoalImage1;
            [DMLElement("STR")] public String GoalImage2;
            [DMLElement("STR")] public String PersonaName;
            [DMLElement("UBYT")] public Byte GoalType;
            [DMLElement("UBYT")] public Byte GoalStatus;
            [DMLElement("INT")] public Int32 GoalCount;
            [DMLElement("INT")] public Int32 GoalTotal;
            [DMLElement("INT")] public Int32 SubscriberGoalTotal;
            [DMLElement("UBYT")] public Byte UseTally;
            [DMLElement("STR")] public String TallyText;
            [DMLElement("INT")] public Int32 SendType;
            [DMLElement("STR")] public String GoalMadlibs;
            [DMLElement("STR")] public String ClientTags;
            [DMLElement("STR")] public String PatronIcon;
            [DMLElement("UBYT")] public Byte NoQuestHelper;
            [DMLElement("UBYT")] public Byte PetOnlyQuest;
            public byte MessageOrder { get; } = 12;
        }
        public sealed class MSG_SENDNPCOPTIONS : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 MobileID;
            [DMLElement("STR")] public String Options;
            [DMLElement("INT")] public Int32 Reinteract;
            public byte MessageOrder { get; } = 13;
        }
        public sealed class MSG_SENDQUEST : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 QuestID;
            [DMLElement("UINT")] public UInt32 QuestNameID;
            [DMLElement("UINT")] public UInt32 QuestType;
            [DMLElement("STR")] public String QuestTitle;
            [DMLElement("STR")] public String QuestInfo;
            [DMLElement("UBYT")] public Byte New;
            [DMLElement("STR")] public String QuestMadlibs;
            [DMLElement("STR")] public String GoalData;
            [DMLElement("STR")] public String Rewards;
            [DMLElement("STR")] public String ClientTags;
            [DMLElement("UBYT")] public Byte NoQuestHelper;
            [DMLElement("UBYT")] public Byte Mainline;
            [DMLElement("UBYT")] public Byte SkipQHAutoSelect;
            [DMLElement("UBYT")] public Byte PetOnlyQuest;
            public byte MessageOrder { get; } = 14;
        }
    }
}
