//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Imlight.Internals.DML
{
    using System;
    public sealed class SOBLOCKS_MESSAGES_25_PROTOCOL : INetworkProtocol
    {
        public byte ServiceID { get; } = 25;
        public string ProtocolType { get; } = "SOBLOCKS_MESSAGES";
        public Int32 ProtocolVersion { get; } = 1;
        public string ProtocolDescription { get; } = "Messages for all Soblocks minigames";
        // == RECORDS ==
        public INetworkMessage Dispatch(byte id)
        {
            switch (id)
            {
                case (1): return new MSG_SOBLOCKS_ADVANCEOFF();
                case (2): return new MSG_SOBLOCKS_ADVANCEON();
                case (3): return new MSG_SOBLOCKS_ATTACK();
                case (4): return new MSG_SOBLOCKS_COUNTDOWN();
                case (5): return new MSG_SOBLOCKS_ENDGAME();
                case (6): return new MSG_SOBLOCKS_FREEZEBLOCKS();
                case (7): return new MSG_SOBLOCKS_INFO();
                case (8): return new MSG_SOBLOCKS_LEVELUP();
                case (9): return new MSG_SOBLOCKS_LOSS();
                case (10): return new MSG_SOBLOCKS_PAUSE();
                case (11): return new MSG_SOBLOCKS_PAUSEOFF();
                case (12): return new MSG_SOBLOCKS_PAUSEON();
                case (13): return new MSG_SOBLOCKS_READY();
                case (14): return new MSG_SOBLOCKS_REQUESTROW();
                case (15): return new MSG_SOBLOCKS_RESETGAME();
                case (16): return new MSG_SOBLOCKS_ROCKDROP();
                case (17): return new MSG_SOBLOCKS_ROWINFO();
                case (18): return new MSG_SOBLOCKS_SELECTGAME();
                case (19): return new MSG_SOBLOCKS_SENDROW();
                case (20): return new MSG_SOBLOCKS_SETLEVEL();
                case (21): return new MSG_SOBLOCKS_STARTSWAP();
                case (22): return new MSG_SOBLOCKS_TIMEDDROP();
                case (23): return new MSG_SOBLOCKS_WIN();
                default: throw new InternalException($"No message was found at ID {id} for this protocol!");
            }
        }
        public sealed class MSG_SOBLOCKS_ADVANCEOFF : INetworkMessage
        {
            public byte MessageOrder { get; } = 1;
        }
        public sealed class MSG_SOBLOCKS_ADVANCEON : INetworkMessage
        {
            public byte MessageOrder { get; } = 2;
        }
        public sealed class MSG_SOBLOCKS_ATTACK : INetworkMessage
        {
            [DMLElement(DMLType.INT)] public Int32 Index1;
            [DMLElement(DMLType.INT)] public Int32 Index2;
            [DMLElement(DMLType.INT)] public Int32 Index3;
            [DMLElement(DMLType.INT)] public Int32 Index4;
            [DMLElement(DMLType.INT)] public Int32 Index5;
            [DMLElement(DMLType.INT)] public Int32 Index6;
            [DMLElement(DMLType.INT)] public Int32 Index7;
            public byte MessageOrder { get; } = 3;
        }
        public sealed class MSG_SOBLOCKS_COUNTDOWN : INetworkMessage
        {
            [DMLElement(DMLType.INT)] public Int32 Number;
            public byte MessageOrder { get; } = 4;
        }
        public sealed class MSG_SOBLOCKS_ENDGAME : INetworkMessage
        {
            [DMLElement(DMLType.INT)] public Int32 Score;
            public byte MessageOrder { get; } = 5;
        }
        public sealed class MSG_SOBLOCKS_FREEZEBLOCKS : INetworkMessage
        {
            [DMLElement(DMLType.INT)] public Int32 Amount;
            public byte MessageOrder { get; } = 6;
        }
        public sealed class MSG_SOBLOCKS_INFO : INetworkMessage
        {
            [DMLElement(DMLType.STR)] public String Name;
            public byte MessageOrder { get; } = 7;
        }
        public sealed class MSG_SOBLOCKS_LEVELUP : INetworkMessage
        {
            public byte MessageOrder { get; } = 8;
        }
        public sealed class MSG_SOBLOCKS_LOSS : INetworkMessage
        {
            public byte MessageOrder { get; } = 9;
        }
        public sealed class MSG_SOBLOCKS_PAUSE : INetworkMessage
        {
            public byte MessageOrder { get; } = 10;
        }
        public sealed class MSG_SOBLOCKS_PAUSEOFF : INetworkMessage
        {
            public byte MessageOrder { get; } = 11;
        }
        public sealed class MSG_SOBLOCKS_PAUSEON : INetworkMessage
        {
            public byte MessageOrder { get; } = 12;
        }
        public sealed class MSG_SOBLOCKS_READY : INetworkMessage
        {
            public byte MessageOrder { get; } = 13;
        }
        public sealed class MSG_SOBLOCKS_REQUESTROW : INetworkMessage
        {
            public byte MessageOrder { get; } = 14;
        }
        public sealed class MSG_SOBLOCKS_RESETGAME : INetworkMessage
        {
            public byte MessageOrder { get; } = 15;
        }
        public sealed class MSG_SOBLOCKS_ROCKDROP : INetworkMessage
        {
            public byte MessageOrder { get; } = 16;
        }
        public sealed class MSG_SOBLOCKS_ROWINFO : INetworkMessage
        {
            [DMLElement(DMLType.INT)] public Int32 Index1;
            [DMLElement(DMLType.INT)] public Int32 Index2;
            [DMLElement(DMLType.INT)] public Int32 Index3;
            [DMLElement(DMLType.INT)] public Int32 Index4;
            [DMLElement(DMLType.INT)] public Int32 Index5;
            [DMLElement(DMLType.INT)] public Int32 Index6;
            [DMLElement(DMLType.INT)] public Int32 Index7;
            public byte MessageOrder { get; } = 17;
        }
        public sealed class MSG_SOBLOCKS_SELECTGAME : INetworkMessage
        {
            [DMLElement(DMLType.INT)] public Int32 GameType;
            public byte MessageOrder { get; } = 18;
        }
        public sealed class MSG_SOBLOCKS_SENDROW : INetworkMessage
        {
            [DMLElement(DMLType.INT)] public Int32 Index1;
            [DMLElement(DMLType.INT)] public Int32 Index2;
            [DMLElement(DMLType.INT)] public Int32 Index3;
            [DMLElement(DMLType.INT)] public Int32 Index4;
            [DMLElement(DMLType.INT)] public Int32 Index5;
            [DMLElement(DMLType.INT)] public Int32 Index6;
            [DMLElement(DMLType.INT)] public Int32 Index7;
            public byte MessageOrder { get; } = 19;
        }
        public sealed class MSG_SOBLOCKS_SETLEVEL : INetworkMessage
        {
            [DMLElement(DMLType.INT)] public Int32 Speed;
            [DMLElement(DMLType.INT)] public Int32 SpeedUp;
            [DMLElement(DMLType.INT)] public Int32 FallSpeed;
            [DMLElement(DMLType.INT)] public Int32 RemoveSpeed;
            [DMLElement(DMLType.INT)] public Int32 Bonus;
            [DMLElement(DMLType.INT)] public Int32 ComboTime;
            [DMLElement(DMLType.INT)] public Int32 MultiTime;
            public byte MessageOrder { get; } = 20;
        }
        public sealed class MSG_SOBLOCKS_STARTSWAP : INetworkMessage
        {
            public byte MessageOrder { get; } = 21;
        }
        public sealed class MSG_SOBLOCKS_TIMEDDROP : INetworkMessage
        {
            [DMLElement(DMLType.INT)] public Int32 Index1;
            [DMLElement(DMLType.INT)] public Int32 Index2;
            [DMLElement(DMLType.INT)] public Int32 Index3;
            [DMLElement(DMLType.INT)] public Int32 Index4;
            [DMLElement(DMLType.INT)] public Int32 Index5;
            [DMLElement(DMLType.INT)] public Int32 Index6;
            [DMLElement(DMLType.INT)] public Int32 Index7;
            public byte MessageOrder { get; } = 22;
        }
        public sealed class MSG_SOBLOCKS_WIN : INetworkMessage
        {
            public byte MessageOrder { get; } = 23;
        }
    }
}
