//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Imlight.Internals.DML
{
    using System;
    public sealed class WIZARDHOUSING_50_PROTOCOL : INetworkProtocol
    {
        public byte ServiceID { get; } = 50;
        public string ProtocolType { get; } = "WIZARDHOUSING";
        public Int32 ProtocolVersion { get; } = 1;
        public string ProtocolDescription { get; } = "Wizard Housing Messages";
        // == RECORDS ==
        public INetworkMessage Dispatch(byte id)
        {
            switch (id)
            {
                case (1): return new MSG_ADDFISHTOAQUARIUM();
                case (2): return new MSG_ADDINSTANCEFISH();
                case (3): return new MSG_ADDTOTREASURECARDPOSTER();
                case (4): return new MSG_AUDITATTICRESULTS();
                case (5): return new MSG_BEGINFISHINGCAST();
                case (6): return new MSG_BLOCKPETSPAWN();
                case (7): return new MSG_BUYISLANDSPACECONFIRM();
                case (8): return new MSG_CASTLEGAMESREQUEST();
                case (9): return new MSG_CASTLEGAMESREQUESTGAMEDATA();
                case (10): return new MSG_CASTLEGAMESTELEPORTREJECTED();
                case (11): return new MSG_CASTLEMAGICCHANGEACTION();
                case (12): return new MSG_CASTLEMAGICCLEAR();
                case (13): return new MSG_CASTLEMAGICCURRENTSTATE();
                case (14): return new MSG_CASTLEMAGICORB();
                case (15): return new MSG_CASTLEMAGICREQUESTALLOWMOUNTS();
                case (16): return new MSG_CASTLEMAGICREQUESTALLOWPVP();
                case (17): return new MSG_CASTLEMAGICREQUESTPLAYERTELEPORT();
                case (18): return new MSG_CASTLEMAGICREQUESTRANDOM();
                case (19): return new MSG_CASTLEMAGICREQUESTUSE();
                case (20): return new MSG_CASTLEMAGICTUTORIAL();
                case (21): return new MSG_CASTLEMAGICUPDATESTATE();
                case (22): return new MSG_CASTLETOURSADD();
                case (23): return new MSG_CASTLETOURSADDRESULT();
                case (24): return new MSG_CASTLETOURSCSRRESULTS();
                case (25): return new MSG_CASTLETOURSDELETECHARACTER();
                case (26): return new MSG_CASTLETOURSENABLERATINGDISPLAY();
                case (27): return new MSG_CASTLETOURSLEADERBOARDRESPONSE();
                case (28): return new MSG_CASTLETOURSPLAYERBANNED();
                case (29): return new MSG_CASTLETOURSRATINGDISPLAY();
                case (30): return new MSG_CASTLETOURSREMOVE();
                case (31): return new MSG_CASTLETOURSREMOVERESULT();
                case (32): return new MSG_CASTLETOURSREQUEST();
                case (33): return new MSG_CASTLETOURSREQUESTFRIENDS();
                case (34): return new MSG_CASTLETOURSREQUESTLEADERBOARD();
                case (35): return new MSG_CASTLETOURSREQUESTMYCASTLEDATA();
                case (36): return new MSG_CASTLETOURSREQUESTMYCASTLES();
                case (37): return new MSG_CASTLETOURSSENDRATING();
                case (38): return new MSG_CASTLETOURSTELEPORTPLAYER();
                case (39): return new MSG_CASTLETOURSTELEPORTREJECTED();
                case (40): return new MSG_CASTLETOURSVISITCASTLE();
                case (41): return new MSG_CATCHFISH();
                case (42): return new MSG_CATCHOFTHEDAYOPEN();
                case (43): return new MSG_CATCHSUCCESS();
                case (44): return new MSG_CHANGEBREADCRUMBREQUEST();
                case (45): return new MSG_CREATETESTISLAND();
                case (46): return new MSG_DAILYPVPOPEN();
                case (47): return new MSG_DAILYQUESTCOMPLETED();
                case (48): return new MSG_DAILYQUESTCSRDATA();
                case (49): return new MSG_DAILYQUESTEXPLORE();
                case (50): return new MSG_DAILYQUESTOPEN();
                case (51): return new MSG_DELETEEQUIPPEDHOUSINGITEM();
                case (52): return new MSG_DELETEFISH();
                case (53): return new MSG_DELETEFROMATTIC();
                case (54): return new MSG_DELETEMUSICLOOP();
                case (55): return new MSG_DISPLAYCATCHFISH();
                case (56): return new MSG_DISPLAYCAUGHTFISH();
                case (57): return new MSG_DISPOSABLEDUNGEONNOOWNER();
                case (58): return new MSG_DailyPvPUpdate();
                case (59): return new MSG_DailyQuestUpdate();
                case (60): return new MSG_EMPTYLOTCHECK();
                case (61): return new MSG_ENDFISHINGCAST();
                case (62): return new MSG_ENTERTOURNAMENTFISH();
                case (63): return new MSG_ENTERTOURNAMENTFISHRESULT();
                case (64): return new MSG_EQUIPHOUSEMUSIC();
                case (65): return new MSG_EQUIPMANNEQUINITEM();
                case (66): return new MSG_FISHESCAPED();
                case (67): return new MSG_FISHINGCSRRESULTS();
                case (68): return new MSG_FISHINGSPELLCAST();
                case (69): return new MSG_FISHTOURNAMENTLEADERBOARDOPEN();
                case (70): return new MSG_FISHTOURNAMENTLEADERBOARDREQUEST();
                case (71): return new MSG_FISHTOURNAMENTOPEN();
                case (72): return new MSG_GARDENINGCASTSPELL();
                case (73): return new MSG_GARDENINGCOMMAND();
                case (74): return new MSG_GARDENINGCOMMANDRESPONSE();
                case (75): return new MSG_GARDENINGCSRRESULTS();
                case (76): return new MSG_GARDENINGHARVESTPLANT();
                case (77): return new MSG_GARDENINGHARVESTPLANTSECONDSPRING();
                case (78): return new MSG_GARDENINGPELLFIZZLE();
                case (79): return new MSG_GARDENINGSPELLINSPECT();
                case (80): return new MSG_GARDENLEVELUP();
                case (81): return new MSG_HIDEHOUSINGOBJECT();
                case (82): return new MSG_HOUSINGGAMEREQUESTPOWERUPLOCATIONS();
                case (83): return new MSG_HOUSINGGAMESTATUSUPDATE();
                case (84): return new MSG_HOUSINGGAMEUSEPOWERUP();
                case (85): return new MSG_HOUSINGOBJECTNOPICKUP();
                case (86): return new MSG_HOUSINGOBJECTPROXIMITY();
                case (87): return new MSG_HOUSINGZONEPLAYER();
                case (88): return new MSG_HOUSINGZONEPLAYERLIST();
                case (89): return new MSG_INTERACTIVEMUSICERROR();
                case (90): return new MSG_INTERACTIVEMUSICINUSE();
                case (91): return new MSG_INTERACTIVEMUSICINUSE2();
                case (92): return new MSG_ISLANDSPACEBUYREQUEST();
                case (93): return new MSG_ISLANDSPACESHOPOPEN();
                case (94): return new MSG_MISSFISH();
                case (95): return new MSG_MONSTERMAGICADDMONSTER();
                case (96): return new MSG_MONSTERMAGICERASEMONSTER();
                case (97): return new MSG_MOVEFROMATTIC();
                case (98): return new MSG_MOVEGEARFROMGEARVAULT();
                case (99): return new MSG_MOVEGEARTOGEARVAULT();
                case (100): return new MSG_MOVEJEWELFROMJEWELVAULT();
                case (101): return new MSG_MOVEJEWELTOJEWELVAULT();
                case (102): return new MSG_MOVESEEDFROMGARDENINGSHED();
                case (103): return new MSG_MOVESEEDTOGARDENINGSHED();
                case (104): return new MSG_MOVETCFROMTCVAULT();
                case (105): return new MSG_MOVETCTOTCVAULT();
                case (106): return new MSG_MOVETOATTIC();
                case (107): return new MSG_NOFISHSPACE();
                case (108): return new MSG_PATCHADDATTIC();
                case (109): return new MSG_PATCHADDHOUSINGOBJECT();
                case (110): return new MSG_PATCHAQUARIUM();
                case (111): return new MSG_PATCHCASTLEMAGIC();
                case (112): return new MSG_PATCHDELETEATTIC();
                case (113): return new MSG_PATCHDELETEHOUSINGOBJECT();
                case (114): return new MSG_PATCHEQUIPHOUSINGOBJECT();
                case (115): return new MSG_PATCHGARDENING();
                case (116): return new MSG_PATCHHOUSE();
                case (117): return new MSG_PATCHHOUSINGBREADCRUMB();
                case (118): return new MSG_PATCHHOUSINGGARDENINGSHED();
                case (119): return new MSG_PATCHHOUSINGGEARVAULT();
                case (120): return new MSG_PATCHHOUSINGJEWELVAULT();
                case (121): return new MSG_PATCHHOUSINGMUSICOBJECT();
                case (122): return new MSG_PATCHHOUSINGSIGNOBJECT();
                case (123): return new MSG_PATCHHOUSINGTELEPORTEROBJECT();
                case (124): return new MSG_PATCHMONSTERARENA();
                case (125): return new MSG_PATCHMUSICLOOP();
                case (126): return new MSG_PATCHREMOVETEXTUREREMAP();
                case (127): return new MSG_PATCHTEXTUREREMAP();
                case (128): return new MSG_PATCHTINTHOUSINGOBJECT();
                case (129): return new MSG_PATCHTREASURECARDPOSTER();
                case (130): return new MSG_PATCHTREASURECARDVAULT();
                case (131): return new MSG_PATCHUPDATEHOUSINGOBJECT();
                case (132): return new MSG_PATCHUPEXTENDEDTILE();
                case (133): return new MSG_PETTOMESCANATTIC();
                case (134): return new MSG_PICKUPALL();
                case (135): return new MSG_PICKUPHOUSINGTEXTURE();
                case (136): return new MSG_PLACEHOUSINGFISH();
                case (137): return new MSG_PLACEHOUSINGOBJECT();
                case (138): return new MSG_PLAYERTELEPORTINGTOFRIEND();
                case (139): return new MSG_PLAYINTERACTIVEMUSIC();
                case (140): return new MSG_PLAYINTERACTIVEMUSIC2();
                case (141): return new MSG_PLAYINTERACTIVEMUSICLOOP();
                case (142): return new MSG_PLAYINTERACTIVEMUSICLOOPING();
                case (143): return new MSG_PLAYINTERACTIVEMUSICLOOPING2();
                case (144): return new MSG_REMOVEFISHFROMAQUARIUM();
                case (145): return new MSG_REMOVEHOUSEMUSIC();
                case (146): return new MSG_REPORTHOUSE();
                case (147): return new MSG_REQUESTALLFISH();
                case (148): return new MSG_REQUESTATTIC();
                case (149): return new MSG_REQUESTCATCHSUCCESS();
                case (150): return new MSG_REQUESTDEEDZONE();
                case (151): return new MSG_REQUESTFISHHISTORY();
                case (152): return new MSG_REQUESTHOUSEOWNERCHARACTERID();
                case (153): return new MSG_REQUESTHOUSETRANSFERLIST();
                case (154): return new MSG_REQUESTHOUSINGZONE();
                case (155): return new MSG_REQUESTHOUSINGZONETELEPORT();
                case (156): return new MSG_REQUESTINTERACTIVEMUSIC();
                case (157): return new MSG_REQUESTISLANDSWITCH();
                case (158): return new MSG_REQUESTSENDAWAY();
                case (159): return new MSG_REQUESTTELEPORTERHOUSINGCONFIRM();
                case (160): return new MSG_REQUESTTELEPORTERHOUSINGZONE();
                case (161): return new MSG_REQUEST_BLOBS();
                case (162): return new MSG_RESPEC();
                case (163): return new MSG_SELECTHOUSEMUSIC();
                case (164): return new MSG_SELECTMUSICSTYLE();
                case (165): return new MSG_SELLFISHOPEN();
                case (166): return new MSG_SELLFISHREQUEST();
                case (167): return new MSG_SENDHOUSINGOBJECTSTATES();
                case (168): return new MSG_SENDHOUSINGTEXTUREINFO();
                case (169): return new MSG_SEND_BLOB();
                case (170): return new MSG_SETATTICID();
                case (171): return new MSG_SETFISHINGPLAYERS();
                case (172): return new MSG_SETHOUSESIGN();
                case (173): return new MSG_SETHOUSETELEPORTER();
                case (174): return new MSG_SETHOUSINGGAMESTATE();
                case (175): return new MSG_SETHOUSINGPALETTE();
                case (176): return new MSG_SETINSTANCEFISH();
                case (177): return new MSG_SETINVISIBLETOFRIENDS();
                case (178): return new MSG_SETMUSICLOOP();
                case (179): return new MSG_SETTILEWALLPAPER();
                case (180): return new MSG_SHOWFISHINGCAST();
                case (181): return new MSG_STARTHOUSINGGAME();
                case (182): return new MSG_STOPINTERACTIVEMUSICLOOP();
                case (183): return new MSG_SWITCHGOTOCOMMONS();
                case (184): return new MSG_TELEPORTEDTODELETEDLOT();
                case (185): return new MSG_UPDATEATTICCOUNT();
                case (186): return new MSG_UPDATEGARDENINGXP();
                case (187): return new MSG_UPDATEHOUSINGOBJECT();
                case (188): return new MSG_UPDATEHOUSINGPET();
                case (189): return new MSG_UPDATEISLANDSPACE();
                case (190): return new MSG_UPDATEMAXIMUMHOUSINGITEMS();
                default: throw new InternalException($"No message was found at ID {id} for this protocol!");
            }
        }
        public sealed class MSG_ADDFISHTOAQUARIUM : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("UINT")] public UInt32 FishTemplateID;
            [DMLElement("FLT")] public Single Size;
            public byte MessageOrder { get; } = 1;
        }
        public sealed class MSG_ADDINSTANCEFISH : INetworkMessage
        {
            [DMLElement("UINT")] public UInt32 ZoneNameID;
            [DMLElement("UINT")] public UInt32 FishTemplateID;
            [DMLElement("FLT")] public Single Size;
            [DMLElement("UINT")] public UInt32 FishID;
            public byte MessageOrder { get; } = 2;
        }
        public sealed class MSG_ADDTOTREASURECARDPOSTER : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 TreasureCardPosterID;
            [DMLElement("UINT")] public UInt32 SpellTemplateID;
            [DMLElement("UINT")] public UInt32 EnchantmentTemplateID;
            [DMLElement("UBYT")] public Byte Flags;
            public byte MessageOrder { get; } = 3;
        }
        public sealed class MSG_AUDITATTICRESULTS : INetworkMessage
        {
            [DMLElement("UINT")] public UInt32 ItemsAudited;
            [DMLElement("UINT")] public UInt32 ItemsRemoved;
            public byte MessageOrder { get; } = 4;
        }
        public sealed class MSG_BEGINFISHINGCAST : INetworkMessage
        {
            [DMLElement("FLT")] public Single PositionX;
            [DMLElement("FLT")] public Single PositionY;
            [DMLElement("FLT")] public Single PositionZ;
            [DMLElement("FLT")] public Single EndX;
            [DMLElement("FLT")] public Single EndY;
            [DMLElement("FLT")] public Single EndZ;
            [DMLElement("FLT")] public Single Yaw;
            [DMLElement("UINT")] public UInt32 SpellTemplateID;
            [DMLElement("UBYT")] public Byte IsRecast;
            public byte MessageOrder { get; } = 5;
        }
        public sealed class MSG_BLOCKPETSPAWN : INetworkMessage
        {
            public byte MessageOrder { get; } = 6;
        }
        public sealed class MSG_BUYISLANDSPACECONFIRM : INetworkMessage
        {
            [DMLElement("BYT")] public SByte Failure;
            [DMLElement("BYT")] public SByte WebFailure;
            [DMLElement("INT")] public Int32 Credits;
            public byte MessageOrder { get; } = 7;
        }
        public sealed class MSG_CASTLEGAMESREQUEST : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            public byte MessageOrder { get; } = 8;
        }
        public sealed class MSG_CASTLEGAMESREQUESTGAMEDATA : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("UINT")] public UInt32 PageNumber;
            [DMLElement("STR")] public String Data;
            public byte MessageOrder { get; } = 9;
        }
        public sealed class MSG_CASTLEGAMESTELEPORTREJECTED : INetworkMessage
        {
            public byte MessageOrder { get; } = 10;
        }
        public sealed class MSG_CASTLEMAGICCHANGEACTION : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("UINT")] public UInt32 ActionNumber;
            [DMLElement("UINT")] public UInt32 SpellTemplateID;
            [DMLElement("UINT")] public UInt32 TargetTemplateID;
            [DMLElement("FLT")] public Single LocX;
            [DMLElement("FLT")] public Single LocY;
            [DMLElement("FLT")] public Single LocZ;
            public byte MessageOrder { get; } = 11;
        }
        public sealed class MSG_CASTLEMAGICCLEAR : INetworkMessage
        {
            public byte MessageOrder { get; } = 12;
        }
        public sealed class MSG_CASTLEMAGICCURRENTSTATE : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 TargetPlayer;
            [DMLElement("STR")] public String ChangeBuffer;
            [DMLElement("FLT")] public Single ZoneTime;
            [DMLElement("BYT")] public SByte OrbFlags;
            public byte MessageOrder { get; } = 13;
        }
        public sealed class MSG_CASTLEMAGICORB : INetworkMessage
        {
            [DMLElement("BYT")] public SByte OrbFlags;
            public byte MessageOrder { get; } = 14;
        }
        public sealed class MSG_CASTLEMAGICREQUESTALLOWMOUNTS : INetworkMessage
        {
            [DMLElement("BYT")] public SByte State;
            public byte MessageOrder { get; } = 15;
        }
        public sealed class MSG_CASTLEMAGICREQUESTALLOWPVP : INetworkMessage
        {
            [DMLElement("BYT")] public SByte State;
            public byte MessageOrder { get; } = 16;
        }
        public sealed class MSG_CASTLEMAGICREQUESTPLAYERTELEPORT : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 TargetPlayerGID;
            [DMLElement("GID")] public UInt64 TargetGID;
            public byte MessageOrder { get; } = 17;
        }
        public sealed class MSG_CASTLEMAGICREQUESTRANDOM : INetworkMessage
        {
            [DMLElement("STR")] public String Buffer;
            public byte MessageOrder { get; } = 18;
        }
        public sealed class MSG_CASTLEMAGICREQUESTUSE : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 ItemGID;
            public byte MessageOrder { get; } = 19;
        }
        public sealed class MSG_CASTLEMAGICTUTORIAL : INetworkMessage
        {
            [DMLElement("BYT")] public SByte State;
            public byte MessageOrder { get; } = 20;
        }
        public sealed class MSG_CASTLEMAGICUPDATESTATE : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("UINT")] public UInt32 State;
            [DMLElement("UINT")] public UInt32 RandomNumbers;
            public byte MessageOrder { get; } = 21;
        }
        public sealed class MSG_CASTLETOURSADD : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("GID")] public UInt64 HouseGID;
            [DMLElement("BYT")] public SByte HouseType;
            public byte MessageOrder { get; } = 22;
        }
        public sealed class MSG_CASTLETOURSADDRESULT : INetworkMessage
        {
            [DMLElement("UINT")] public UInt32 Status;
            public byte MessageOrder { get; } = 23;
        }
        public sealed class MSG_CASTLETOURSCSRRESULTS : INetworkMessage
        {
            [DMLElement("STR")] public String Result;
            public byte MessageOrder { get; } = 24;
        }
        public sealed class MSG_CASTLETOURSDELETECHARACTER : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 CharacterID;
            public byte MessageOrder { get; } = 25;
        }
        public sealed class MSG_CASTLETOURSENABLERATINGDISPLAY : INetworkMessage
        {
            [DMLElement("BYT")] public SByte CastleType;
            [DMLElement("BYT")] public SByte Rating;
            [DMLElement("BYT")] public SByte FirstDisplay;
            [DMLElement("UINT")] public UInt32 TemplateID;
            public byte MessageOrder { get; } = 26;
        }
        public sealed class MSG_CASTLETOURSLEADERBOARDRESPONSE : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 CharacterID;
            [DMLElement("BYT")] public SByte LeaderboardType;
            [DMLElement("BYT")] public SByte SortType;
            [DMLElement("UINT")] public UInt32 PageNumber;
            [DMLElement("STR")] public String LeaderboardData;
            public byte MessageOrder { get; } = 27;
        }
        public sealed class MSG_CASTLETOURSPLAYERBANNED : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            public byte MessageOrder { get; } = 28;
        }
        public sealed class MSG_CASTLETOURSRATINGDISPLAY : INetworkMessage
        {
            public byte MessageOrder { get; } = 29;
        }
        public sealed class MSG_CASTLETOURSREMOVE : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("GID")] public UInt64 HouseGID;
            public byte MessageOrder { get; } = 30;
        }
        public sealed class MSG_CASTLETOURSREMOVERESULT : INetworkMessage
        {
            [DMLElement("UINT")] public UInt32 Status;
            public byte MessageOrder { get; } = 31;
        }
        public sealed class MSG_CASTLETOURSREQUEST : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            public byte MessageOrder { get; } = 32;
        }
        public sealed class MSG_CASTLETOURSREQUESTFRIENDS : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 CharacterID;
            [DMLElement("STR")] public String Data;
            public byte MessageOrder { get; } = 33;
        }
        public sealed class MSG_CASTLETOURSREQUESTLEADERBOARD : INetworkMessage
        {
            [DMLElement("BYT")] public SByte LeaderboardType;
            [DMLElement("BYT")] public SByte SortType;
            [DMLElement("UINT")] public UInt32 PageNumber;
            [DMLElement("STR")] public String LeaderboardData;
            public byte MessageOrder { get; } = 34;
        }
        public sealed class MSG_CASTLETOURSREQUESTMYCASTLEDATA : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("STR")] public String Data;
            public byte MessageOrder { get; } = 35;
        }
        public sealed class MSG_CASTLETOURSREQUESTMYCASTLES : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("STR")] public String Data;
            [DMLElement("BYT")] public SByte Days;
            public byte MessageOrder { get; } = 36;
        }
        public sealed class MSG_CASTLETOURSSENDRATING : INetworkMessage
        {
            [DMLElement("BYT")] public SByte Rating;
            public byte MessageOrder { get; } = 37;
        }
        public sealed class MSG_CASTLETOURSTELEPORTPLAYER : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 CharacterID;
            [DMLElement("STR")] public String TeleportData;
            [DMLElement("BYT")] public SByte Source;
            public byte MessageOrder { get; } = 38;
        }
        public sealed class MSG_CASTLETOURSTELEPORTREJECTED : INetworkMessage
        {
            public byte MessageOrder { get; } = 39;
        }
        public sealed class MSG_CASTLETOURSVISITCASTLE : INetworkMessage
        {
            [DMLElement("BYT")] public SByte VisitType;
            [DMLElement("BYT")] public SByte HouseType;
            public byte MessageOrder { get; } = 40;
        }
        public sealed class MSG_CATCHFISH : INetworkMessage
        {
            [DMLElement("UINT")] public UInt32 SpellTemplateID;
            [DMLElement("UBYT")] public Byte IsTreasureCard;
            [DMLElement("UINT")] public UInt32 FishingPassport;
            [DMLElement("UINT")] public UInt32 FishID;
            public byte MessageOrder { get; } = 41;
        }
        public sealed class MSG_CATCHOFTHEDAYOPEN : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("UINT")] public UInt32 FishTemplateID;
            [DMLElement("UINT")] public UInt32 CatchOfTheDayBonus;
            public byte MessageOrder { get; } = 42;
        }
        public sealed class MSG_CATCHSUCCESS : INetworkMessage
        {
            [DMLElement("UINT")] public UInt32 FishID;
            [DMLElement("UBYT")] public Byte Assist;
            public byte MessageOrder { get; } = 43;
        }
        public sealed class MSG_CHANGEBREADCRUMBREQUEST : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 BreadCrumbGID;
            [DMLElement("GID")] public UInt64 OtherGID;
            [DMLElement("BYT")] public SByte AddPet;
            [DMLElement("BYT")] public SByte LinkBreadCrumb;
            [DMLElement("BYT")] public SByte SetPetBehavior;
            public byte MessageOrder { get; } = 44;
        }
        public sealed class MSG_CREATETESTISLAND : INetworkMessage
        {
            [DMLElement("UINT")] public UInt32 DeedGID;
            [DMLElement("UINT")] public UInt32 StructureGID;
            public byte MessageOrder { get; } = 45;
        }
        public sealed class MSG_DAILYPVPOPEN : INetworkMessage
        {
            public byte MessageOrder { get; } = 46;
        }
        public sealed class MSG_DAILYQUESTCOMPLETED : INetworkMessage
        {
            [DMLElement("UINT")] public UInt32 QuestIndex;
            [DMLElement("UBYT")] public Byte CurrentCircle;
            [DMLElement("UBYT")] public Byte ConsecutiveDays;
            [DMLElement("UBYT")] public Byte Flags;
            [DMLElement("UINT")] public UInt32 ItemTemplateID;
            public byte MessageOrder { get; } = 47;
        }
        public sealed class MSG_DAILYQUESTCSRDATA : INetworkMessage
        {
            [DMLElement("STR")] public String QuestData;
            public byte MessageOrder { get; } = 48;
        }
        public sealed class MSG_DAILYQUESTEXPLORE : INetworkMessage
        {
            [DMLElement("FLT")] public Single LocX;
            [DMLElement("FLT")] public Single LocY;
            [DMLElement("FLT")] public Single LocZ;
            [DMLElement("FLT")] public Single Radius;
            public byte MessageOrder { get; } = 49;
        }
        public sealed class MSG_DAILYQUESTOPEN : INetworkMessage
        {
            public byte MessageOrder { get; } = 50;
        }
        public sealed class MSG_DELETEEQUIPPEDHOUSINGITEM : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 ObjectGID;
            [DMLElement("GID")] public UInt64 ItemGID;
            [DMLElement("STR")] public String SlotName;
            public byte MessageOrder { get; } = 51;
        }
        public sealed class MSG_DELETEFISH : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("UINT")] public UInt32 FishTemplateID;
            [DMLElement("FLT")] public Single Size;
            public byte MessageOrder { get; } = 52;
        }
        public sealed class MSG_DELETEFROMATTIC : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("GID")] public UInt64 ItemID;
            public byte MessageOrder { get; } = 53;
        }
        public sealed class MSG_DELETEMUSICLOOP : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 ObjectGID;
            [DMLElement("UINT")] public UInt32 LoopNumber;
            public byte MessageOrder { get; } = 54;
        }
        public sealed class MSG_DISPLAYCATCHFISH : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 ObjectGID;
            [DMLElement("UINT")] public UInt32 FishTemplateID;
            [DMLElement("FLT")] public Single Size;
            [DMLElement("UINT")] public UInt32 SpellTemplateID;
            public byte MessageOrder { get; } = 55;
        }
        public sealed class MSG_DISPLAYCAUGHTFISH : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 ObjectGID;
            [DMLElement("UINT")] public UInt32 FishTemplateID;
            [DMLElement("FLT")] public Single Length;
            [DMLElement("UBYT")] public Byte IsSmallFry;
            [DMLElement("UBYT")] public Byte IsWopper;
            [DMLElement("STR")] public String LootData;
            [DMLElement("UBYT")] public Byte Energy;
            [DMLElement("UBYT")] public Byte IsTournamentFish;
            [DMLElement("UINT")] public UInt32 CatchOfTheDayBonus;
            public byte MessageOrder { get; } = 56;
        }
        public sealed class MSG_DISPOSABLEDUNGEONNOOWNER : INetworkMessage
        {
            public byte MessageOrder { get; } = 57;
        }
        public sealed class MSG_DailyPvPUpdate : INetworkMessage
        {
            [DMLElement("UBYT")] public Byte ConsecutiveDays;
            [DMLElement("UBYT")] public Byte Flags;
            [DMLElement("UINT")] public UInt32 TimeLeft;
            public byte MessageOrder { get; } = 58;
        }
        public sealed class MSG_DailyQuestUpdate : INetworkMessage
        {
            [DMLElement("UINT")] public UInt32 QuestIndex;
            [DMLElement("UBYT")] public Byte CurrentCircle;
            [DMLElement("UBYT")] public Byte ConsecutiveDays;
            [DMLElement("UBYT")] public Byte Flags;
            [DMLElement("UINT")] public UInt32 TimeLeft;
            public byte MessageOrder { get; } = 59;
        }
        public sealed class MSG_EMPTYLOTCHECK : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 EmptyLotGID;
            public byte MessageOrder { get; } = 60;
        }
        public sealed class MSG_ENDFISHINGCAST : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 ObjectGID;
            public byte MessageOrder { get; } = 61;
        }
        public sealed class MSG_ENTERTOURNAMENTFISH : INetworkMessage
        {
            [DMLElement("UINT")] public UInt32 FishTemplateID;
            [DMLElement("FLT")] public Single FishSize;
            public byte MessageOrder { get; } = 62;
        }
        public sealed class MSG_ENTERTOURNAMENTFISHRESULT : INetworkMessage
        {
            [DMLElement("INT")] public Int32 Position;
            public byte MessageOrder { get; } = 63;
        }
        public sealed class MSG_EQUIPHOUSEMUSIC : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 MusicPlayerGID;
            [DMLElement("GID")] public UInt64 MusicGID;
            public byte MessageOrder { get; } = 64;
        }
        public sealed class MSG_EQUIPMANNEQUINITEM : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 MannequinGID;
            [DMLElement("INT")] public Int32 IsEquip;
            [DMLElement("GID")] public UInt64 ItemID;
            [DMLElement("STR")] public String SlotName;
            public byte MessageOrder { get; } = 65;
        }
        public sealed class MSG_FISHESCAPED : INetworkMessage
        {
            [DMLElement("UINT")] public UInt32 FishID;
            public byte MessageOrder { get; } = 66;
        }
        public sealed class MSG_FISHINGCSRRESULTS : INetworkMessage
        {
            [DMLElement("STR")] public String Result;
            public byte MessageOrder { get; } = 67;
        }
        public sealed class MSG_FISHINGSPELLCAST : INetworkMessage
        {
            [DMLElement("UINT")] public UInt32 SpellTemplateID;
            [DMLElement("UBYT")] public Byte IsTreasureCard;
            [DMLElement("UINT")] public UInt32 FishingPassport;
            [DMLElement("UBYT")] public Byte IsRecast;
            public byte MessageOrder { get; } = 68;
        }
        public sealed class MSG_FISHTOURNAMENTLEADERBOARDOPEN : INetworkMessage
        {
            [DMLElement("UINT")] public UInt32 ThisWeeksExpireTime;
            [DMLElement("UINT")] public UInt32 LastWeeksExpireTime;
            public byte MessageOrder { get; } = 69;
        }
        public sealed class MSG_FISHTOURNAMENTLEADERBOARDREQUEST : INetworkMessage
        {
            [DMLElement("UINT")] public UInt32 ExpireTime;
            [DMLElement("UINT")] public UInt32 PageNumber;
            [DMLElement("STR")] public String Data;
            public byte MessageOrder { get; } = 70;
        }
        public sealed class MSG_FISHTOURNAMENTOPEN : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("UINT")] public UInt32 FishTemplateID;
            [DMLElement("UINT")] public UInt32 FishSizeTarget;
            public byte MessageOrder { get; } = 71;
        }
        public sealed class MSG_GARDENINGCASTSPELL : INetworkMessage
        {
            [DMLElement("UINT")] public UInt32 SpellTemplateID;
            [DMLElement("GID")] public UInt64 PlayerGID;
            [DMLElement("FLT")] public Single PositionX;
            [DMLElement("FLT")] public Single PositionY;
            [DMLElement("FLT")] public Single PositionZ;
            public byte MessageOrder { get; } = 72;
        }
        public sealed class MSG_GARDENINGCOMMAND : INetworkMessage
        {
            [DMLElement("UBYT")] public Byte Command;
            [DMLElement("FLT")] public Single PositionX;
            [DMLElement("FLT")] public Single PositionY;
            [DMLElement("FLT")] public Single PositionZ;
            [DMLElement("UINT")] public UInt32 TemplateID;
            [DMLElement("GID")] public UInt64 ObjectGID;
            [DMLElement("GID")] public UInt64 ZoneGID;
            public byte MessageOrder { get; } = 73;
        }
        public sealed class MSG_GARDENINGCOMMANDRESPONSE : INetworkMessage
        {
            public byte MessageOrder { get; } = 74;
        }
        public sealed class MSG_GARDENINGCSRRESULTS : INetworkMessage
        {
            [DMLElement("STR")] public String Result;
            public byte MessageOrder { get; } = 75;
        }
        public sealed class MSG_GARDENINGHARVESTPLANT : INetworkMessage
        {
            [DMLElement("FLT")] public Single PositionX;
            [DMLElement("FLT")] public Single PositionY;
            [DMLElement("FLT")] public Single PositionZ;
            [DMLElement("UINT")] public UInt32 PlantTemplateID;
            public byte MessageOrder { get; } = 76;
        }
        public sealed class MSG_GARDENINGHARVESTPLANTSECONDSPRING : INetworkMessage
        {
            [DMLElement("FLT")] public Single PositionX;
            [DMLElement("FLT")] public Single PositionY;
            [DMLElement("FLT")] public Single PositionZ;
            public byte MessageOrder { get; } = 77;
        }
        public sealed class MSG_GARDENINGPELLFIZZLE : INetworkMessage
        {
            [DMLElement("UBYT")] public Byte FizzleType;
            public byte MessageOrder { get; } = 78;
        }
        public sealed class MSG_GARDENINGSPELLINSPECT : INetworkMessage
        {
            [DMLElement("FLT")] public Single PositionX;
            [DMLElement("FLT")] public Single PositionY;
            [DMLElement("FLT")] public Single PositionZ;
            [DMLElement("FLT")] public Single Progress;
            public byte MessageOrder { get; } = 79;
        }
        public sealed class MSG_GARDENLEVELUP : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("INT")] public Int32 NewLevel;
            public byte MessageOrder { get; } = 80;
        }
        public sealed class MSG_HIDEHOUSINGOBJECT : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 ObjectGID;
            [DMLElement("INT")] public Int32 Hide;
            public byte MessageOrder { get; } = 81;
        }
        public sealed class MSG_HOUSINGGAMEREQUESTPOWERUPLOCATIONS : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 ZoneGID;
            [DMLElement("STR")] public String Data;
            public byte MessageOrder { get; } = 82;
        }
        public sealed class MSG_HOUSINGGAMESTATUSUPDATE : INetworkMessage
        {
            [DMLElement("UBYT")] public Byte Flags;
            public byte MessageOrder { get; } = 83;
        }
        public sealed class MSG_HOUSINGGAMEUSEPOWERUP : INetworkMessage
        {
            public byte MessageOrder { get; } = 84;
        }
        public sealed class MSG_HOUSINGOBJECTNOPICKUP : INetworkMessage
        {
            public byte MessageOrder { get; } = 85;
        }
        public sealed class MSG_HOUSINGOBJECTPROXIMITY : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 ObjectID;
            [DMLElement("INT")] public Int32 Inside;
            public byte MessageOrder { get; } = 86;
        }
        public sealed class MSG_HOUSINGZONEPLAYER : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 HousingPlayer;
            [DMLElement("BYT")] public SByte AddPlayer;
            public byte MessageOrder { get; } = 87;
        }
        public sealed class MSG_HOUSINGZONEPLAYERLIST : INetworkMessage
        {
            [DMLElement("STR")] public String PlayerListBuffer;
            [DMLElement("GID")] public UInt64 ZoneGID;
            [DMLElement("BYT")] public SByte OrbFlags;
            public byte MessageOrder { get; } = 88;
        }
        public sealed class MSG_INTERACTIVEMUSICERROR : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 ObjectGID;
            [DMLElement("BYT")] public SByte Error;
            public byte MessageOrder { get; } = 89;
        }
        public sealed class MSG_INTERACTIVEMUSICINUSE : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 PlayerGID;
            [DMLElement("BYT")] public SByte InUse;
            public byte MessageOrder { get; } = 90;
        }
        public sealed class MSG_INTERACTIVEMUSICINUSE2 : INetworkMessage
        {
            [DMLElement("STR")] public String Data;
            public byte MessageOrder { get; } = 91;
        }
        public sealed class MSG_ISLANDSPACEBUYREQUEST : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("BYT")] public SByte WebFailure;
            [DMLElement("INT")] public Int32 Credits;
            public byte MessageOrder { get; } = 92;
        }
        public sealed class MSG_ISLANDSPACESHOPOPEN : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("BYT")] public SByte WebFailure;
            [DMLElement("INT")] public Int32 Credits;
            public byte MessageOrder { get; } = 93;
        }
        public sealed class MSG_MISSFISH : INetworkMessage
        {
            [DMLElement("UINT")] public UInt32 SpellTemplateID;
            [DMLElement("UBYT")] public Byte IsTreasureCard;
            public byte MessageOrder { get; } = 94;
        }
        public sealed class MSG_MONSTERMAGICADDMONSTER : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("UINT")] public UInt32 SpellTemplateID;
            public byte MessageOrder { get; } = 95;
        }
        public sealed class MSG_MONSTERMAGICERASEMONSTER : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("UINT")] public UInt32 MobTemplateID;
            public byte MessageOrder { get; } = 96;
        }
        public sealed class MSG_MOVEFROMATTIC : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("GID")] public UInt64 ItemID;
            public byte MessageOrder { get; } = 97;
        }
        public sealed class MSG_MOVEGEARFROMGEARVAULT : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GearVaultGID;
            [DMLElement("STR")] public String GearData;
            public byte MessageOrder { get; } = 98;
        }
        public sealed class MSG_MOVEGEARTOGEARVAULT : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GearVaultGID;
            [DMLElement("GID")] public UInt64 GearGID;
            public byte MessageOrder { get; } = 99;
        }
        public sealed class MSG_MOVEJEWELFROMJEWELVAULT : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 JewelVaultID;
            [DMLElement("UINT")] public UInt32 JewelTemplateID;
            [DMLElement("UINT")] public UInt32 Count;
            public byte MessageOrder { get; } = 100;
        }
        public sealed class MSG_MOVEJEWELTOJEWELVAULT : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 JewelVaultID;
            [DMLElement("UINT")] public UInt32 JewelTemplateID;
            [DMLElement("UINT")] public UInt32 Count;
            public byte MessageOrder { get; } = 101;
        }
        public sealed class MSG_MOVESEEDFROMGARDENINGSHED : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GardeningShedID;
            [DMLElement("UINT")] public UInt32 SeedTemplateID;
            [DMLElement("UINT")] public UInt32 Count;
            public byte MessageOrder { get; } = 102;
        }
        public sealed class MSG_MOVESEEDTOGARDENINGSHED : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GardeningShedID;
            [DMLElement("UINT")] public UInt32 SeedTemplateID;
            [DMLElement("UINT")] public UInt32 Count;
            public byte MessageOrder { get; } = 103;
        }
        public sealed class MSG_MOVETCFROMTCVAULT : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 TCVaultID;
            [DMLElement("UINT")] public UInt32 SpellTemplateID;
            [DMLElement("UINT")] public UInt32 EnchantmentTemplateID;
            [DMLElement("UINT")] public UInt32 Count;
            public byte MessageOrder { get; } = 104;
        }
        public sealed class MSG_MOVETCTOTCVAULT : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 TCVaultID;
            [DMLElement("UINT")] public UInt32 SpellTemplateID;
            [DMLElement("UINT")] public UInt32 EnchantmentTemplateID;
            [DMLElement("UINT")] public UInt32 Count;
            public byte MessageOrder { get; } = 105;
        }
        public sealed class MSG_MOVETOATTIC : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("GID")] public UInt64 ItemID;
            public byte MessageOrder { get; } = 106;
        }
        public sealed class MSG_NOFISHSPACE : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GameObjectID;
            public byte MessageOrder { get; } = 107;
        }
        public sealed class MSG_PATCHADDATTIC : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 BlobGID;
            [DMLElement("GID")] public UInt64 ObjectID;
            [DMLElement("STR")] public String SubType;
            [DMLElement("UINT")] public UInt32 PackageNumber;
            [DMLElement("UINT")] public UInt32 VersionNumber;
            [DMLElement("UINT")] public UInt32 GIDID;
            [DMLElement("STR")] public String Data;
            [DMLElement("BYT")] public SByte PrimaryColorIndex;
            public byte MessageOrder { get; } = 108;
        }
        public sealed class MSG_PATCHADDHOUSINGOBJECT : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 ObjectID;
            [DMLElement("FLT")] public Single LocX;
            [DMLElement("FLT")] public Single LocY;
            [DMLElement("FLT")] public Single LocZ;
            [DMLElement("FLT")] public Single Yaw;
            [DMLElement("STR")] public String SubType;
            [DMLElement("UINT")] public UInt32 PackageNumber;
            [DMLElement("UINT")] public UInt32 VersionNumber;
            [DMLElement("UINT")] public UInt32 GIDID;
            [DMLElement("STR")] public String Data;
            [DMLElement("BYT")] public SByte ColorBits;
            public byte MessageOrder { get; } = 109;
        }
        public sealed class MSG_PATCHAQUARIUM : INetworkMessage
        {
            [DMLElement("STR")] public String Data;
            [DMLElement("STR")] public String SubType;
            [DMLElement("UINT")] public UInt32 PackageNumber;
            [DMLElement("UINT")] public UInt32 VersionNumber;
            [DMLElement("UINT")] public UInt32 GIDID;
            public byte MessageOrder { get; } = 110;
        }
        public sealed class MSG_PATCHCASTLEMAGIC : INetworkMessage
        {
            [DMLElement("STR")] public String Data;
            [DMLElement("STR")] public String SubType;
            [DMLElement("UINT")] public UInt32 PackageNumber;
            [DMLElement("UINT")] public UInt32 VersionNumber;
            [DMLElement("UINT")] public UInt32 GIDID;
            public byte MessageOrder { get; } = 111;
        }
        public sealed class MSG_PATCHDELETEATTIC : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 BlobGID;
            [DMLElement("GID")] public UInt64 ObjectID;
            [DMLElement("STR")] public String SubType;
            [DMLElement("UINT")] public UInt32 PackageNumber;
            [DMLElement("UINT")] public UInt32 VersionNumber;
            [DMLElement("UINT")] public UInt32 GIDID;
            public byte MessageOrder { get; } = 112;
        }
        public sealed class MSG_PATCHDELETEHOUSINGOBJECT : INetworkMessage
        {
            [DMLElement("STR")] public String SubType;
            [DMLElement("UINT")] public UInt32 PackageNumber;
            [DMLElement("UINT")] public UInt32 VersionNumber;
            [DMLElement("UINT")] public UInt32 GIDID;
            public byte MessageOrder { get; } = 113;
        }
        public sealed class MSG_PATCHEQUIPHOUSINGOBJECT : INetworkMessage
        {
            [DMLElement("STR")] public String Data;
            [DMLElement("STR")] public String SubType;
            [DMLElement("UINT")] public UInt32 PackageNumber;
            [DMLElement("UINT")] public UInt32 VersionNumber;
            [DMLElement("UINT")] public UInt32 GIDID;
            public byte MessageOrder { get; } = 114;
        }
        public sealed class MSG_PATCHGARDENING : INetworkMessage
        {
            [DMLElement("UBYT")] public Byte Command;
            [DMLElement("FLT")] public Single PositionX;
            [DMLElement("FLT")] public Single PositionY;
            [DMLElement("FLT")] public Single PositionZ;
            [DMLElement("UINT")] public UInt32 PackageNumber;
            [DMLElement("UINT")] public UInt32 VersionNumber;
            [DMLElement("UINT")] public UInt32 GIDID;
            [DMLElement("UINT")] public UInt32 TemplateID;
            [DMLElement("UINT")] public UInt32 Time;
            public byte MessageOrder { get; } = 115;
        }
        public sealed class MSG_PATCHHOUSE : INetworkMessage
        {
            [DMLElement("UINT")] public UInt32 DeedTemplateID;
            public byte MessageOrder { get; } = 116;
        }
        public sealed class MSG_PATCHHOUSINGBREADCRUMB : INetworkMessage
        {
            [DMLElement("STR")] public String Data;
            [DMLElement("STR")] public String SubType;
            [DMLElement("UINT")] public UInt32 PackageNumber;
            [DMLElement("UINT")] public UInt32 VersionNumber;
            [DMLElement("UINT")] public UInt32 GIDID;
            public byte MessageOrder { get; } = 117;
        }
        public sealed class MSG_PATCHHOUSINGGARDENINGSHED : INetworkMessage
        {
            [DMLElement("STR")] public String Data;
            [DMLElement("STR")] public String SubType;
            [DMLElement("UINT")] public UInt32 PackageNumber;
            [DMLElement("UINT")] public UInt32 VersionNumber;
            [DMLElement("UINT")] public UInt32 GIDID;
            public byte MessageOrder { get; } = 118;
        }
        public sealed class MSG_PATCHHOUSINGGEARVAULT : INetworkMessage
        {
            [DMLElement("STR")] public String Data;
            [DMLElement("STR")] public String SubType;
            [DMLElement("UINT")] public UInt32 PackageNumber;
            [DMLElement("UINT")] public UInt32 VersionNumber;
            [DMLElement("UINT")] public UInt32 GIDID;
            public byte MessageOrder { get; } = 119;
        }
        public sealed class MSG_PATCHHOUSINGJEWELVAULT : INetworkMessage
        {
            [DMLElement("STR")] public String Data;
            [DMLElement("STR")] public String SubType;
            [DMLElement("UINT")] public UInt32 PackageNumber;
            [DMLElement("UINT")] public UInt32 VersionNumber;
            [DMLElement("UINT")] public UInt32 GIDID;
            public byte MessageOrder { get; } = 120;
        }
        public sealed class MSG_PATCHHOUSINGMUSICOBJECT : INetworkMessage
        {
            [DMLElement("STR")] public String Data;
            [DMLElement("STR")] public String SubType;
            [DMLElement("UINT")] public UInt32 PackageNumber;
            [DMLElement("UINT")] public UInt32 VersionNumber;
            [DMLElement("UINT")] public UInt32 GIDID;
            public byte MessageOrder { get; } = 121;
        }
        public sealed class MSG_PATCHHOUSINGSIGNOBJECT : INetworkMessage
        {
            [DMLElement("STR")] public String Data;
            [DMLElement("STR")] public String SubType;
            [DMLElement("UINT")] public UInt32 PackageNumber;
            [DMLElement("UINT")] public UInt32 VersionNumber;
            [DMLElement("UINT")] public UInt32 GIDID;
            public byte MessageOrder { get; } = 122;
        }
        public sealed class MSG_PATCHHOUSINGTELEPORTEROBJECT : INetworkMessage
        {
            [DMLElement("STR")] public String Data;
            [DMLElement("STR")] public String SubType;
            [DMLElement("UINT")] public UInt32 PackageNumber;
            [DMLElement("UINT")] public UInt32 VersionNumber;
            [DMLElement("UINT")] public UInt32 GIDID;
            public byte MessageOrder { get; } = 123;
        }
        public sealed class MSG_PATCHMONSTERARENA : INetworkMessage
        {
            [DMLElement("STR")] public String Data;
            [DMLElement("STR")] public String SubType;
            [DMLElement("UINT")] public UInt32 PackageNumber;
            [DMLElement("UINT")] public UInt32 VersionNumber;
            [DMLElement("UINT")] public UInt32 GIDID;
            public byte MessageOrder { get; } = 124;
        }
        public sealed class MSG_PATCHMUSICLOOP : INetworkMessage
        {
            [DMLElement("STR")] public String SubType;
            [DMLElement("STR")] public String MusicData;
            [DMLElement("UINT")] public UInt32 PackageNumber;
            [DMLElement("UINT")] public UInt32 VersionNumber;
            [DMLElement("UINT")] public UInt32 GIDID;
            [DMLElement("GID")] public UInt64 ObjectID;
            public byte MessageOrder { get; } = 125;
        }
        public sealed class MSG_PATCHREMOVETEXTUREREMAP : INetworkMessage
        {
            [DMLElement("STR")] public String Data;
            [DMLElement("STR")] public String SubType;
            [DMLElement("UINT")] public UInt32 PackageNumber;
            [DMLElement("UINT")] public UInt32 VersionNumber;
            [DMLElement("UINT")] public UInt32 GIDID;
            [DMLElement("UINT")] public UInt32 RemapIndex;
            [DMLElement("UINT")] public UInt32 TextureType;
            public byte MessageOrder { get; } = 126;
        }
        public sealed class MSG_PATCHTEXTUREREMAP : INetworkMessage
        {
            [DMLElement("STR")] public String Data;
            [DMLElement("STR")] public String SubType;
            [DMLElement("UINT")] public UInt32 PackageNumber;
            [DMLElement("UINT")] public UInt32 VersionNumber;
            [DMLElement("UINT")] public UInt32 GIDID;
            public byte MessageOrder { get; } = 127;
        }
        public sealed class MSG_PATCHTINTHOUSINGOBJECT : INetworkMessage
        {
            [DMLElement("STR")] public String SubType;
            [DMLElement("BYT")] public SByte ColorBits;
            [DMLElement("UINT")] public UInt32 PackageNumber;
            [DMLElement("UINT")] public UInt32 VersionNumber;
            [DMLElement("UINT")] public UInt32 GIDID;
            [DMLElement("GID")] public UInt64 ObjectID;
            public byte MessageOrder { get; } = 128;
        }
        public sealed class MSG_PATCHTREASURECARDPOSTER : INetworkMessage
        {
            [DMLElement("STR")] public String Data;
            [DMLElement("STR")] public String SubType;
            [DMLElement("UINT")] public UInt32 PackageNumber;
            [DMLElement("UINT")] public UInt32 VersionNumber;
            [DMLElement("UINT")] public UInt32 GIDID;
            public byte MessageOrder { get; } = 129;
        }
        public sealed class MSG_PATCHTREASURECARDVAULT : INetworkMessage
        {
            [DMLElement("STR")] public String Data;
            [DMLElement("STR")] public String SubType;
            [DMLElement("UINT")] public UInt32 PackageNumber;
            [DMLElement("UINT")] public UInt32 VersionNumber;
            [DMLElement("UINT")] public UInt32 GIDID;
            public byte MessageOrder { get; } = 130;
        }
        public sealed class MSG_PATCHUPDATEHOUSINGOBJECT : INetworkMessage
        {
            [DMLElement("FLT")] public Single LocX;
            [DMLElement("FLT")] public Single LocY;
            [DMLElement("FLT")] public Single LocZ;
            [DMLElement("FLT")] public Single Yaw;
            [DMLElement("STR")] public String SubType;
            [DMLElement("UINT")] public UInt32 PackageNumber;
            [DMLElement("UINT")] public UInt32 VersionNumber;
            [DMLElement("UINT")] public UInt32 GIDID;
            [DMLElement("GID")] public UInt64 ObjectID;
            [DMLElement("BYT")] public SByte SwitchTemplateID;
            [DMLElement("BYT")] public SByte UseExtendedYaw;
            public byte MessageOrder { get; } = 131;
        }
        public sealed class MSG_PATCHUPEXTENDEDTILE : INetworkMessage
        {
            [DMLElement("STR")] public String SubType;
            [DMLElement("UINT")] public UInt32 PackageNumber;
            [DMLElement("UINT")] public UInt32 VersionNumber;
            [DMLElement("UINT")] public UInt32 GIDID;
            [DMLElement("BYT")] public SByte RemapIndex;
            [DMLElement("BYT")] public SByte IsWallpaper;
            [DMLElement("GID")] public UInt64 ObjectID;
            public byte MessageOrder { get; } = 132;
        }
        public sealed class MSG_PETTOMESCANATTIC : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            public byte MessageOrder { get; } = 133;
        }
        public sealed class MSG_PICKUPALL : INetworkMessage
        {
            [DMLElement("UINT")] public UInt32 ItemCount;
            [DMLElement("BYT")] public SByte ErrorCode;
            [DMLElement("STR")] public String Exceptions;
            public byte MessageOrder { get; } = 134;
        }
        public sealed class MSG_PICKUPHOUSINGTEXTURE : INetworkMessage
        {
            [DMLElement("UINT")] public UInt32 RemapIndex;
            [DMLElement("UINT")] public UInt32 TextureType;
            public byte MessageOrder { get; } = 135;
        }
        public sealed class MSG_PLACEHOUSINGFISH : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 FishTemplateID;
            [DMLElement("FLT")] public Single LocX;
            [DMLElement("FLT")] public Single LocY;
            [DMLElement("FLT")] public Single LocZ;
            [DMLElement("FLT")] public Single Yaw;
            [DMLElement("FLT")] public Single FishSize;
            public byte MessageOrder { get; } = 136;
        }
        public sealed class MSG_PLACEHOUSINGOBJECT : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 ObjectID;
            [DMLElement("FLT")] public Single LocX;
            [DMLElement("FLT")] public Single LocY;
            [DMLElement("FLT")] public Single LocZ;
            [DMLElement("FLT")] public Single Yaw;
            [DMLElement("BYT")] public SByte SwitchCastleBlock;
            public byte MessageOrder { get; } = 137;
        }
        public sealed class MSG_PLAYERTELEPORTINGTOFRIEND : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 TargetCharacterID;
            [DMLElement("GID")] public UInt64 OriginatorID;
            public byte MessageOrder { get; } = 138;
        }
        public sealed class MSG_PLAYINTERACTIVEMUSIC : INetworkMessage
        {
            [DMLElement("UINT")] public UInt32 InstrumentNote;
            public byte MessageOrder { get; } = 139;
        }
        public sealed class MSG_PLAYINTERACTIVEMUSIC2 : INetworkMessage
        {
            [DMLElement("STR")] public String InstrumentNotes;
            public byte MessageOrder { get; } = 140;
        }
        public sealed class MSG_PLAYINTERACTIVEMUSICLOOP : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 PlayerGID;
            [DMLElement("UINT")] public UInt32 TemplateID;
            [DMLElement("BYT")] public SByte LoopIndex;
            [DMLElement("GID")] public UInt64 ObjectGID;
            [DMLElement("STR")] public String TargetPlayers;
            [DMLElement("FLT")] public Single LoopOffset;
            public byte MessageOrder { get; } = 141;
        }
        public sealed class MSG_PLAYINTERACTIVEMUSICLOOPING : INetworkMessage
        {
            [DMLElement("UINT")] public UInt32 InstrumentNote;
            [DMLElement("GID")] public UInt64 ObjectGID;
            [DMLElement("FLT")] public Single LoopOffset;
            public byte MessageOrder { get; } = 142;
        }
        public sealed class MSG_PLAYINTERACTIVEMUSICLOOPING2 : INetworkMessage
        {
            [DMLElement("STR")] public String InstrumentNotes;
            [DMLElement("GID")] public UInt64 ObjectGID;
            [DMLElement("FLT")] public Single LoopOffset;
            public byte MessageOrder { get; } = 143;
        }
        public sealed class MSG_REMOVEFISHFROMAQUARIUM : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("UINT")] public UInt32 FishTemplateID;
            [DMLElement("FLT")] public Single Size;
            public byte MessageOrder { get; } = 144;
        }
        public sealed class MSG_REMOVEHOUSEMUSIC : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 MusicPlayerGID;
            [DMLElement("UINT")] public UInt32 MusicTemplateID;
            public byte MessageOrder { get; } = 145;
        }
        public sealed class MSG_REPORTHOUSE : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 CharacterID;
            [DMLElement("UINT")] public UInt32 DeedTemplateID;
            [DMLElement("WSTR")] public String Message;
            public byte MessageOrder { get; } = 146;
        }
        public sealed class MSG_REQUESTALLFISH : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("STR")] public String FishData;
            public byte MessageOrder { get; } = 147;
        }
        public sealed class MSG_REQUESTATTIC : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            public byte MessageOrder { get; } = 148;
        }
        public sealed class MSG_REQUESTCATCHSUCCESS : INetworkMessage
        {
            [DMLElement("UINT")] public UInt32 SpellTemplateID;
            [DMLElement("UINT")] public UInt32 FishingPassport;
            [DMLElement("UINT")] public UInt32 FishID;
            public byte MessageOrder { get; } = 149;
        }
        public sealed class MSG_REQUESTDEEDZONE : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("INT")] public Int32 Status;
            [DMLElement("INT")] public Int32 Teleport;
            [DMLElement("STR")] public String Arguments;
            public byte MessageOrder { get; } = 150;
        }
        public sealed class MSG_REQUESTFISHHISTORY : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("STR")] public String FishData;
            public byte MessageOrder { get; } = 151;
        }
        public sealed class MSG_REQUESTHOUSEOWNERCHARACTERID : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 CharacterID;
            [DMLElement("UINT")] public UInt32 DeedTemplateID;
            public byte MessageOrder { get; } = 152;
        }
        public sealed class MSG_REQUESTHOUSETRANSFERLIST : INetworkMessage
        {
            [DMLElement("STR")] public String Data;
            public byte MessageOrder { get; } = 153;
        }
        public sealed class MSG_REQUESTHOUSINGZONE : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("INT")] public Int32 Status;
            [DMLElement("GID")] public UInt64 TemplateGID;
            public byte MessageOrder { get; } = 154;
        }
        public sealed class MSG_REQUESTHOUSINGZONETELEPORT : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 TemplateGID;
            [DMLElement("STR")] public String Location;
            public byte MessageOrder { get; } = 155;
        }
        public sealed class MSG_REQUESTINTERACTIVEMUSIC : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 ObjectGID;
            [DMLElement("UINT")] public UInt32 InUse;
            [DMLElement("STR")] public String PlayerName;
            public byte MessageOrder { get; } = 156;
        }
        public sealed class MSG_REQUESTISLANDSWITCH : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("INT")] public Int32 Status;
            public byte MessageOrder { get; } = 157;
        }
        public sealed class MSG_REQUESTSENDAWAY : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 TargetPlayer;
            [DMLElement("UBYT")] public Byte ISCSR;
            public byte MessageOrder { get; } = 158;
        }
        public sealed class MSG_REQUESTTELEPORTERHOUSINGCONFIRM : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            public byte MessageOrder { get; } = 159;
        }
        public sealed class MSG_REQUESTTELEPORTERHOUSINGZONE : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("INT")] public Int32 Status;
            [DMLElement("GID")] public UInt64 TemplateGID;
            [DMLElement("GID")] public UInt64 StructureGID;
            public byte MessageOrder { get; } = 160;
        }
        public sealed class MSG_REQUEST_BLOBS : INetworkMessage
        {
            [DMLElement("STR")] public String Data;
            public byte MessageOrder { get; } = 161;
        }
        public sealed class MSG_RESPEC : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("INT")] public Int32 Points;
            [DMLElement("BYT")] public SByte WebFailure;
            [DMLElement("INT")] public Int32 Credits;
            [DMLElement("BYT")] public SByte LevelIsLow;
            [DMLElement("BYT")] public SByte EncounteredUpgradedTierSpell;
            [DMLElement("INT")] public Int32 Cost;
            [DMLElement("STR")] public String Buffer;
            public byte MessageOrder { get; } = 162;
        }
        public sealed class MSG_SELECTHOUSEMUSIC : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 MusicPlayerGID;
            [DMLElement("UINT")] public UInt32 MusicTemplateID;
            public byte MessageOrder { get; } = 163;
        }
        public sealed class MSG_SELECTMUSICSTYLE : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 MusicPlayerGID;
            [DMLElement("UINT")] public UInt32 MusicStyle;
            public byte MessageOrder { get; } = 164;
        }
        public sealed class MSG_SELLFISHOPEN : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("UINT")] public UInt32 FishTemplateID;
            [DMLElement("UINT")] public UInt32 CatchOfTheDayBonus;
            public byte MessageOrder { get; } = 165;
        }
        public sealed class MSG_SELLFISHREQUEST : INetworkMessage
        {
            [DMLElement("STR")] public String FishData;
            public byte MessageOrder { get; } = 166;
        }
        public sealed class MSG_SENDHOUSINGOBJECTSTATES : INetworkMessage
        {
            [DMLElement("STR")] public String Data;
            public byte MessageOrder { get; } = 167;
        }
        public sealed class MSG_SENDHOUSINGTEXTUREINFO : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 ObjectID;
            [DMLElement("UINT")] public UInt32 RemapIndex;
            public byte MessageOrder { get; } = 168;
        }
        public sealed class MSG_SEND_BLOB : INetworkMessage
        {
            [DMLElement("STR")] public String Data;
            [DMLElement("UINT")] public UInt32 UserData;
            public byte MessageOrder { get; } = 169;
        }
        public sealed class MSG_SETATTICID : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("GID")] public UInt64 AtticID;
            public byte MessageOrder { get; } = 170;
        }
        public sealed class MSG_SETFISHINGPLAYERS : INetworkMessage
        {
            [DMLElement("UINT")] public UInt32 ZoneNameID;
            [DMLElement("STR")] public String Data;
            public byte MessageOrder { get; } = 171;
        }
        public sealed class MSG_SETHOUSESIGN : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 ObjectID;
            [DMLElement("STR")] public String SignText;
            public byte MessageOrder { get; } = 172;
        }
        public sealed class MSG_SETHOUSETELEPORTER : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 ObjectID;
            [DMLElement("FLT")] public Single LocX;
            [DMLElement("FLT")] public Single LocY;
            [DMLElement("FLT")] public Single LocZ;
            [DMLElement("FLT")] public Single Yaw;
            public byte MessageOrder { get; } = 173;
        }
        public sealed class MSG_SETHOUSINGGAMESTATE : INetworkMessage
        {
            [DMLElement("STR")] public String PlayerName;
            [DMLElement("UINT")] public UInt32 GameState;
            [DMLElement("GID")] public UInt64 ObjectGID;
            [DMLElement("STR")] public String Score;
            public byte MessageOrder { get; } = 174;
        }
        public sealed class MSG_SETHOUSINGPALETTE : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 ObjectGID;
            [DMLElement("BYT")] public SByte PrimaryColorIndex;
            public byte MessageOrder { get; } = 175;
        }
        public sealed class MSG_SETINSTANCEFISH : INetworkMessage
        {
            [DMLElement("UINT")] public UInt32 ZoneNameID;
            [DMLElement("STR")] public String Data;
            public byte MessageOrder { get; } = 176;
        }
        public sealed class MSG_SETINVISIBLETOFRIENDS : INetworkMessage
        {
            [DMLElement("UBYT")] public Byte InvisibleToFriends;
            public byte MessageOrder { get; } = 177;
        }
        public sealed class MSG_SETMUSICLOOP : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 ObjectGID;
            [DMLElement("STR")] public String Data;
            public byte MessageOrder { get; } = 178;
        }
        public sealed class MSG_SETTILEWALLPAPER : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 ObjectID;
            [DMLElement("BYT")] public SByte RemapIndex;
            [DMLElement("BYT")] public SByte IsWallpaper;
            public byte MessageOrder { get; } = 179;
        }
        public sealed class MSG_SHOWFISHINGCAST : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 ObjectGID;
            [DMLElement("FLT")] public Single PositionX;
            [DMLElement("FLT")] public Single PositionY;
            [DMLElement("FLT")] public Single PositionZ;
            [DMLElement("FLT")] public Single Yaw;
            [DMLElement("UINT")] public UInt32 SpellTemplateID;
            public byte MessageOrder { get; } = 180;
        }
        public sealed class MSG_STARTHOUSINGGAME : INetworkMessage
        {
            [DMLElement("STR")] public String GameType;
            [DMLElement("UINT")] public UInt32 GameInProgress;
            [DMLElement("STR")] public String Data;
            [DMLElement("BYT")] public SByte IsPublic;
            public byte MessageOrder { get; } = 181;
        }
        public sealed class MSG_STOPINTERACTIVEMUSICLOOP : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 PlayerGID;
            public byte MessageOrder { get; } = 182;
        }
        public sealed class MSG_SWITCHGOTOCOMMONS : INetworkMessage
        {
            public byte MessageOrder { get; } = 183;
        }
        public sealed class MSG_TELEPORTEDTODELETEDLOT : INetworkMessage
        {
            [DMLElement("BYT")] public SByte Quarantined;
            public byte MessageOrder { get; } = 184;
        }
        public sealed class MSG_UPDATEATTICCOUNT : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("INT")] public Int32 ItemCount;
            public byte MessageOrder { get; } = 185;
        }
        public sealed class MSG_UPDATEGARDENINGXP : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("INT")] public Int32 XP;
            [DMLElement("INT")] public Int32 Level;
            [DMLElement("BYT")] public SByte IsPet;
            public byte MessageOrder { get; } = 186;
        }
        public sealed class MSG_UPDATEHOUSINGOBJECT : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 ObjectGID;
            [DMLElement("FLT")] public Single LocX;
            [DMLElement("FLT")] public Single LocY;
            [DMLElement("FLT")] public Single LocZ;
            [DMLElement("FLT")] public Single Yaw;
            [DMLElement("UINT")] public UInt32 SwitchCastleBlock;
            [DMLElement("BYT")] public SByte UseExtendedYaw;
            public byte MessageOrder { get; } = 187;
        }
        public sealed class MSG_UPDATEHOUSINGPET : INetworkMessage
        {
            [DMLElement("STR")] public String Data;
            [DMLElement("GID")] public UInt64 ZoneID;
            public byte MessageOrder { get; } = 188;
        }
        public sealed class MSG_UPDATEISLANDSPACE : INetworkMessage
        {
            [DMLElement("INT")] public Int32 IslandLimit;
            public byte MessageOrder { get; } = 189;
        }
        public sealed class MSG_UPDATEMAXIMUMHOUSINGITEMS : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 ZoneGID;
            [DMLElement("UINT")] public UInt32 NewMaximumItems;
            [DMLElement("UINT")] public UInt32 IncreaseAmount;
            public byte MessageOrder { get; } = 190;
        }
    }
}
