//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Imlight.Internals.DML
{
    using System;
    using Imlight.Engine.DML;
    public sealed class DOODLEDOUG_MESSAGES_41_PROTOCOL : INetworkProtocol
    {
        public byte ServiceID { get; } = 41;
        public string ProtocolType { get; } = "DOODLEDOUG_MESSAGES";
        public Int32 ProtocolVersion { get; } = 1;
        public string ProtocolDescription { get; } = "Messages for all DoodleDoug minigames";
        // == RECORDS ==
        public static INetworkRecord Dispatch(byte id)
        {
            switch (id)
            {
                case (1): return new MSG_DOODLEDOUG_CONNECT();
                case (2): return new MSG_DOODLEDOUG_MOVED();
                case (3): return new MSG_DOODLEDOUG_REWARDS();
                default: throw new InternalException($"No message was found at ID {id} for this protocol!");
            }
        }
        public sealed class MSG_DOODLEDOUG_CONNECT : INetworkRecord
        {
            public byte MessageOrder { get; } = 1;
        }
        public sealed class MSG_DOODLEDOUG_MOVED : INetworkRecord
        {
            public byte MessageOrder { get; } = 2;
        }
        public sealed class MSG_DOODLEDOUG_REWARDS : INetworkRecord
        {
            [DMLElement("INT")] public Int32 score;
            [DMLElement("STR")] public String gameName;
            public byte MessageOrder { get; } = 3;
        }
    }
}
