//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Imlight.Internals.DML
{
    using System;
    public sealed class GAME_5_PROTOCOL : INetworkProtocol
    {
        public byte ServiceID { get; } = 5;
        public string ProtocolType { get; } = "GAME";
        public Int32 ProtocolVersion { get; } = 1;
        public string ProtocolDescription { get; } = "Game Messages";
        // == RECORDS ==
        public static INetworkMessage Dispatch(byte id)
        {
            switch (id)
            {
                case (1): return new MSG_ADCLICKTHROUGH();
                case (2): return new MSG_ADDEFFECT();
                case (3): return new MSG_ADDITEMREQUEST();
                case (4): return new MSG_ADDOBJECT();
                case (5): return new MSG_ADDPARTICLE();
                case (6): return new MSG_ADDZONETIMER();
                case (7): return new MSG_ATTACH();
                case (8): return new MSG_ATTACHFAILED();
                case (9): return new MSG_AUCTIONHOUSEUPDATE();
                case (10): return new MSG_BADGES();
                case (11): return new MSG_BAN_RSP();
                case (12): return new MSG_BESTFRIEND();
                case (13): return new MSG_BLACKBALL();
                case (14): return new MSG_BUDDYDROP();
                case (15): return new MSG_BUDDYENTRY();
                case (16): return new MSG_BUDDYLISTCOMPLETE();
                case (17): return new MSG_BUDDYREQUESTACCEPT();
                case (18): return new MSG_BUDDYREQUESTACCEPTFWD();
                case (19): return new MSG_BUDDYREQUESTADD();
                case (20): return new MSG_BUDDYREQUESTADDFWD();
                case (21): return new MSG_BUDDYREQUESTDENY();
                case (22): return new MSG_BUDDYREQUESTDENYFWD();
                case (23): return new MSG_BUDDYREQUESTDROP();
                case (24): return new MSG_BUDDYREQUESTERROR();
                case (25): return new MSG_BUDDYREQUESTLIST();
                case (26): return new MSG_BUDDYSTATS();
                case (27): return new MSG_BUDDYSTATUSUPDATE();
                case (28): return new MSG_BUGREPORT();
                case (29): return new MSG_BUGSUBMITRESPONSE();
                case (30): return new MSG_CHANNELCHAT();
                case (31): return new MSG_CHANNELSUBSCRIPTION();
                case (32): return new MSG_CHATDIAGNOSTICS();
                case (33): return new MSG_CHATERROR();
                case (34): return new MSG_CHECKSUBSCRIPTION();
                case (35): return new MSG_CHECK_MAIL();
                case (36): return new MSG_CLIENTMOVE();
                case (37): return new MSG_CLIENTMOVESTATE();
                case (38): return new MSG_CLIENTNOTIFYTEXT();
                case (39): return new MSG_CLIENTTUTORIALEVENT();
                case (40): return new MSG_CLIENT_DISCONNECT();
                case (41): return new MSG_CLIENT_ERROR();
                case (42): return new MSG_CLIENT_PROCESS_TERMINATED();
                case (43): return new MSG_COMBINEINVENTORYITEMS();
                case (44): return new MSG_COMMAND();
                case (45): return new MSG_COMMANDRESULT();
                case (46): return new MSG_COMPANIONEFFECTS();
                case (47): return new MSG_CORE_EMOTE();
                case (48): return new MSG_CREATECHANNELRESPONSE();
                case (49): return new MSG_CREATE_SESSION();
                case (50): return new MSG_CSRBANKITEMS();
                case (51): return new MSG_CSRBANKITEMSDONE();
                case (52): return new MSG_CSREDITCHARACTER();
                case (53): return new MSG_CSREDITCHARACTERFAILED();
                case (54): return new MSG_CSRFINISHEDHOUSE();
                case (55): return new MSG_CSRSEARCHLIST();
                case (56): return new MSG_CSR_MAIL_DATA();
                case (57): return new MSG_CSR_RECEIVE_GIFTS();
                case (58): return new MSG_DEBUGDELETEALLOBJECTS();
                case (59): return new MSG_DELETEOBJECT();
                case (60): return new MSG_DELETE_GIFT();
                case (61): return new MSG_DIRECTEDCHAT();
                case (62): return new MSG_DIRECTEDCHATBYNAMERESPONSE();
                case (63): return new MSG_DIRECTEDCHATFAIL();
                case (64): return new MSG_DIRECTEDQUICKCHAT();
                case (65): return new MSG_DIRECTEDQUICKCHATEXT();
                case (66): return new MSG_DISCONNECT_AFK();
                case (67): return new MSG_DOWNLOADBROWSER();
                case (68): return new MSG_DOWNLOADPACKAGE();
                case (69): return new MSG_DOWNLOADPACKAGEELEMENT();
                case (70): return new MSG_DYNAMODBEHAVIOR_UPDATEMODS();
                case (71): return new MSG_DYNAMODDUMP();
                case (72): return new MSG_ENTERSTATE();
                case (73): return new MSG_EQUIPITEM();
                case (74): return new MSG_EQUIPMENTBEHAVIOR_EQUIPITEM();
                case (75): return new MSG_EQUIPMENTBEHAVIOR_PUBLICEQUIPITEM();
                case (76): return new MSG_EQUIPMENTBEHAVIOR_PUBLICUNEQUIPITEM();
                case (77): return new MSG_EQUIPMENTBEHAVIOR_UNEQUIPITEM();
                case (78): return new MSG_FEEDINVENTORYITEM();
                case (79): return new MSG_FIND_SESSIONS();
                case (80): return new MSG_FIND_SESSION_PLAYERS();
                case (81): return new MSG_GENERICGAME();
                case (82): return new MSG_GETLADDER();
                case (83): return new MSG_GET_RANKINGS();
                case (84): return new MSG_GIFT_REDEEMED();
                case (85): return new MSG_GOTOPLAYER();
                case (86): return new MSG_GOTOPLAYERRESP();
                case (87): return new MSG_HARASSMENTREPORT();
                case (88): return new MSG_IGNOREADD();
                case (89): return new MSG_IGNOREDROP();
                case (90): return new MSG_IGNORELIST();
                case (91): return new MSG_INTERACTOBJECT();
                case (92): return new MSG_INTERACTOPTION();
                case (93): return new MSG_INVENTORYBEHAVIOR_ADDITEM();
                case (94): return new MSG_INVENTORYBEHAVIOR_REMOVEITEM();
                case (95): return new MSG_INVENTORYBEHAVIOR_TRADEITEM();
                case (96): return new MSG_INVITEFRIEND();
                case (97): return new MSG_INVITE_RESPONSE();
                case (98): return new MSG_JOINCHANNELRESPONSE();
                case (99): return new MSG_JOIN_SESSION();
                case (100): return new MSG_JUMP();
                case (101): return new MSG_KILL_CLIENT_PROCESS();
                case (102): return new MSG_LADDER();
                case (103): return new MSG_LEAVECHANNELRESPONSE();
                case (104): return new MSG_LEAVEHOUSINGLOT();
                case (105): return new MSG_LEAVESERVICERANGE();
                case (106): return new MSG_LEAVESTATE();
                case (107): return new MSG_LOADSAVEOBJECTS();
                case (108): return new MSG_LOGINCOMPLETE();
                case (109): return new MSG_MAIL_DATA();
                case (110): return new MSG_MARK_LOCATION();
                case (111): return new MSG_MARK_LOCATION_RESPONSE();
                case (112): return new MSG_MATCHAWARD();
                case (113): return new MSG_MATCHINVITE();
                case (114): return new MSG_MATCHMAKERUPDATE();
                case (115): return new MSG_MATCHREADY();
                case (116): return new MSG_MATCHRESULT();
                case (117): return new MSG_MESSAGE_PROCESS();
                case (118): return new MSG_MOVECORRECTION();
                case (119): return new MSG_MOVESTATE();
                case (120): return new MSG_MUTE();
                case (121): return new MSG_MUTE_RSP();
                case (122): return new MSG_NEWOBJECT();
                case (123): return new MSG_NEWSYSSTATS();
                case (124): return new MSG_NEWTICKCNT();
                case (125): return new MSG_NEWTOURNEYREWARDS();
                case (126): return new MSG_NEW_MAIL();
                case (127): return new MSG_NOTIFYCHANNELINSTANCE();
                case (128): return new MSG_NOTIFY_GIFT();
                case (129): return new MSG_NOTMUTED();
                case (130): return new MSG_NOT_AFK();
                case (131): return new MSG_NPCSPEECH();
                case (132): return new MSG_OBJECT_INFO_QUERY();
                case (133): return new MSG_PARTYDISBAND();
                case (134): return new MSG_PARTYJOINFAILED();
                case (135): return new MSG_PARTYJOINNOTIFICATION();
                case (136): return new MSG_PARTYLEAVE();
                case (137): return new MSG_PARTYLEAVENOTIFICATION();
                case (138): return new MSG_PARTYLEVELUP();
                case (139): return new MSG_PARTYLEVELUPUPDATE();
                case (140): return new MSG_PARTYMULTIPLAYERMOUNTEQUIP();
                case (141): return new MSG_PARTYMULTIPLAYERMOUNTEQUIPUPDATE();
                case (142): return new MSG_PARTYMULTIPLAYERMOUNTJOIN();
                case (143): return new MSG_PARTYMULTIPLAYERMOUNTJOINUPDATE();
                case (144): return new MSG_PARTYREQUESTACCEPT();
                case (145): return new MSG_PARTYREQUESTDECLINE();
                case (146): return new MSG_PARTYREQUESTINVITE();
                case (147): return new MSG_PARTYREQUESTJOIN();
                case (148): return new MSG_PARTYREQUESTMEMBERZONES();
                case (149): return new MSG_PARTYREQUESTRESPONSE();
                case (150): return new MSG_PARTYREQUESTTIMEOUT();
                case (151): return new MSG_PARTYSUBMITMEMBERZONES();
                case (152): return new MSG_PARTYUPDATE();
                case (153): return new MSG_PARTYZONEREQUEST();
                case (154): return new MSG_PARTYZONEREQUESTRESPONSE();
                case (155): return new MSG_PICKUPOBJECT();
                case (156): return new MSG_PLACEOBJECT();
                case (157): return new MSG_PLAYCINEMATIC();
                case (158): return new MSG_PLAYERBLACKBALLEDALERT();
                case (159): return new MSG_PLAYERREADYACK();
                case (160): return new MSG_PLAYSOUND();
                case (161): return new MSG_POSTZONEEVENTFROMCLIENT();
                case (162): return new MSG_PREVIEW_ISLAND();
                case (163): return new MSG_PVPUPDATEINFO();
                case (164): return new MSG_QUERY_LOGOUT();
                case (165): return new MSG_RADIALCHAT();
                case (166): return new MSG_RADIALQUICKCHAT();
                case (167): return new MSG_RADIALQUICKCHATEXT();
                case (168): return new MSG_RADIALZONECLUSTERQUICKCHAT();
                case (169): return new MSG_RANKING();
                case (170): return new MSG_REALM_INFO_QUERY();
                case (171): return new MSG_RECALL_LOCATION();
                case (172): return new MSG_RECEIVE_GIFTS();
                case (173): return new MSG_RECEIVE_PROMOTIONS();
                case (174): return new MSG_REDEEM_GIFT();
                case (175): return new MSG_REDEEM_MAIL_GIFT();
                case (176): return new MSG_REDEEM_MAIL_GIFT_RESPONSE();
                case (177): return new MSG_RELEASEDELAY();
                case (178): return new MSG_RELOADTEMPLATEDIR();
                case (179): return new MSG_REMOVEDSHOPPER();
                case (180): return new MSG_REMOVEEFFECT();
                case (181): return new MSG_REMOVEITEMREQUEST();
                case (182): return new MSG_REMOVEOBJECT();
                case (183): return new MSG_REMOVEPARTICLE();
                case (184): return new MSG_REMOVEZONETIMER();
                case (185): return new MSG_REPORTADTAKEOVER();
                case (186): return new MSG_REQASKSERVER();
                case (187): return new MSG_REQCHATDIAGNOSTICS();
                case (188): return new MSG_REQUESTADVANCECHANNELINSTANCE();
                case (189): return new MSG_REQUESTCHATCODE();
                case (190): return new MSG_REQUESTCREATECHANNEL();
                case (191): return new MSG_REQUESTDIRECTEDCHAT();
                case (192): return new MSG_REQUESTDIRECTEDCHATBYNAME();
                case (193): return new MSG_REQUESTDIRECTEDQUICKCHAT();
                case (194): return new MSG_REQUESTDIRECTEDQUICKCHATEXT();
                case (195): return new MSG_REQUESTJOINCHANNEL();
                case (196): return new MSG_REQUESTJOINCHANNELBYNAME();
                case (197): return new MSG_REQUESTLEAVECHANNEL();
                case (198): return new MSG_REQUESTLEAVECHANNELBYNAME();
                case (199): return new MSG_REQUESTMAXFRIENDS();
                case (200): return new MSG_REQUESTRADIALCHAT();
                case (201): return new MSG_REQUESTRADIALFRIENDCHAT();
                case (202): return new MSG_REQUESTRADIALFRIENDQUICKCHAT();
                case (203): return new MSG_REQUESTRADIALOWNERCHAT();
                case (204): return new MSG_REQUESTRADIALQUICKCHAT();
                case (205): return new MSG_REQUESTRADIALQUICKCHATEXT();
                case (206): return new MSG_REQUESTSESSION();
                case (207): return new MSG_REQUESTZONECLUSTERQUICKCHAT();
                case (208): return new MSG_REQUEST_GIFTS();
                case (209): return new MSG_REQUEST_PROMOTIONS();
                case (210): return new MSG_RESTORECHAR_RSP();
                case (211): return new MSG_RETRIEVE_MAIL();
                case (212): return new MSG_RETRYTELEPORT();
                case (213): return new MSG_SCRIPT();
                case (214): return new MSG_SELECT_BADGE();
                case (215): return new MSG_SENDCHATCODE();
                case (216): return new MSG_SENDINTERACTOPTIONS();
                case (217): return new MSG_SENDTEXT();
                case (218): return new MSG_SERVERMOVE();
                case (219): return new MSG_SERVERSHUTDOWN();
                case (220): return new MSG_SERVERTELEPORT();
                case (221): return new MSG_SERVERTRANSFER();
                case (222): return new MSG_SERVERTUTORIALCOMMAND();
                case (223): return new MSG_SERVER_ERROR();
                case (224): return new MSG_SERVER_PROCESS_RUNNING();
                case (225): return new MSG_SESSION();
                case (226): return new MSG_SESSION_ERROR();
                case (227): return new MSG_SESSION_PLAYER();
                case (228): return new MSG_SETHOUSECUSTOMIZATION();
                case (229): return new MSG_SPLITQUANTITY();
                case (230): return new MSG_STARTSTAGEDCINEMATIC();
                case (231): return new MSG_START_CLIENT_PROCESS();
                case (232): return new MSG_START_SERVER_PROCESS();
                case (233): return new MSG_SUBOPTIMAL_BRACKET_RESPONSE();
                case (234): return new MSG_TELEPORT_TO_GAME_ZONE();
                case (235): return new MSG_TOURNAMENTUPDATE();
                case (236): return new MSG_TRANSFERCHAR_RSP();
                case (237): return new MSG_TRANSFER_INSTANCE();
                case (238): return new MSG_TRANSFER_REALMS();
                case (239): return new MSG_TRASHINVENTORYITEM();
                case (240): return new MSG_TUTORIALS();
                case (241): return new MSG_UPDATEOBJECT();
                case (242): return new MSG_UPDATEQUANTITY();
                case (243): return new MSG_UPDATEZONECOUNTER();
                case (244): return new MSG_UPDATEZONETIMER();
                case (245): return new MSG_USECHATCODE();
                case (246): return new MSG_VIEWACCOUNT();
                case (247): return new MSG_WIZBANG();
                case (248): return new MSG_ZOMBIE_PLAYER();
                case (249): return new MSG_ZONEEVENTTIMEREXPIRED();
                case (250): return new MSG_ZONETRANSFER();
                case (251): return new MSG_ZONETRANSFERACK();
                case (252): return new MSG_ZONETRANSFERNACK();
                case (253): return new MSG_ZONETRANSFERREQUEST();
                default: throw new InternalException($"No message was found at ID {id} for this protocol!");
            }
        }
        public sealed class MSG_ADCLICKTHROUGH : INetworkMessage
        {
            [DMLElement("STR")] public String Partner;
            [DMLElement("STR")] public String URL;
            public byte MessageOrder { get; } = 1;
        }
        public sealed class MSG_ADDEFFECT : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GameObjectID;
            [DMLElement("STR")] public String EffectData;
            public byte MessageOrder { get; } = 2;
        }
        public sealed class MSG_ADDITEMREQUEST : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("GID")] public UInt64 ItemTemplateID;
            [DMLElement("INT")] public Int32 Quantity;
            public byte MessageOrder { get; } = 3;
        }
        public sealed class MSG_ADDOBJECT : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GameObjectID;
            [DMLElement("FLT")] public Single LocationX;
            [DMLElement("FLT")] public Single LocationY;
            [DMLElement("FLT")] public Single LocationZ;
            [DMLElement("FLT")] public Single Direction;
            [DMLElement("STR")] public String Name;
            [DMLElement("GID")] public UInt64 TemplateID;
            public byte MessageOrder { get; } = 4;
        }
        public sealed class MSG_ADDPARTICLE : INetworkMessage
        {
            [DMLElement("STR")] public String asset;
            [DMLElement("STR")] public String newName;
            [DMLElement("STR")] public String attachTo;
            [DMLElement("UBYT")] public Byte loop;
            [DMLElement("STR")] public String floatText;
            [DMLElement("STR")] public String chatText;
            [DMLElement("STR")] public String chatArgs;
            [DMLElement("STR")] public String sound;
            [DMLElement("GID")] public UInt64 parentID;
            public byte MessageOrder { get; } = 5;
        }
        public sealed class MSG_ADDZONETIMER : INetworkMessage
        {
            [DMLElement("INT")] public Int32 TimerID;
            [DMLElement("STR")] public String Title;
            [DMLElement("STR")] public String TimerUI;
            [DMLElement("FLT")] public Single CountdownTime;
            public byte MessageOrder { get; } = 6;
        }
        public sealed class MSG_ATTACH : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GameObjectID;
            [DMLElement("STR")] public String LoginKey;
            [DMLElement("GID")] public UInt64 UserID;
            [DMLElement("GID")] public UInt64 CharID;
            [DMLElement("STR")] public String ZoneName;
            [DMLElement("STR")] public String Location;
            [DMLElement("GID")] public UInt64 TargetPlayerID;
            [DMLElement("GID")] public UInt64 ZoneID;
            [DMLElement("INT")] public Int32 Slot;
            [DMLElement("GID")] public UInt64 SessionID;
            [DMLElement("INT")] public Int32 SessionSlot;
            [DMLElement("STR")] public String PassKey;
            [DMLElement("UBYT")] public Byte Reattach;
            [DMLElement("UBYT")] public Byte Retry;
            [DMLElement("STR")] public String Locale;
            public byte MessageOrder { get; } = 7;
        }
        public sealed class MSG_ATTACHFAILED : INetworkMessage
        {
            [DMLElement("UINT")] public UInt32 Error;
            [DMLElement("UINT")] public UInt32 Rejected;
            [DMLElement("UINT")] public UInt32 NoDisconnect;
            public byte MessageOrder { get; } = 8;
        }
        public sealed class MSG_AUCTIONHOUSEUPDATE : INetworkMessage
        {
            [DMLElement("STR")] public String UpdateInfo;
            [DMLElement("GID")] public UInt64 CharacterID;
            public byte MessageOrder { get; } = 9;
        }
        public sealed class MSG_BADGES : INetworkMessage
        {
            [DMLElement("UINT")] public UInt32 CurrentBadge;
            [DMLElement("BYT")] public SByte UpdateAll;
            [DMLElement("UINT")] public UInt32 TotalBadges;
            [DMLElement("BYT")] public SByte Add;
            [DMLElement("BYT")] public SByte Remove;
            [DMLElement("STR")] public String BadgeName;
            [DMLElement("STR")] public String BadgeInfo;
            [DMLElement("UINT")] public UInt32 BadgeNameID;
            [DMLElement("STR")] public String BadgeFilterInfo;
            public byte MessageOrder { get; } = 10;
        }
        public sealed class MSG_BAN_RSP : INetworkMessage
        {
            [DMLElement("STR")] public String BannedID;
            [DMLElement("STR")] public String BanTime;
            [DMLElement("STR")] public String BanType;
            [DMLElement("UBYT")] public Byte Success;
            public byte MessageOrder { get; } = 11;
        }
        public sealed class MSG_BESTFRIEND : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 ListOwnerGID;
            [DMLElement("GID")] public UInt64 BuddyID;
            [DMLElement("UBYT")] public Byte Forwarded;
            [DMLElement("UBYT")] public Byte FriendSymbol;
            public byte MessageOrder { get; } = 12;
        }
        public sealed class MSG_BLACKBALL : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 TargetObjID;
            [DMLElement("WSTR")] public String HarassmentType;
            [DMLElement("WSTR")] public String ChatLog;
            [DMLElement("BYT")] public SByte IsMute;
            public byte MessageOrder { get; } = 13;
        }
        public sealed class MSG_BUDDYDROP : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 ListOwnerGID;
            [DMLElement("GID")] public UInt64 EntryGID;
            public byte MessageOrder { get; } = 14;
        }
        public sealed class MSG_BUDDYENTRY : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 ListOwnerGID;
            [DMLElement("GID")] public UInt64 EntryGID;
            [DMLElement("GID")] public UInt64 GameObjectID;
            [DMLElement("STR")] public String Name;
            [DMLElement("UBYT")] public Byte Status;
            [DMLElement("UINT")] public UInt32 FriendInfo;
            [DMLElement("UBYT")] public Byte PasswordChat;
            [DMLElement("UINT")] public UInt32 Permissions;
            [DMLElement("STR")] public String ZoneName;
            [DMLElement("STR")] public String RealmName;
            [DMLElement("UINT")] public UInt32 Locale;
            [DMLElement("UINT")] public UInt32 FriendDate;
            [DMLElement("UINT")] public UInt32 FriendStatusDate;
            public byte MessageOrder { get; } = 15;
        }
        public sealed class MSG_BUDDYLISTCOMPLETE : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 ListOwnerGID;
            public byte MessageOrder { get; } = 16;
        }
        public sealed class MSG_BUDDYREQUESTACCEPT : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 ListOwnerGID;
            [DMLElement("GID")] public UInt64 EntryGID;
            [DMLElement("STR")] public String OwnerName;
            [DMLElement("STR")] public String EntryName;
            [DMLElement("GID")] public UInt64 SourceObjectID;
            [DMLElement("GID")] public UInt64 DestObjectID;
            [DMLElement("UINT")] public UInt32 Error;
            [DMLElement("UINT")] public UInt32 Permissions;
            [DMLElement("UBYT")] public Byte Forwarded;
            [DMLElement("UINT")] public UInt32 EntryLocale;
            [DMLElement("UINT")] public UInt32 FriendInfo;
            [DMLElement("UINT")] public UInt32 FriendDate;
            [DMLElement("UINT")] public UInt32 FriendStatusDate;
            public byte MessageOrder { get; } = 17;
        }
        public sealed class MSG_BUDDYREQUESTACCEPTFWD : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 ListOwnerGID;
            [DMLElement("GID")] public UInt64 EntryGID;
            [DMLElement("STR")] public String OwnerName;
            [DMLElement("STR")] public String EntryName;
            [DMLElement("GID")] public UInt64 SourceObjectID;
            [DMLElement("GID")] public UInt64 DestObjectID;
            [DMLElement("UINT")] public UInt32 Permissions;
            [DMLElement("UINT")] public UInt32 EntryLocale;
            [DMLElement("UINT")] public UInt32 FriendInfo;
            [DMLElement("UINT")] public UInt32 FriendDate;
            [DMLElement("UINT")] public UInt32 FriendStatusDate;
            public byte MessageOrder { get; } = 18;
        }
        public sealed class MSG_BUDDYREQUESTADD : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 ListOwnerGID;
            [DMLElement("GID")] public UInt64 EntryGID;
            [DMLElement("STR")] public String OwnerName;
            [DMLElement("UBYT")] public Byte OwnerLevel;
            [DMLElement("STR")] public String OwnerSchool;
            [DMLElement("UBYT")] public Byte Remove;
            public byte MessageOrder { get; } = 19;
        }
        public sealed class MSG_BUDDYREQUESTADDFWD : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 ListOwnerGID;
            [DMLElement("GID")] public UInt64 EntryGID;
            [DMLElement("STR")] public String OwnerName;
            [DMLElement("UBYT")] public Byte OwnerLevel;
            [DMLElement("STR")] public String OwnerSchool;
            [DMLElement("UBYT")] public Byte Remove;
            public byte MessageOrder { get; } = 20;
        }
        public sealed class MSG_BUDDYREQUESTDENY : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 ListOwnerGID;
            [DMLElement("GID")] public UInt64 EntryGID;
            public byte MessageOrder { get; } = 21;
        }
        public sealed class MSG_BUDDYREQUESTDENYFWD : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 ListOwnerGID;
            [DMLElement("GID")] public UInt64 EntryGID;
            public byte MessageOrder { get; } = 22;
        }
        public sealed class MSG_BUDDYREQUESTDROP : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 ListOwnerGID;
            [DMLElement("GID")] public UInt64 EntryGID;
            [DMLElement("UBYT")] public Byte Forwarded;
            public byte MessageOrder { get; } = 23;
        }
        public sealed class MSG_BUDDYREQUESTERROR : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 ListOwnerGID;
            [DMLElement("GID")] public UInt64 EntryGID;
            [DMLElement("UBYT")] public Byte Error;
            public byte MessageOrder { get; } = 24;
        }
        public sealed class MSG_BUDDYREQUESTLIST : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 ListOwnerGID;
            [DMLElement("UBYT")] public Byte Forwarded;
            public byte MessageOrder { get; } = 25;
        }
        public sealed class MSG_BUDDYSTATS : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 BuddyID;
            [DMLElement("STR")] public String StatBlock;
            [DMLElement("STR")] public String PetStatBlock;
            [DMLElement("STR")] public String CharBlock;
            [DMLElement("STR")] public String EquipBlock;
            [DMLElement("STR")] public String EffectBlock;
            [DMLElement("UINT")] public UInt32 Level;
            [DMLElement("UINT")] public UInt32 School;
            [DMLElement("BYT")] public SByte Gender;
            [DMLElement("UINT")] public UInt32 StatBlockCRC;
            [DMLElement("UINT")] public UInt32 PetStatBlockCRC;
            [DMLElement("UINT")] public UInt32 CharBlockCRC;
            [DMLElement("UINT")] public UInt32 EquipBlockCRC;
            [DMLElement("UINT")] public UInt32 EffectBlockCRC;
            [DMLElement("GID")] public UInt64 SourceCharacterGID;
            [DMLElement("GID")] public UInt64 TargetCharacterGID;
            [DMLElement("UINT")] public UInt32 PetJewelID;
            public byte MessageOrder { get; } = 26;
        }
        public sealed class MSG_BUDDYSTATUSUPDATE : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 ListOwnerGID;
            [DMLElement("GID")] public UInt64 EntryGID;
            [DMLElement("UBYT")] public Byte Status;
            [DMLElement("UINT")] public UInt32 Permissions;
            [DMLElement("STR")] public String ZoneName;
            [DMLElement("UINT")] public UInt32 Locale;
            [DMLElement("STR")] public String RealmName;
            [DMLElement("UINT")] public UInt32 FriendInfo;
            [DMLElement("UINT")] public UInt32 FriendDate;
            [DMLElement("UINT")] public UInt32 FriendStatusDate;
            public byte MessageOrder { get; } = 27;
        }
        public sealed class MSG_BUGREPORT : INetworkMessage
        {
            [DMLElement("STR")] public String Report;
            public byte MessageOrder { get; } = 28;
        }
        public sealed class MSG_BUGSUBMITRESPONSE : INetworkMessage
        {
            [DMLElement("BYT")] public SByte Success;
            [DMLElement("BYT")] public SByte Type;
            public byte MessageOrder { get; } = 29;
        }
        public sealed class MSG_CHANNELCHAT : INetworkMessage
        {
            [DMLElement("STR")] public String SourceName;
            [DMLElement("GID")] public UInt64 SourceID;
            [DMLElement("WSTR")] public String Message;
            [DMLElement("GID")] public UInt64 TargetID;
            [DMLElement("UBYT")] public Byte Filter;
            [DMLElement("UINT")] public UInt32 Flags;
            public byte MessageOrder { get; } = 30;
        }
        public sealed class MSG_CHANNELSUBSCRIPTION : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 RecipientID;
            [DMLElement("GID")] public UInt64 ChannelID;
            [DMLElement("GID")] public UInt64 ParentID;
            [DMLElement("WSTR")] public String ChannelName;
            [DMLElement("UBYT")] public Byte ChannelType;
            public byte MessageOrder { get; } = 31;
        }
        public sealed class MSG_CHATDIAGNOSTICS : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 CharacterID;
            [DMLElement("STR")] public String Data;
            public byte MessageOrder { get; } = 32;
        }
        public sealed class MSG_CHATERROR : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 ListOwnerGID;
            [DMLElement("GID")] public UInt64 CharacterID;
            [DMLElement("UINT")] public UInt32 Error;
            public byte MessageOrder { get; } = 33;
        }
        public sealed class MSG_CHECKSUBSCRIPTION : INetworkMessage
        {
            [DMLElement("UBYT")] public Byte Success;
            public byte MessageOrder { get; } = 34;
        }
        public sealed class MSG_CHECK_MAIL : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 CharacterID;
            public byte MessageOrder { get; } = 35;
        }
        public sealed class MSG_CLIENTMOVE : INetworkMessage
        {
            [DMLElement("USHRT")] public UInt16 LocationX;
            [DMLElement("USHRT")] public UInt16 LocationY;
            [DMLElement("USHRT")] public UInt16 LocationZ;
            [DMLElement("UBYT")] public Byte Direction;
            [DMLElement("UBYT")] public Byte ZoneCounter;
            public byte MessageOrder { get; } = 36;
        }
        public sealed class MSG_CLIENTMOVESTATE : INetworkMessage
        {
            [DMLElement("BYT")] public SByte NewState;
            public byte MessageOrder { get; } = 37;
        }
        public sealed class MSG_CLIENTNOTIFYTEXT : INetworkMessage
        {
            [DMLElement("STR")] public String NotifyText;
            [DMLElement("INT")] public Int32 Type;
            [DMLElement("STR")] public String Madlibs;
            public byte MessageOrder { get; } = 38;
        }
        public sealed class MSG_CLIENTTUTORIALEVENT : INetworkMessage
        {
            [DMLElement("STR")] public String Event;
            public byte MessageOrder { get; } = 39;
        }
        public sealed class MSG_CLIENT_DISCONNECT : INetworkMessage
        {
            public byte MessageOrder { get; } = 40;
        }
        public sealed class MSG_CLIENT_ERROR : INetworkMessage
        {
            [DMLElement("STR")] public String Function;
            public byte MessageOrder { get; } = 41;
        }
        public sealed class MSG_CLIENT_PROCESS_TERMINATED : INetworkMessage
        {
            [DMLElement("UINT")] public UInt32 JobID;
            public byte MessageOrder { get; } = 42;
        }
        public sealed class MSG_COMBINEINVENTORYITEMS : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("GID")] public UInt64 ItemID1;
            [DMLElement("GID")] public UInt64 ItemID2;
            public byte MessageOrder { get; } = 43;
        }
        public sealed class MSG_COMMAND : INetworkMessage
        {
            [DMLElement("WSTR")] public String Command;
            [DMLElement("STR")] public String ResultEvent;
            public byte MessageOrder { get; } = 44;
        }
        public sealed class MSG_COMMANDRESULT : INetworkMessage
        {
            [DMLElement("WSTR")] public String Command;
            [DMLElement("STR")] public String ResultEvent;
            [DMLElement("WSTR")] public String Results;
            public byte MessageOrder { get; } = 45;
        }
        public sealed class MSG_COMPANIONEFFECTS : INetworkMessage
        {
            [DMLElement("UINT")] public UInt32 NPC;
            [DMLElement("STR")] public String EffectInfoList;
            [DMLElement("UBYT")] public Byte Add;
            public byte MessageOrder { get; } = 46;
        }
        public sealed class MSG_CORE_EMOTE : INetworkMessage
        {
            [DMLElement("STR")] public String Name;
            [DMLElement("UBYT")] public Byte ExcludeOriginator;
            [DMLElement("UINT")] public UInt32 PhraseID;
            public byte MessageOrder { get; } = 47;
        }
        public sealed class MSG_CREATECHANNELRESPONSE : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 SourceID;
            [DMLElement("GID")] public UInt64 ChannelID;
            [DMLElement("STR")] public String ChannelName;
            [DMLElement("UBYT")] public Byte ErrorCode;
            public byte MessageOrder { get; } = 48;
        }
        public sealed class MSG_CREATE_SESSION : INetworkMessage
        {
            public byte MessageOrder { get; } = 49;
        }
        public sealed class MSG_CSRBANKITEMS : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("UBYT")] public Byte SharedBank;
            [DMLElement("STR")] public String SerializedItem;
            public byte MessageOrder { get; } = 50;
        }
        public sealed class MSG_CSRBANKITEMSDONE : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("UBYT")] public Byte SharedBank;
            [DMLElement("INT")] public Int32 Limit;
            public byte MessageOrder { get; } = 51;
        }
        public sealed class MSG_CSREDITCHARACTER : INetworkMessage
        {
            [DMLElement("UINT")] public UInt32 ChunkNum;
            [DMLElement("GID")] public UInt64 CharacterID;
            [DMLElement("GID")] public UInt64 UserID;
            [DMLElement("STR")] public String UserName;
            [DMLElement("STR")] public String CurrentBan;
            [DMLElement("STR")] public String CurrentMute;
            [DMLElement("UBYT")] public Byte AcctAssoc;
            [DMLElement("STR")] public String Object;
            [DMLElement("STR")] public String CurrentQuests;
            [DMLElement("STR")] public String Registry;
            [DMLElement("STR")] public String AccessPasses;
            [DMLElement("STR")] public String BadgeList;
            [DMLElement("UBYT")] public Byte Edit;
            [DMLElement("UBYT")] public Byte AllowedToReport;
            [DMLElement("STR")] public String DynaMods;
            [DMLElement("INT")] public Int32 CharacterSlots;
            public byte MessageOrder { get; } = 52;
        }
        public sealed class MSG_CSREDITCHARACTERFAILED : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 CharacterID;
            public byte MessageOrder { get; } = 53;
        }
        public sealed class MSG_CSRFINISHEDHOUSE : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 OldGid;
            [DMLElement("GID")] public UInt64 NewGid;
            [DMLElement("GID")] public UInt64 Character;
            [DMLElement("UBYT")] public Byte Error;
            public byte MessageOrder { get; } = 54;
        }
        public sealed class MSG_CSRSEARCHLIST : INetworkMessage
        {
            [DMLElement("UBYT")] public Byte StartEnd;
            [DMLElement("STR")] public String Data;
            public byte MessageOrder { get; } = 55;
        }
        public sealed class MSG_CSR_MAIL_DATA : INetworkMessage
        {
            [DMLElement("STR")] public String Data;
            public byte MessageOrder { get; } = 56;
        }
        public sealed class MSG_CSR_RECEIVE_GIFTS : INetworkMessage
        {
            [DMLElement("INT")] public Int32 Success;
            [DMLElement("STR")] public String Data;
            public byte MessageOrder { get; } = 57;
        }
        public sealed class MSG_DEBUGDELETEALLOBJECTS : INetworkMessage
        {
            public byte MessageOrder { get; } = 58;
        }
        public sealed class MSG_DELETEOBJECT : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GameObjectID;
            [DMLElement("STR")] public String Data;
            public byte MessageOrder { get; } = 59;
        }
        public sealed class MSG_DELETE_GIFT : INetworkMessage
        {
            [DMLElement("STR")] public String GiftID;
            [DMLElement("INT")] public Int32 Success;
            public byte MessageOrder { get; } = 60;
        }
        public sealed class MSG_DIRECTEDCHAT : INetworkMessage
        {
            [DMLElement("STR")] public String SourceName;
            [DMLElement("GID")] public UInt64 SourceID;
            [DMLElement("WSTR")] public String Message;
            [DMLElement("GID")] public UInt64 TargetID;
            [DMLElement("UBYT")] public Byte Filter;
            public byte MessageOrder { get; } = 61;
        }
        public sealed class MSG_DIRECTEDCHATBYNAMERESPONSE : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 TargetID;
            [DMLElement("WSTR")] public String TargetName;
            public byte MessageOrder { get; } = 62;
        }
        public sealed class MSG_DIRECTEDCHATFAIL : INetworkMessage
        {
            public byte MessageOrder { get; } = 63;
        }
        public sealed class MSG_DIRECTEDQUICKCHAT : INetworkMessage
        {
            [DMLElement("STR")] public String SourceName;
            [DMLElement("GID")] public UInt64 SourceID;
            [DMLElement("UINT")] public UInt32 MessageID;
            [DMLElement("UBYT")] public Byte Filter;
            [DMLElement("UINT")] public UInt32 Flags;
            public byte MessageOrder { get; } = 64;
        }
        public sealed class MSG_DIRECTEDQUICKCHATEXT : INetworkMessage
        {
            [DMLElement("STR")] public String SourceName;
            [DMLElement("GID")] public UInt64 SourceID;
            [DMLElement("STR")] public String Message;
            [DMLElement("UBYT")] public Byte Filter;
            [DMLElement("UINT")] public UInt32 Flags;
            public byte MessageOrder { get; } = 65;
        }
        public sealed class MSG_DISCONNECT_AFK : INetworkMessage
        {
            [DMLElement("BYT")] public SByte Warning;
            public byte MessageOrder { get; } = 66;
        }
        public sealed class MSG_DOWNLOADBROWSER : INetworkMessage
        {
            public byte MessageOrder { get; } = 67;
        }
        public sealed class MSG_DOWNLOADPACKAGE : INetworkMessage
        {
            [DMLElement("STR")] public String Data;
            public byte MessageOrder { get; } = 68;
        }
        public sealed class MSG_DOWNLOADPACKAGEELEMENT : INetworkMessage
        {
            [DMLElement("STR")] public String Data;
            public byte MessageOrder { get; } = 69;
        }
        public sealed class MSG_DYNAMODBEHAVIOR_UPDATEMODS : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("BYT")] public SByte UpdateAll;
            [DMLElement("BYT")] public SByte Add;
            [DMLElement("BYT")] public SByte Remove;
            [DMLElement("STR")] public String AllMods;
            [DMLElement("STR")] public String NewMod;
            [DMLElement("INT")] public Int32 Index;
            public byte MessageOrder { get; } = 70;
        }
        public sealed class MSG_DYNAMODDUMP : INetworkMessage
        {
            [DMLElement("STR")] public String Data;
            [DMLElement("STR")] public String Filename;
            public byte MessageOrder { get; } = 71;
        }
        public sealed class MSG_ENTERSTATE : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GameObjectID;
            [DMLElement("UINT")] public UInt32 State;
            [DMLElement("STR")] public String Data;
            public byte MessageOrder { get; } = 72;
        }
        public sealed class MSG_EQUIPITEM : INetworkMessage
        {
            [DMLElement("INT")] public Int32 IsEquip;
            [DMLElement("GID")] public UInt64 ItemID;
            [DMLElement("STR")] public String SlotName;
            public byte MessageOrder { get; } = 73;
        }
        public sealed class MSG_EQUIPMENTBEHAVIOR_EQUIPITEM : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("STR")] public String SlotName;
            [DMLElement("INT")] public Int32 IsValid;
            [DMLElement("STR")] public String SerializedItem;
            public byte MessageOrder { get; } = 74;
        }
        public sealed class MSG_EQUIPMENTBEHAVIOR_PUBLICEQUIPITEM : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("STR")] public String SerializedInfo;
            public byte MessageOrder { get; } = 75;
        }
        public sealed class MSG_EQUIPMENTBEHAVIOR_PUBLICUNEQUIPITEM : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("UBYT")] public Byte IndexToRemove;
            public byte MessageOrder { get; } = 76;
        }
        public sealed class MSG_EQUIPMENTBEHAVIOR_UNEQUIPITEM : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("GID")] public UInt64 ItemID;
            public byte MessageOrder { get; } = 77;
        }
        public sealed class MSG_FEEDINVENTORYITEM : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 PetID;
            [DMLElement("GID")] public UInt64 FedObjectID;
            public byte MessageOrder { get; } = 78;
        }
        public sealed class MSG_FIND_SESSIONS : INetworkMessage
        {
            public byte MessageOrder { get; } = 79;
        }
        public sealed class MSG_FIND_SESSION_PLAYERS : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 ZoneID;
            [DMLElement("GID")] public UInt64 SessionID;
            public byte MessageOrder { get; } = 80;
        }
        public sealed class MSG_GENERICGAME : INetworkMessage
        {
            [DMLElement("INT")] public Int32 A;
            [DMLElement("INT")] public Int32 B;
            [DMLElement("INT")] public Int32 X;
            [DMLElement("INT")] public Int32 Y;
            [DMLElement("INT")] public Int32 Z;
            [DMLElement("INT")] public Int32 W;
            [DMLElement("STR")] public String Message;
            public byte MessageOrder { get; } = 81;
        }
        public sealed class MSG_GETLADDER : INetworkMessage
        {
            [DMLElement("STR")] public String NameBlob;
            [DMLElement("GID")] public UInt64 CharacterID;
            [DMLElement("UINT")] public UInt32 TournamentNameID;
            public byte MessageOrder { get; } = 82;
        }
        public sealed class MSG_GET_RANKINGS : INetworkMessage
        {
            [DMLElement("STR")] public String Game;
            [DMLElement("INT")] public Int32 RankingCount;
            [DMLElement("UINT")] public UInt32 Time;
            [DMLElement("GID")] public UInt64 GroupID;
            public byte MessageOrder { get; } = 83;
        }
        public sealed class MSG_GIFT_REDEEMED : INetworkMessage
        {
            [DMLElement("INT")] public Int32 Success;
            [DMLElement("STR")] public String GiftID;
            [DMLElement("GID")] public UInt64 GID;
            [DMLElement("STR")] public String Data;
            [DMLElement("GID")] public UInt64 TemplateID;
            [DMLElement("INT")] public Int32 ErrorCode;
            [DMLElement("INT")] public Int32 Quantity;
            public byte MessageOrder { get; } = 84;
        }
        public sealed class MSG_GOTOPLAYER : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 TargetCharacterID;
            [DMLElement("GID")] public UInt64 OriginatorID;
            [DMLElement("UBYT")] public Byte MustBeFriend;
            public byte MessageOrder { get; } = 85;
        }
        public sealed class MSG_GOTOPLAYERRESP : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 TargetCharacterID;
            [DMLElement("STR")] public String ZoneName;
            [DMLElement("GID")] public UInt64 ZoneID;
            [DMLElement("GID")] public UInt64 OriginatorID;
            [DMLElement("UINT")] public UInt32 Error;
            public byte MessageOrder { get; } = 86;
        }
        public sealed class MSG_HARASSMENTREPORT : INetworkMessage
        {
            [DMLElement("INT")] public Int32 Count;
            [DMLElement("INT")] public Int32 CountToMute;
            public byte MessageOrder { get; } = 87;
        }
        public sealed class MSG_IGNOREADD : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 ListOwnerGID;
            [DMLElement("GID")] public UInt64 CharacterGID;
            [DMLElement("GID")] public UInt64 GameObjectGID;
            [DMLElement("STR")] public String CharacterName;
            [DMLElement("UBYT")] public Byte Forwarded;
            public byte MessageOrder { get; } = 88;
        }
        public sealed class MSG_IGNOREDROP : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 ListOwnerGID;
            [DMLElement("GID")] public UInt64 CharacterGID;
            [DMLElement("GID")] public UInt64 GameObjectGID;
            [DMLElement("UBYT")] public Byte Forwarded;
            public byte MessageOrder { get; } = 89;
        }
        public sealed class MSG_IGNORELIST : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 ListOwnerGID;
            [DMLElement("STR")] public String ListData;
            [DMLElement("UBYT")] public Byte Add;
            public byte MessageOrder { get; } = 90;
        }
        public sealed class MSG_INTERACTOBJECT : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("GID")] public UInt64 TemplateID;
            public byte MessageOrder { get; } = 91;
        }
        public sealed class MSG_INTERACTOPTION : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 ObjectID;
            [DMLElement("INT")] public Int32 OptionIndex;
            public byte MessageOrder { get; } = 92;
        }
        public sealed class MSG_INVENTORYBEHAVIOR_ADDITEM : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("STR")] public String SerializedItem;
            public byte MessageOrder { get; } = 93;
        }
        public sealed class MSG_INVENTORYBEHAVIOR_REMOVEITEM : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("GID")] public UInt64 ItemID;
            public byte MessageOrder { get; } = 94;
        }
        public sealed class MSG_INVENTORYBEHAVIOR_TRADEITEM : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("GID")] public UInt64 ItemID;
            [DMLElement("INT")] public Int32 Trading;
            public byte MessageOrder { get; } = 95;
        }
        public sealed class MSG_INVITEFRIEND : INetworkMessage
        {
            [DMLElement("STR")] public String PromoID;
            [DMLElement("WSTR")] public String YourName;
            [DMLElement("WSTR")] public String FriendName;
            [DMLElement("STR")] public String FriendEmail;
            [DMLElement("STR")] public String Locale;
            [DMLElement("UBYT")] public Byte SendInEnglish;
            public byte MessageOrder { get; } = 96;
        }
        public sealed class MSG_INVITE_RESPONSE : INetworkMessage
        {
            [DMLElement("INT")] public Int32 Success;
            [DMLElement("STR")] public String ErrorDesc;
            public byte MessageOrder { get; } = 97;
        }
        public sealed class MSG_JOINCHANNELRESPONSE : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 SourceID;
            [DMLElement("GID")] public UInt64 ParentID;
            [DMLElement("GID")] public UInt64 ChannelID;
            [DMLElement("WSTR")] public String ChannelName;
            [DMLElement("UBYT")] public Byte ErrorCode;
            [DMLElement("UBYT")] public Byte ChannelType;
            [DMLElement("GID")] public UInt64 RecipientID;
            public byte MessageOrder { get; } = 98;
        }
        public sealed class MSG_JOIN_SESSION : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 ZoneID;
            [DMLElement("GID")] public UInt64 SessionID;
            public byte MessageOrder { get; } = 99;
        }
        public sealed class MSG_JUMP : INetworkMessage
        {
            [DMLElement("UBYT")] public Byte ExcludeOriginator;
            public byte MessageOrder { get; } = 100;
        }
        public sealed class MSG_KILL_CLIENT_PROCESS : INetworkMessage
        {
            [DMLElement("UINT")] public UInt32 JobID;
            public byte MessageOrder { get; } = 101;
        }
        public sealed class MSG_LADDER : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 CharacterID;
            [DMLElement("STR")] public String LadderData;
            [DMLElement("UINT")] public UInt32 TourneyCredits;
            public byte MessageOrder { get; } = 102;
        }
        public sealed class MSG_LEAVECHANNELRESPONSE : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 SourceID;
            [DMLElement("GID")] public UInt64 ParentID;
            [DMLElement("GID")] public UInt64 ChannelID;
            [DMLElement("WSTR")] public String ChannelName;
            [DMLElement("UBYT")] public Byte ChannelType;
            [DMLElement("UBYT")] public Byte ErrorCode;
            [DMLElement("GID")] public UInt64 RecipientID;
            public byte MessageOrder { get; } = 103;
        }
        public sealed class MSG_LEAVEHOUSINGLOT : INetworkMessage
        {
            public byte MessageOrder { get; } = 104;
        }
        public sealed class MSG_LEAVESERVICERANGE : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 MobileID;
            public byte MessageOrder { get; } = 105;
        }
        public sealed class MSG_LEAVESTATE : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GameObjectID;
            [DMLElement("UINT")] public UInt32 State;
            public byte MessageOrder { get; } = 106;
        }
        public sealed class MSG_LOADSAVEOBJECTS : INetworkMessage
        {
            [DMLElement("STR")] public String Filename;
            [DMLElement("UBYT")] public Byte Save;
            public byte MessageOrder { get; } = 107;
        }
        public sealed class MSG_LOGINCOMPLETE : INetworkMessage
        {
            [DMLElement("STR")] public String ZoneName;
            [DMLElement("STR")] public String Data;
            [DMLElement("UINT")] public UInt32 ServerTime;
            [DMLElement("GID")] public UInt64 ZoneID;
            [DMLElement("UINT")] public UInt32 DynamicZoneID;
            [DMLElement("UINT")] public UInt32 DynamicServerProcID;
            [DMLElement("UINT")] public UInt32 Permissions;
            [DMLElement("INT")] public Int32 IsCSR;
            [DMLElement("STR")] public String ZoneServer;
            [DMLElement("UBYT")] public Byte TestServer;
            [DMLElement("UINT")] public UInt32 AltMusicFile;
            [DMLElement("UBYT")] public Byte ShowSubscriberIcon;
            [DMLElement("INT")] public Int32 SubscriberCrownsPricePercent;
            [DMLElement("INT")] public Int32 UseFriendFinder;
            [DMLElement("STR")] public String RealmName;
            [DMLElement("UBYT")] public Byte IsBossMarkZone;
            [DMLElement("STR")] public String CriticalObjects;
            public byte MessageOrder { get; } = 108;
        }
        public sealed class MSG_MAIL_DATA : INetworkMessage
        {
            [DMLElement("STR")] public String Data;
            public byte MessageOrder { get; } = 109;
        }
        public sealed class MSG_MARK_LOCATION : INetworkMessage
        {
            public byte MessageOrder { get; } = 110;
        }
        public sealed class MSG_MARK_LOCATION_RESPONSE : INetworkMessage
        {
            [DMLElement("BYT")] public SByte Result;
            [DMLElement("STR")] public String ZoneName;
            [DMLElement("STR")] public String ZoneDisplayNameId;
            [DMLElement("BYT")] public SByte ZoneType;
            [DMLElement("GID")] public UInt64 InstanceId;
            [DMLElement("FLT")] public Single LocationX;
            [DMLElement("FLT")] public Single LocationY;
            [DMLElement("FLT")] public Single LocationZ;
            [DMLElement("FLT")] public Single Direction;
            [DMLElement("STR")] public String CommonsZoneId;
            [DMLElement("STR")] public String MarkType;
            public byte MessageOrder { get; } = 111;
        }
        public sealed class MSG_MATCHAWARD : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 CharacterID;
            [DMLElement("STR")] public String AwardData;
            public byte MessageOrder { get; } = 112;
        }
        public sealed class MSG_MATCHINVITE : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 CharacterID;
            [DMLElement("UINT")] public UInt32 TournamentNameID;
            [DMLElement("STR")] public String MatchActor;
            public byte MessageOrder { get; } = 113;
        }
        public sealed class MSG_MATCHMAKERUPDATE : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 CharacterID;
            [DMLElement("STR")] public String MatchTeam;
            [DMLElement("STR")] public String MatchActor;
            [DMLElement("STR")] public String BracketInfo;
            [DMLElement("STR")] public String RegistrationInfo;
            [DMLElement("STR")] public String UpdateMessage;
            [DMLElement("UBYT")] public Byte Status;
            public byte MessageOrder { get; } = 114;
        }
        public sealed class MSG_MATCHREADY : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 CharacterID;
            [DMLElement("GID")] public UInt64 ZoneID;
            [DMLElement("STR")] public String ZoneName;
            [DMLElement("UINT")] public UInt32 TournamentNameID;
            [DMLElement("STR")] public String MatchActor;
            public byte MessageOrder { get; } = 115;
        }
        public sealed class MSG_MATCHRESULT : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 CharacterID;
            [DMLElement("STR")] public String ResultData;
            [DMLElement("STR")] public String AwardData;
            public byte MessageOrder { get; } = 116;
        }
        public sealed class MSG_MESSAGE_PROCESS : INetworkMessage
        {
            [DMLElement("UINT")] public UInt32 JobID;
            [DMLElement("STR")] public String Message;
            public byte MessageOrder { get; } = 117;
        }
        public sealed class MSG_MOVECORRECTION : INetworkMessage
        {
            [DMLElement("FLT")] public Single LocationX;
            [DMLElement("FLT")] public Single LocationY;
            [DMLElement("FLT")] public Single LocationZ;
            [DMLElement("FLT")] public Single Direction;
            public byte MessageOrder { get; } = 118;
        }
        public sealed class MSG_MOVESTATE : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("BYT")] public SByte NewState;
            public byte MessageOrder { get; } = 119;
        }
        public sealed class MSG_MUTE : INetworkMessage
        {
            [DMLElement("STR")] public String MuteTime;
            [DMLElement("UBYT")] public Byte ForceMessage;
            public byte MessageOrder { get; } = 120;
        }
        public sealed class MSG_MUTE_RSP : INetworkMessage
        {
            [DMLElement("STR")] public String MutedID;
            [DMLElement("STR")] public String MuteTime;
            [DMLElement("STR")] public String MuteType;
            [DMLElement("UBYT")] public Byte Success;
            public byte MessageOrder { get; } = 121;
        }
        public sealed class MSG_NEWOBJECT : INetworkMessage
        {
            [DMLElement("STR")] public String Data;
            public byte MessageOrder { get; } = 122;
        }
        public sealed class MSG_NEWSYSSTATS : INetworkMessage
        {
            [DMLElement("INT")] public Int32 CpuUsage;
            [DMLElement("INT")] public Int32 VMemUsed;
            [DMLElement("INT")] public Int32 RMemUsed;
            public byte MessageOrder { get; } = 123;
        }
        public sealed class MSG_NEWTICKCNT : INetworkMessage
        {
            [DMLElement("INT")] public Int32 TickCnt;
            public byte MessageOrder { get; } = 124;
        }
        public sealed class MSG_NEWTOURNEYREWARDS : INetworkMessage
        {
            [DMLElement("STR")] public String Data;
            [DMLElement("GID")] public UInt64 BracketID;
            [DMLElement("STR")] public String TourneyNameSTKey;
            public byte MessageOrder { get; } = 125;
        }
        public sealed class MSG_NEW_MAIL : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 CharacterID;
            [DMLElement("INT")] public Int32 MailType;
            [DMLElement("UBYT")] public Byte AccountMail;
            public byte MessageOrder { get; } = 126;
        }
        public sealed class MSG_NOTIFYCHANNELINSTANCE : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 RecipientID;
            [DMLElement("GID")] public UInt64 ParentID;
            [DMLElement("GID")] public UInt64 ID;
            [DMLElement("WSTR")] public String Name;
            [DMLElement("UBYT")] public Byte Create;
            public byte MessageOrder { get; } = 127;
        }
        public sealed class MSG_NOTIFY_GIFT : INetworkMessage
        {
            [DMLElement("INT")] public Int32 Gift;
            [DMLElement("INT")] public Int32 CrownsRewards;
            public byte MessageOrder { get; } = 128;
        }
        public sealed class MSG_NOTMUTED : INetworkMessage
        {
            public byte MessageOrder { get; } = 129;
        }
        public sealed class MSG_NOT_AFK : INetworkMessage
        {
            public byte MessageOrder { get; } = 130;
        }
        public sealed class MSG_NPCSPEECH : INetworkMessage
        {
            [DMLElement("STR")] public String SourceName;
            [DMLElement("GID")] public UInt64 SourceID;
            [DMLElement("STR")] public String TargetName;
            [DMLElement("GID")] public UInt64 TargetID;
            [DMLElement("STR")] public String Talk;
            [DMLElement("STR")] public String Sound;
            [DMLElement("INT")] public Int32 WidthOverride;
            public byte MessageOrder { get; } = 131;
        }
        public sealed class MSG_OBJECT_INFO_QUERY : INetworkMessage
        {
            [DMLElement("STR")] public String Info;
            [DMLElement("INT")] public Int32 Part;
            [DMLElement("INT")] public Int32 Total;
            [DMLElement("INT")] public Int32 Size;
            public byte MessageOrder { get; } = 132;
        }
        public sealed class MSG_PARTYDISBAND : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 DestinationCharacterID;
            public byte MessageOrder { get; } = 133;
        }
        public sealed class MSG_PARTYJOINFAILED : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 DestinationCharacterID;
            [DMLElement("INT")] public Int32 ErrorCode;
            public byte MessageOrder { get; } = 134;
        }
        public sealed class MSG_PARTYJOINNOTIFICATION : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 DestinationCharacterID;
            [DMLElement("GID")] public UInt64 ChannelID;
            [DMLElement("GID")] public UInt64 PartyID;
            public byte MessageOrder { get; } = 135;
        }
        public sealed class MSG_PARTYLEAVE : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 SourceCharacterID;
            public byte MessageOrder { get; } = 136;
        }
        public sealed class MSG_PARTYLEAVENOTIFICATION : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 DestinationCharacterID;
            [DMLElement("GID")] public UInt64 CharacterID;
            public byte MessageOrder { get; } = 137;
        }
        public sealed class MSG_PARTYLEVELUP : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 CharacterID;
            [DMLElement("INT")] public Int32 NewLevel;
            public byte MessageOrder { get; } = 138;
        }
        public sealed class MSG_PARTYLEVELUPUPDATE : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 DestinationCharacterID;
            [DMLElement("GID")] public UInt64 CharacterID;
            [DMLElement("INT")] public Int32 NewLevel;
            public byte MessageOrder { get; } = 139;
        }
        public sealed class MSG_PARTYMULTIPLAYERMOUNTEQUIP : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 SourceCharacterID;
            [DMLElement("GID")] public UInt64 MountTemplateID;
            public byte MessageOrder { get; } = 140;
        }
        public sealed class MSG_PARTYMULTIPLAYERMOUNTEQUIPUPDATE : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 DestinationCharacterID;
            [DMLElement("GID")] public UInt64 SourceCharacterID;
            [DMLElement("GID")] public UInt64 MountTemplateID;
            public byte MessageOrder { get; } = 141;
        }
        public sealed class MSG_PARTYMULTIPLAYERMOUNTJOIN : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 SourceCharacterID;
            [DMLElement("GID")] public UInt64 MountOwnerCharacterID;
            [DMLElement("GID")] public UInt64 MountTemplateID;
            public byte MessageOrder { get; } = 142;
        }
        public sealed class MSG_PARTYMULTIPLAYERMOUNTJOINUPDATE : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 DestinationCharacterID;
            [DMLElement("GID")] public UInt64 SourceCharacterID;
            [DMLElement("GID")] public UInt64 MountOwnerCharacterID;
            [DMLElement("GID")] public UInt64 MountTemplateID;
            public byte MessageOrder { get; } = 143;
        }
        public sealed class MSG_PARTYREQUESTACCEPT : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 SourceCharacterID;
            [DMLElement("GID")] public UInt64 PartyID;
            public byte MessageOrder { get; } = 144;
        }
        public sealed class MSG_PARTYREQUESTDECLINE : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 SourceCharacterID;
            [DMLElement("GID")] public UInt64 PartyID;
            public byte MessageOrder { get; } = 145;
        }
        public sealed class MSG_PARTYREQUESTINVITE : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 SourceCharacterID;
            [DMLElement("GID")] public UInt64 SourceGlobalID;
            [DMLElement("GID")] public UInt64 TargetCharacterID;
            [DMLElement("GID")] public UInt64 TargetGlobalID;
            public byte MessageOrder { get; } = 146;
        }
        public sealed class MSG_PARTYREQUESTJOIN : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 DestinationCharacterID;
            [DMLElement("GID")] public UInt64 CharacterID;
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("STR")] public String PlayerNameBlob;
            [DMLElement("GID")] public UInt64 PartyID;
            public byte MessageOrder { get; } = 147;
        }
        public sealed class MSG_PARTYREQUESTMEMBERZONES : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 PartyID;
            [DMLElement("GID")] public UInt64 SourceCharacterID;
            public byte MessageOrder { get; } = 148;
        }
        public sealed class MSG_PARTYREQUESTRESPONSE : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 DestinationCharacterID;
            [DMLElement("GID")] public UInt64 TargetCharacterID;
            [DMLElement("GID")] public UInt64 TargetGlobalID;
            [DMLElement("INT")] public Int32 ErrorCode;
            [DMLElement("STR")] public String PlayerNameBlob;
            public byte MessageOrder { get; } = 149;
        }
        public sealed class MSG_PARTYREQUESTTIMEOUT : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 DestinationCharacterID;
            public byte MessageOrder { get; } = 150;
        }
        public sealed class MSG_PARTYSUBMITMEMBERZONES : INetworkMessage
        {
            [DMLElement("STR")] public String PartyMemberZones;
            [DMLElement("GID")] public UInt64 DestinationCharacterID;
            public byte MessageOrder { get; } = 151;
        }
        public sealed class MSG_PARTYUPDATE : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 DestinationCharacterID;
            [DMLElement("STR")] public String PlayerNameBlob;
            [DMLElement("GID")] public UInt64 CharacterID;
            [DMLElement("GID")] public UInt64 GlobalID;
            public byte MessageOrder { get; } = 152;
        }
        public sealed class MSG_PARTYZONEREQUEST : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 CharacterID;
            public byte MessageOrder { get; } = 153;
        }
        public sealed class MSG_PARTYZONEREQUESTRESPONSE : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 CharacterID;
            [DMLElement("GID")] public UInt64 PartyID;
            public byte MessageOrder { get; } = 154;
        }
        public sealed class MSG_PICKUPOBJECT : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GameObjectID;
            public byte MessageOrder { get; } = 155;
        }
        public sealed class MSG_PLACEOBJECT : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("GID")] public UInt64 TemplateID;
            public byte MessageOrder { get; } = 156;
        }
        public sealed class MSG_PLAYCINEMATIC : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 CinematicID;
            [DMLElement("GID")] public UInt64 TargetID;
            [DMLElement("FLT")] public Single Start_X;
            [DMLElement("FLT")] public Single Start_Y;
            [DMLElement("FLT")] public Single Start_Z;
            [DMLElement("FLT")] public Single End_X;
            [DMLElement("FLT")] public Single End_Y;
            [DMLElement("FLT")] public Single End_Z;
            [DMLElement("STR")] public String Asset;
            [DMLElement("UBYT")] public Byte DisableInteraction;
            public byte MessageOrder { get; } = 157;
        }
        public sealed class MSG_PLAYERBLACKBALLEDALERT : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 CharacterID;
            [DMLElement("BYT")] public SByte Muted;
            public byte MessageOrder { get; } = 158;
        }
        public sealed class MSG_PLAYERREADYACK : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 CharacterID;
            [DMLElement("UINT")] public UInt32 TournamentNameID;
            [DMLElement("UINT")] public UInt32 MatchNameID;
            [DMLElement("GID")] public UInt64 BracketID;
            [DMLElement("UBYT")] public Byte Online;
            public byte MessageOrder { get; } = 159;
        }
        public sealed class MSG_PLAYSOUND : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 SoundID;
            [DMLElement("FLT")] public Single ReinteractTime;
            [DMLElement("STR")] public String SoundFilename;
            [DMLElement("FLT")] public Single StartDelay;
            [DMLElement("UBYT")] public Byte PlayAtMusicVolume;
            public byte MessageOrder { get; } = 160;
        }
        public sealed class MSG_POSTZONEEVENTFROMCLIENT : INetworkMessage
        {
            [DMLElement("STR")] public String EventName;
            public byte MessageOrder { get; } = 161;
        }
        public sealed class MSG_PREVIEW_ISLAND : INetworkMessage
        {
            [DMLElement("STR")] public String PreviewWorldZone;
            public byte MessageOrder { get; } = 162;
        }
        public sealed class MSG_PVPUPDATEINFO : INetworkMessage
        {
            [DMLElement("STR")] public String TournamentInfo;
            [DMLElement("GID")] public UInt64 CharacterID;
            public byte MessageOrder { get; } = 163;
        }
        public sealed class MSG_QUERY_LOGOUT : INetworkMessage
        {
            [DMLElement("UBYT")] public Byte IsInstance;
            public byte MessageOrder { get; } = 164;
        }
        public sealed class MSG_RADIALCHAT : INetworkMessage
        {
            [DMLElement("STR")] public String SourceName;
            [DMLElement("GID")] public UInt64 SourceID;
            [DMLElement("STR")] public String Message;
            [DMLElement("UBYT")] public Byte Filter;
            public byte MessageOrder { get; } = 165;
        }
        public sealed class MSG_RADIALQUICKCHAT : INetworkMessage
        {
            [DMLElement("STR")] public String SourceName;
            [DMLElement("GID")] public UInt64 SourceID;
            [DMLElement("UINT")] public UInt32 MessageID;
            [DMLElement("UBYT")] public Byte Filter;
            public byte MessageOrder { get; } = 166;
        }
        public sealed class MSG_RADIALQUICKCHATEXT : INetworkMessage
        {
            [DMLElement("STR")] public String SourceName;
            [DMLElement("GID")] public UInt64 SourceID;
            [DMLElement("STR")] public String Message;
            [DMLElement("UBYT")] public Byte Filter;
            public byte MessageOrder { get; } = 167;
        }
        public sealed class MSG_RADIALZONECLUSTERQUICKCHAT : INetworkMessage
        {
            [DMLElement("STR")] public String SourceName;
            [DMLElement("GID")] public UInt64 SourceID;
            [DMLElement("UINT")] public UInt32 MessageID;
            [DMLElement("UBYT")] public Byte Filter;
            [DMLElement("UBYT")] public Byte IsOwner;
            public byte MessageOrder { get; } = 168;
        }
        public sealed class MSG_RANKING : INetworkMessage
        {
            [DMLElement("UINT")] public UInt32 GameID;
            [DMLElement("STR")] public String Name;
            [DMLElement("GID")] public UInt64 CharacterID;
            [DMLElement("INT")] public Int32 Score;
            [DMLElement("INT")] public Int32 Rank;
            public byte MessageOrder { get; } = 169;
        }
        public sealed class MSG_REALM_INFO_QUERY : INetworkMessage
        {
            [DMLElement("STR")] public String RealmInfoList;
            [DMLElement("STR")] public String CurrentRealm;
            [DMLElement("STR")] public String InstanceInfoList;
            [DMLElement("STR")] public String CurrentZone;
            public byte MessageOrder { get; } = 170;
        }
        public sealed class MSG_RECALL_LOCATION : INetworkMessage
        {
            public byte MessageOrder { get; } = 171;
        }
        public sealed class MSG_RECEIVE_GIFTS : INetworkMessage
        {
            [DMLElement("INT")] public Int32 Success;
            [DMLElement("STR")] public String Data;
            [DMLElement("INT")] public Int32 CrownsRewards;
            public byte MessageOrder { get; } = 172;
        }
        public sealed class MSG_RECEIVE_PROMOTIONS : INetworkMessage
        {
            [DMLElement("INT")] public Int32 Success;
            [DMLElement("STR")] public String Data;
            public byte MessageOrder { get; } = 173;
        }
        public sealed class MSG_REDEEM_GIFT : INetworkMessage
        {
            [DMLElement("STR")] public String GiftID;
            [DMLElement("GID")] public UInt64 BundleChoiceID;
            [DMLElement("INT")] public Int32 PrimaryColorIndex;
            public byte MessageOrder { get; } = 174;
        }
        public sealed class MSG_REDEEM_MAIL_GIFT : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 MailId;
            [DMLElement("INT")] public Int32 PrimaryColorIndex;
            public byte MessageOrder { get; } = 175;
        }
        public sealed class MSG_REDEEM_MAIL_GIFT_RESPONSE : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 MailId;
            [DMLElement("INT")] public Int32 ErrorCode;
            [DMLElement("GID")] public UInt64 TemplateId;
            public byte MessageOrder { get; } = 176;
        }
        public sealed class MSG_RELEASEDELAY : INetworkMessage
        {
            public byte MessageOrder { get; } = 177;
        }
        public sealed class MSG_RELOADTEMPLATEDIR : INetworkMessage
        {
            [DMLElement("STR")] public String Directory;
            [DMLElement("BYT")] public SByte Recursive;
            public byte MessageOrder { get; } = 178;
        }
        public sealed class MSG_REMOVEDSHOPPER : INetworkMessage
        {
            [DMLElement("STR")] public String StateName;
            public byte MessageOrder { get; } = 179;
        }
        public sealed class MSG_REMOVEEFFECT : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GameObjectID;
            [DMLElement("UINT")] public UInt32 EffectNameID;
            [DMLElement("INT")] public Int32 InternalID;
            public byte MessageOrder { get; } = 180;
        }
        public sealed class MSG_REMOVEITEMREQUEST : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("GID")] public UInt64 ItemTemplateID;
            [DMLElement("INT")] public Int32 Quantity;
            public byte MessageOrder { get; } = 181;
        }
        public sealed class MSG_REMOVEOBJECT : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GameObjectID;
            public byte MessageOrder { get; } = 182;
        }
        public sealed class MSG_REMOVEPARTICLE : INetworkMessage
        {
            [DMLElement("STR")] public String newName;
            [DMLElement("STR")] public String attachTo;
            [DMLElement("GID")] public UInt64 parentID;
            public byte MessageOrder { get; } = 183;
        }
        public sealed class MSG_REMOVEZONETIMER : INetworkMessage
        {
            [DMLElement("INT")] public Int32 TimerID;
            public byte MessageOrder { get; } = 184;
        }
        public sealed class MSG_REPORTADTAKEOVER : INetworkMessage
        {
            [DMLElement("STR")] public String PARTNER;
            [DMLElement("STR")] public String URL;
            public byte MessageOrder { get; } = 185;
        }
        public sealed class MSG_REQASKSERVER : INetworkMessage
        {
            [DMLElement("UINT")] public UInt32 RequestID;
            [DMLElement("STR")] public String Requirement;
            [DMLElement("UINT")] public UInt32 Response;
            public byte MessageOrder { get; } = 186;
        }
        public sealed class MSG_REQCHATDIAGNOSTICS : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 CharacterID;
            [DMLElement("STR")] public String Data;
            public byte MessageOrder { get; } = 187;
        }
        public sealed class MSG_REQUESTADVANCECHANNELINSTANCE : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 SourceID;
            [DMLElement("GID")] public UInt64 ChannelID;
            public byte MessageOrder { get; } = 188;
        }
        public sealed class MSG_REQUESTCHATCODE : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 ListOwnerGID;
            [DMLElement("STR")] public String Code;
            [DMLElement("INT")] public Int32 CodeTime;
            [DMLElement("INT")] public Int32 SpecialCode;
            [DMLElement("UBYT")] public Byte Forwarded;
            [DMLElement("STR")] public String NameBlob;
            public byte MessageOrder { get; } = 189;
        }
        public sealed class MSG_REQUESTCREATECHANNEL : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 SourceID;
            [DMLElement("STR")] public String Name;
            [DMLElement("STR")] public String Password;
            [DMLElement("UINT")] public UInt32 Flags;
            [DMLElement("UINT")] public UInt32 ChatInfoFlags;
            [DMLElement("INT")] public Int32 UserLimit;
            public byte MessageOrder { get; } = 190;
        }
        public sealed class MSG_REQUESTDIRECTEDCHAT : INetworkMessage
        {
            [DMLElement("WSTR")] public String Message;
            [DMLElement("GID")] public UInt64 TargetID;
            public byte MessageOrder { get; } = 191;
        }
        public sealed class MSG_REQUESTDIRECTEDCHATBYNAME : INetworkMessage
        {
            [DMLElement("WSTR")] public String Message;
            [DMLElement("WSTR")] public String TargetName;
            public byte MessageOrder { get; } = 192;
        }
        public sealed class MSG_REQUESTDIRECTEDQUICKCHAT : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 TargetID;
            [DMLElement("UINT")] public UInt32 MessageID;
            public byte MessageOrder { get; } = 193;
        }
        public sealed class MSG_REQUESTDIRECTEDQUICKCHATEXT : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 TargetID;
            [DMLElement("STR")] public String Message;
            public byte MessageOrder { get; } = 194;
        }
        public sealed class MSG_REQUESTJOINCHANNEL : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 SourceID;
            [DMLElement("GID")] public UInt64 ChannelID;
            [DMLElement("WSTR")] public String Password;
            public byte MessageOrder { get; } = 195;
        }
        public sealed class MSG_REQUESTJOINCHANNELBYNAME : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 SourceID;
            [DMLElement("WSTR")] public String ChannelName;
            [DMLElement("WSTR")] public String Password;
            public byte MessageOrder { get; } = 196;
        }
        public sealed class MSG_REQUESTLEAVECHANNEL : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 SourceID;
            [DMLElement("GID")] public UInt64 ChannelID;
            public byte MessageOrder { get; } = 197;
        }
        public sealed class MSG_REQUESTLEAVECHANNELBYNAME : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 SourceID;
            [DMLElement("WSTR")] public String ChannelName;
            public byte MessageOrder { get; } = 198;
        }
        public sealed class MSG_REQUESTMAXFRIENDS : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 RequestingPlayerGID;
            [DMLElement("INT")] public Int32 MaximumFriends;
            [DMLElement("INT")] public Int32 MaximumSubscriberFriends;
            public byte MessageOrder { get; } = 199;
        }
        public sealed class MSG_REQUESTRADIALCHAT : INetworkMessage
        {
            [DMLElement("STR")] public String Message;
            public byte MessageOrder { get; } = 200;
        }
        public sealed class MSG_REQUESTRADIALFRIENDCHAT : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 PlayerGID;
            [DMLElement("STR")] public String Message;
            [DMLElement("GID")] public UInt64 SourceID;
            [DMLElement("UBYT")] public Byte Filter;
            [DMLElement("STR")] public String SourceName;
            public byte MessageOrder { get; } = 201;
        }
        public sealed class MSG_REQUESTRADIALFRIENDQUICKCHAT : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 PlayerGID;
            [DMLElement("UINT")] public UInt32 MessageID;
            [DMLElement("GID")] public UInt64 SourceID;
            [DMLElement("UBYT")] public Byte Filter;
            [DMLElement("STR")] public String SourceName;
            public byte MessageOrder { get; } = 202;
        }
        public sealed class MSG_REQUESTRADIALOWNERCHAT : INetworkMessage
        {
            [DMLElement("STR")] public String Message;
            [DMLElement("GID")] public UInt64 SourceID;
            [DMLElement("UBYT")] public Byte Filter;
            [DMLElement("STR")] public String SourceName;
            [DMLElement("UBYT")] public Byte IsOwner;
            public byte MessageOrder { get; } = 203;
        }
        public sealed class MSG_REQUESTRADIALQUICKCHAT : INetworkMessage
        {
            [DMLElement("UINT")] public UInt32 MessageID;
            public byte MessageOrder { get; } = 204;
        }
        public sealed class MSG_REQUESTRADIALQUICKCHATEXT : INetworkMessage
        {
            [DMLElement("STR")] public String Message;
            public byte MessageOrder { get; } = 205;
        }
        public sealed class MSG_REQUESTSESSION : INetworkMessage
        {
            [DMLElement("STR")] public String Session;
            [DMLElement("UBYT")] public Byte Valid;
            [DMLElement("INT")] public Int32 ID;
            [DMLElement("UINT")] public UInt32 CRC;
            [DMLElement("STR")] public String STEAMID;
            [DMLElement("STR")] public String Whitelist;
            [DMLElement("UINT")] public UInt32 Threshold;
            public byte MessageOrder { get; } = 206;
        }
        public sealed class MSG_REQUESTZONECLUSTERQUICKCHAT : INetworkMessage
        {
            [DMLElement("UINT")] public UInt32 MessageID;
            [DMLElement("UBYT")] public Byte IsOwner;
            public byte MessageOrder { get; } = 207;
        }
        public sealed class MSG_REQUEST_GIFTS : INetworkMessage
        {
            [DMLElement("STR")] public String GiftType;
            public byte MessageOrder { get; } = 208;
        }
        public sealed class MSG_REQUEST_PROMOTIONS : INetworkMessage
        {
            [DMLElement("STR")] public String Locale;
            public byte MessageOrder { get; } = 209;
        }
        public sealed class MSG_RESTORECHAR_RSP : INetworkMessage
        {
            [DMLElement("UBYT")] public Byte Success;
            public byte MessageOrder { get; } = 210;
        }
        public sealed class MSG_RETRIEVE_MAIL : INetworkMessage
        {
            public byte MessageOrder { get; } = 211;
        }
        public sealed class MSG_RETRYTELEPORT : INetworkMessage
        {
            public byte MessageOrder { get; } = 212;
        }
        public sealed class MSG_SCRIPT : INetworkMessage
        {
            [DMLElement("INT")] public Int32 ProcessID;
            [DMLElement("STR")] public String Message;
            public byte MessageOrder { get; } = 213;
        }
        public sealed class MSG_SELECT_BADGE : INetworkMessage
        {
            [DMLElement("UINT")] public UInt32 BadgeNameID;
            [DMLElement("UINT")] public UInt32 Error;
            public byte MessageOrder { get; } = 214;
        }
        public sealed class MSG_SENDCHATCODE : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 ListOwnerGID;
            [DMLElement("STR")] public String Code;
            [DMLElement("UINT")] public UInt32 Error;
            [DMLElement("GID")] public UInt64 UseSuccess;
            [DMLElement("STR")] public String CreatorName;
            public byte MessageOrder { get; } = 215;
        }
        public sealed class MSG_SENDINTERACTOPTIONS : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 MobileID;
            [DMLElement("STR")] public String Options;
            public byte MessageOrder { get; } = 216;
        }
        public sealed class MSG_SENDTEXT : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 CharacterID;
            [DMLElement("STR")] public String Message;
            public byte MessageOrder { get; } = 217;
        }
        public sealed class MSG_SERVERMOVE : INetworkMessage
        {
            [DMLElement("USHRT")] public UInt16 LocationX;
            [DMLElement("USHRT")] public UInt16 LocationY;
            [DMLElement("USHRT")] public UInt16 LocationZ;
            [DMLElement("UBYT")] public Byte Direction;
            [DMLElement("USHRT")] public UInt16 MobileID;
            public byte MessageOrder { get; } = 218;
        }
        public sealed class MSG_SERVERSHUTDOWN : INetworkMessage
        {
            [DMLElement("UINT")] public UInt32 Message;
            public byte MessageOrder { get; } = 219;
        }
        public sealed class MSG_SERVERTELEPORT : INetworkMessage
        {
            [DMLElement("USHRT")] public UInt16 LocationX;
            [DMLElement("USHRT")] public UInt16 LocationY;
            [DMLElement("USHRT")] public UInt16 LocationZ;
            [DMLElement("UBYT")] public Byte Direction;
            [DMLElement("USHRT")] public UInt16 MobileID;
            public byte MessageOrder { get; } = 220;
        }
        public sealed class MSG_SERVERTRANSFER : INetworkMessage
        {
            [DMLElement("STR")] public String IP;
            [DMLElement("INT")] public Int32 TCPPort;
            [DMLElement("INT")] public Int32 UDPPort;
            [DMLElement("INT")] public Int32 Key;
            [DMLElement("GID")] public UInt64 UserID;
            [DMLElement("GID")] public UInt64 CharID;
            [DMLElement("STR")] public String ZoneName;
            [DMLElement("GID")] public UInt64 ZoneID;
            [DMLElement("STR")] public String Location;
            [DMLElement("INT")] public Int32 Slot;
            [DMLElement("GID")] public UInt64 SessionID;
            [DMLElement("INT")] public Int32 SessionSlot;
            [DMLElement("GID")] public UInt64 TargetPlayerID;
            [DMLElement("STR")] public String FallbackIP;
            [DMLElement("INT")] public Int32 FallbackTCPPort;
            [DMLElement("INT")] public Int32 FallbackUDPPort;
            [DMLElement("INT")] public Int32 FallbackKey;
            [DMLElement("STR")] public String FallbackZone;
            [DMLElement("GID")] public UInt64 FallbackZoneID;
            [DMLElement("UINT")] public UInt32 TransitionID;
            public byte MessageOrder { get; } = 221;
        }
        public sealed class MSG_SERVERTUTORIALCOMMAND : INetworkMessage
        {
            [DMLElement("STR")] public String QuestToAdd;
            [DMLElement("STR")] public String QuestToRemove;
            [DMLElement("STR")] public String GoalToComplete;
            [DMLElement("STR")] public String EventToPost;
            [DMLElement("STR")] public String Action;
            [DMLElement("INT")] public Int32 Value;
            public byte MessageOrder { get; } = 222;
        }
        public sealed class MSG_SERVER_ERROR : INetworkMessage
        {
            [DMLElement("UINT")] public UInt32 Error;
            public byte MessageOrder { get; } = 223;
        }
        public sealed class MSG_SERVER_PROCESS_RUNNING : INetworkMessage
        {
            [DMLElement("UINT")] public UInt32 PID;
            [DMLElement("UINT")] public UInt32 JobID;
            public byte MessageOrder { get; } = 224;
        }
        public sealed class MSG_SESSION : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 ZoneID;
            [DMLElement("GID")] public UInt64 SessionID;
            [DMLElement("STR")] public String Name;
            [DMLElement("INT")] public Int32 Slots;
            [DMLElement("INT")] public Int32 ActiveSlots;
            [DMLElement("STR")] public String Zone;
            [DMLElement("STR")] public String Rules;
            public byte MessageOrder { get; } = 225;
        }
        public sealed class MSG_SESSION_ERROR : INetworkMessage
        {
            [DMLElement("INT")] public Int32 ErrorCode;
            public byte MessageOrder { get; } = 226;
        }
        public sealed class MSG_SESSION_PLAYER : INetworkMessage
        {
            [DMLElement("INT")] public Int32 Slot;
            [DMLElement("GID")] public UInt64 CharID;
            [DMLElement("STR")] public String Name;
            [DMLElement("STR")] public String Ranking;
            [DMLElement("INT")] public Int32 IsFriend;
            public byte MessageOrder { get; } = 227;
        }
        public sealed class MSG_SETHOUSECUSTOMIZATION : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GameObjectID;
            [DMLElement("STR")] public String TagName;
            [DMLElement("STR")] public String TextureFilename;
            public byte MessageOrder { get; } = 228;
        }
        public sealed class MSG_SPLITQUANTITY : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("GID")] public UInt64 ItemID;
            [DMLElement("INT")] public Int32 Quantity;
            public byte MessageOrder { get; } = 229;
        }
        public sealed class MSG_STARTSTAGEDCINEMATIC : INetworkMessage
        {
            [DMLElement("STR")] public String CinematicName;
            [DMLElement("STR")] public String InitialStageName;
            [DMLElement("FLT")] public Single Start_X;
            [DMLElement("FLT")] public Single Start_Y;
            [DMLElement("FLT")] public Single Start_Z;
            [DMLElement("FLT")] public Single Yaw;
            [DMLElement("GID")] public UInt64 DuelID;
            [DMLElement("BYT")] public SByte WinningTeamID;
            public byte MessageOrder { get; } = 230;
        }
        public sealed class MSG_START_CLIENT_PROCESS : INetworkMessage
        {
            [DMLElement("UINT")] public UInt32 JobID;
            [DMLElement("STR")] public String ScriptName;
            [DMLElement("GID")] public UInt64 OwnerGID;
            public byte MessageOrder { get; } = 231;
        }
        public sealed class MSG_START_SERVER_PROCESS : INetworkMessage
        {
            [DMLElement("UINT")] public UInt32 PID;
            [DMLElement("STR")] public String ScriptName;
            [DMLElement("GID")] public UInt64 OwnerGID;
            public byte MessageOrder { get; } = 232;
        }
        public sealed class MSG_SUBOPTIMAL_BRACKET_RESPONSE : INetworkMessage
        {
            [DMLElement("UINT")] public UInt32 Choice;
            public byte MessageOrder { get; } = 233;
        }
        public sealed class MSG_TELEPORT_TO_GAME_ZONE : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 CharacterID;
            [DMLElement("STR")] public String Game;
            [DMLElement("STR")] public String Track;
            [DMLElement("GID")] public UInt64 ZoneInstanceID;
            public byte MessageOrder { get; } = 234;
        }
        public sealed class MSG_TOURNAMENTUPDATE : INetworkMessage
        {
            [DMLElement("STR")] public String Updates;
            [DMLElement("GID")] public UInt64 CharacterID;
            public byte MessageOrder { get; } = 235;
        }
        public sealed class MSG_TRANSFERCHAR_RSP : INetworkMessage
        {
            [DMLElement("UBYT")] public Byte Success;
            public byte MessageOrder { get; } = 236;
        }
        public sealed class MSG_TRANSFER_INSTANCE : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 ZoneID;
            [DMLElement("UINT")] public UInt32 Error;
            public byte MessageOrder { get; } = 237;
        }
        public sealed class MSG_TRANSFER_REALMS : INetworkMessage
        {
            [DMLElement("STR")] public String RealmName;
            [DMLElement("UINT")] public UInt32 Error;
            public byte MessageOrder { get; } = 238;
        }
        public sealed class MSG_TRASHINVENTORYITEM : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("GID")] public UInt64 TemplateID;
            public byte MessageOrder { get; } = 239;
        }
        public sealed class MSG_TUTORIALS : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("INT")] public Int32 Remove;
            [DMLElement("STR")] public String TutorialInfo;
            public byte MessageOrder { get; } = 240;
        }
        public sealed class MSG_UPDATEOBJECT : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GameObjectID;
            [DMLElement("FLT")] public Single LocationX;
            [DMLElement("FLT")] public Single LocationY;
            [DMLElement("FLT")] public Single LocationZ;
            [DMLElement("FLT")] public Single Direction;
            [DMLElement("STR")] public String Name;
            [DMLElement("GID")] public UInt64 TemplateID;
            [DMLElement("INT")] public Int32 StartDragging;
            public byte MessageOrder { get; } = 241;
        }
        public sealed class MSG_UPDATEQUANTITY : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("INT")] public Int32 Quantity;
            public byte MessageOrder { get; } = 242;
        }
        public sealed class MSG_UPDATEZONECOUNTER : INetworkMessage
        {
            [DMLElement("UBYT")] public Byte ZoneCounter;
            public byte MessageOrder { get; } = 243;
        }
        public sealed class MSG_UPDATEZONETIMER : INetworkMessage
        {
            [DMLElement("INT")] public Int32 TimerID;
            [DMLElement("STR")] public String Title;
            [DMLElement("STR")] public String TimerUI;
            [DMLElement("FLT")] public Single CountdownTime;
            public byte MessageOrder { get; } = 244;
        }
        public sealed class MSG_USECHATCODE : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 ListOwnerGID;
            [DMLElement("GID")] public UInt64 BuddyID;
            [DMLElement("STR")] public String Code;
            [DMLElement("UBYT")] public Byte Forwarded;
            public byte MessageOrder { get; } = 245;
        }
        public sealed class MSG_VIEWACCOUNT : INetworkMessage
        {
            [DMLElement("STR")] public String AccountName;
            [DMLElement("GID")] public UInt64 AccountID;
            [DMLElement("GID")] public UInt64 CharacterID;
            [DMLElement("UBYT")] public Byte CanFilterChat;
            [DMLElement("UBYT")] public Byte CanOpenChat;
            [DMLElement("UBYT")] public Byte CanUseCodes;
            public byte MessageOrder { get; } = 246;
        }
        public sealed class MSG_WIZBANG : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GameObjectID;
            [DMLElement("UINT")] public UInt32 WizBangID;
            public byte MessageOrder { get; } = 247;
        }
        public sealed class MSG_ZOMBIE_PLAYER : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 GlobalID;
            [DMLElement("FLT")] public Single Remaining;
            public byte MessageOrder { get; } = 248;
        }
        public sealed class MSG_ZONEEVENTTIMEREXPIRED : INetworkMessage
        {
            [DMLElement("STR")] public String TimerName;
            [DMLElement("STR")] public String EventName;
            public byte MessageOrder { get; } = 249;
        }
        public sealed class MSG_ZONETRANSFER : INetworkMessage
        {
            [DMLElement("STR")] public String ZoneName;
            [DMLElement("GID")] public UInt64 ZoneID;
            [DMLElement("INT")] public Int32 Slot;
            [DMLElement("UINT")] public UInt32 DynamicZoneID;
            [DMLElement("UINT")] public UInt32 DynamicServerProcID;
            [DMLElement("UBYT")] public Byte ZoneCounter;
            [DMLElement("UINT")] public UInt32 TransitionID;
            [DMLElement("GID")] public UInt64 SessionID;
            [DMLElement("INT")] public Int32 SessionSlot;
            public byte MessageOrder { get; } = 250;
        }
        public sealed class MSG_ZONETRANSFERACK : INetworkMessage
        {
            public byte MessageOrder { get; } = 251;
        }
        public sealed class MSG_ZONETRANSFERNACK : INetworkMessage
        {
            public byte MessageOrder { get; } = 252;
        }
        public sealed class MSG_ZONETRANSFERREQUEST : INetworkMessage
        {
            [DMLElement("STR")] public String ZoneName;
            [DMLElement("UBYT")] public Byte SendAck;
            public byte MessageOrder { get; } = 253;
        }
    }
}
