//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Imlight.Internals.DML
{
    using System;
    public sealed class PATCH_8_PROTOCOL : INetworkProtocol
    {
        public byte ServiceID { get; } = 8;
        public string ProtocolType { get; } = "PATCH";
        public Int32 ProtocolVersion { get; } = 1;
        public string ProtocolDescription { get; } = "Patch Server Messages";
        // == RECORDS ==
        public static INetworkRecord Dispatch(byte id)
        {
            switch (id)
            {
                case (1): return new MSG_LATEST_FILE_LIST();
                case (2): return new MSG_LATEST_FILE_LIST_V2();
                case (3): return new MSG_NEXT_VERSION();
                default: throw new InternalException($"No message was found at ID {id} for this protocol!");
            }
        }
        public sealed class MSG_LATEST_FILE_LIST : INetworkRecord
        {
            public byte MessageOrder { get; } = 1;
            [DMLElement("UINT")] public UInt32 LatestVersion;
            [DMLElement("STR")] public String ListFileName;
            [DMLElement("UINT")] public UInt32 ListFileType;
            [DMLElement("UINT")] public UInt32 ListFileTime;
            [DMLElement("UINT")] public UInt32 ListFileSize;
            [DMLElement("UINT")] public UInt32 ListFileCRC;
            [DMLElement("STR")] public String ListFileURL;
            [DMLElement("STR")] public String URLPrefix;
            [DMLElement("STR")] public String URLSuffix;
        }
        public sealed class MSG_LATEST_FILE_LIST_V2 : INetworkRecord
        {
            public byte MessageOrder { get; } = 2;
            [DMLElement("UINT")] public UInt32 LatestVersion;
            [DMLElement("STR")] public String ListFileName;
            [DMLElement("UINT")] public UInt32 ListFileType;
            [DMLElement("UINT")] public UInt32 ListFileTime;
            [DMLElement("UINT")] public UInt32 ListFileSize;
            [DMLElement("UINT")] public UInt32 ListFileCRC;
            [DMLElement("STR")] public String ListFileURL;
            [DMLElement("STR")] public String URLPrefix;
            [DMLElement("STR")] public String URLSuffix;
            [DMLElement("STR")] public String Locale;
        }
        public sealed class MSG_NEXT_VERSION : INetworkRecord
        {
            public byte MessageOrder { get; } = 3;
            [DMLElement("STR")] public String PkgName;
            [DMLElement("INT")] public Int32 Version;
            [DMLElement("STR")] public String URLPrefix;
            [DMLElement("STR")] public String FileName;
            [DMLElement("INT")] public Int32 FileType;
        }
    }
}
