//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Imlight.Internals.DML
{
    using System;
    public sealed class SKULLRIDERS_MESSAGES_40_PROTOCOL : INetworkProtocol
    {
        public byte ServiceID { get; } = 40;
        public string ProtocolType { get; } = "SKULLRIDERS_MESSAGES";
        public Int32 ProtocolVersion { get; } = 1;
        public string ProtocolDescription { get; } = "Messages for all SkullRiders minigames";
        // == RECORDS ==
        public static INetworkMessage Dispatch(byte id)
        {
            switch (id)
            {
                case (1): return new MSG_SKULLRIDERS_CONNECT();
                case (2): return new MSG_SKULLRIDERS_MOVED();
                case (3): return new MSG_SKULLRIDERS_REWARDS();
                default: throw new InternalException($"No message was found at ID {id} for this protocol!");
            }
        }
        public sealed class MSG_SKULLRIDERS_CONNECT : INetworkMessage
        {
            public byte MessageOrder { get; } = 1;
        }
        public sealed class MSG_SKULLRIDERS_MOVED : INetworkMessage
        {
            public byte MessageOrder { get; } = 2;
        }
        public sealed class MSG_SKULLRIDERS_REWARDS : INetworkMessage
        {
            [DMLElement("INT")] public Int32 score;
            [DMLElement("STR")] public String gameName;
            public byte MessageOrder { get; } = 3;
        }
    }
}
