//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Imlight.Internals.DML
{
    using System;
    using Imlight.Engine.DML;
    public sealed class SYSTEM_1_PROTOCOL : INetworkProtocol
    {
        public byte ServiceID { get; } = 1;
        public string ProtocolType { get; } = "SYSTEM";
        public Int32 ProtocolVersion { get; } = 1;
        public string ProtocolDescription { get; } = "All Common System Messages - Not Game Messages";
        // == RECORDS ==
        public static INetworkRecord Dispatch(byte id)
        {
            switch (id)
            {
                case (1): return new MSG_PING();
                case (2): return new MSG_PING_RSP();
                default: throw new InternalException($"No message was found at ID {id} for this protocol!");
            }
        }
        public sealed class MSG_PING : INetworkRecord
        {
            public byte MessageOrder { get; } = 1;
        }
        public sealed class MSG_PING_RSP : INetworkRecord
        {
            public byte MessageOrder { get; } = 2;
        }
    }
}
