//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Imlight.Internals.DML
{
    using System;
    public sealed class TESTMANAGER_11_PROTOCOL : INetworkProtocol
    {
        public byte ServiceID { get; } = 11;
        public string ProtocolType { get; } = "TESTMANAGER";
        public Int32 ProtocolVersion { get; } = 1;
        public string ProtocolDescription { get; } = "Test Manager Server Messages";
        // == RECORDS ==
        public static INetworkMessage Dispatch(byte id)
        {
            switch (id)
            {
                case (100): return new MSG_LOGIN();
                case (101): return new MSG_LOGINRESPONSE();
                default: throw new InternalException($"No message was found at ID {id} for this protocol!");
            }
        }
        public sealed class MSG_LOGIN : INetworkMessage
        {
            public byte MessageOrder { get; } = 100;
            [DMLElement("STR")] public String Username;
            [DMLElement("STR")] public String Password;
        }
        public sealed class MSG_LOGINRESPONSE : INetworkMessage
        {
            public byte MessageOrder { get; } = 101;
            [DMLElement("INT")] public Int32 Success;
        }
    }
}
