//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Imlight.Internals.DML
{
    using System;
    public sealed class WIZARDCOMBAT_MESSAGES_51_PROTOCOL : INetworkProtocol
    {
        public byte ServiceID { get; } = 51;
        public string ProtocolType { get; } = "WIZARDCOMBAT_MESSAGES";
        public Int32 ProtocolVersion { get; } = 1;
        public string ProtocolDescription { get; } = "Messages for all DoodleDoug minigames";
        // == RECORDS ==
        public static INetworkMessage Dispatch(byte id)
        {
            switch (id)
            {
                case (1): return new MSG_ALLOWLEAVEPVP();
                case (2): return new MSG_COMBATACTIONS();
                case (3): return new MSG_COMBATADD();
                case (4): return new MSG_COMBATAFK();
                case (5): return new MSG_COMBATCHEAT();
                case (6): return new MSG_COMBATDRAW();
                case (7): return new MSG_COMBATFLEE();
                case (8): return new MSG_COMBATHAND();
                case (9): return new MSG_COMBATHEALTH();
                case (10): return new MSG_COMBATLOADED();
                case (11): return new MSG_COMBATMATCHRESULT();
                case (12): return new MSG_COMBATMOVE();
                case (13): return new MSG_COMBATMOVESELECTION();
                case (14): return new MSG_COMBATPAUSED();
                case (15): return new MSG_COMBATPHASE();
                case (16): return new MSG_COMBATPHASEFORSPECTATORS();
                case (17): return new MSG_COMBATPIPS();
                case (18): return new MSG_COMBATREMOVE();
                case (19): return new MSG_COMBATREVEALHANGING();
                case (20): return new MSG_COMBATSTATS();
                case (21): return new MSG_COMBATUPFIRST();
                case (22): return new MSG_COMBATVICTORY();
                case (23): return new MSG_DUEL();
                case (24): return new MSG_ENDDUEL();
                case (25): return new MSG_PETWILLCAST();
                case (26): return new MSG_SETPLANNINGPHASETIMER();
                case (27): return new MSG_SHOWCOMBATUI();
                case (28): return new MSG_SHOWPETCARD();
                case (29): return new MSG_SIGILSPELL();
                case (30): return new MSG_UPDATECOMBATPARTICIPANT();
                case (31): return new MSG_UPDATEDUELTIMER();
                default: throw new InternalException($"No message was found at ID {id} for this protocol!");
            }
        }
        public sealed class MSG_ALLOWLEAVEPVP : INetworkMessage
        {
            public byte MessageOrder { get; } = 1;
        }
        public sealed class MSG_COMBATACTIONS : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 DuelID;
            [DMLElement("STR")] public String ActionData;
            public byte MessageOrder { get; } = 2;
        }
        public sealed class MSG_COMBATADD : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 DuelID;
            [DMLElement("STR")] public String ParticipantData;
            public byte MessageOrder { get; } = 3;
        }
        public sealed class MSG_COMBATAFK : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 DuelID;
            [DMLElement("UBYT")] public Byte IsCombatAFK;
            public byte MessageOrder { get; } = 4;
        }
        public sealed class MSG_COMBATCHEAT : INetworkMessage
        {
            [DMLElement("UINT")] public UInt32 CheatFlags;
            public byte MessageOrder { get; } = 5;
        }
        public sealed class MSG_COMBATDRAW : INetworkMessage
        {
            public byte MessageOrder { get; } = 6;
        }
        public sealed class MSG_COMBATFLEE : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 ParticipantID;
            public byte MessageOrder { get; } = 7;
        }
        public sealed class MSG_COMBATHAND : INetworkMessage
        {
            [DMLElement("STR")] public String HandData;
            [DMLElement("USHRT")] public UInt16 DeckCount;
            [DMLElement("USHRT")] public UInt16 TotalDeckCount;
            [DMLElement("USHRT")] public UInt16 TreasureCardCount;
            [DMLElement("GID")] public UInt64 ParticipantID;
            public byte MessageOrder { get; } = 8;
        }
        public sealed class MSG_COMBATHEALTH : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 DuelID;
            [DMLElement("STR")] public String HealthData;
            public byte MessageOrder { get; } = 9;
        }
        public sealed class MSG_COMBATLOADED : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 DuelID;
            [DMLElement("INT")] public Int32 RoundNum;
            [DMLElement("INT")] public Int32 FirstTeamToAct;
            [DMLElement("STR")] public String ParticipantList;
            public byte MessageOrder { get; } = 10;
        }
        public sealed class MSG_COMBATMATCHRESULT : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 DuelID;
            [DMLElement("INT")] public Int32 WinningTeam;
            public byte MessageOrder { get; } = 11;
        }
        public sealed class MSG_COMBATMOVE : INetworkMessage
        {
            [DMLElement("UBYT")] public Byte MoveType;
            [DMLElement("UBYT")] public Byte SpellSelection;
            [DMLElement("UBYT")] public Byte SpellTarget;
            public byte MessageOrder { get; } = 12;
        }
        public sealed class MSG_COMBATMOVESELECTION : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 DuelID;
            [DMLElement("GID")] public UInt64 ParticipantID;
            [DMLElement("UBYT")] public Byte MoveType;
            [DMLElement("INT")] public Int32 SpellID;
            [DMLElement("BYT")] public SByte SpellTargetIndex;
            [DMLElement("INT")] public Int32 EnchantmentID;
            [DMLElement("UBYT")] public Byte IsItemCard;
            [DMLElement("UBYT")] public Byte IsTreasureCard;
            [DMLElement("UBYT")] public Byte IsBattleCard;
            public byte MessageOrder { get; } = 13;
        }
        public sealed class MSG_COMBATPAUSED : INetworkMessage
        {
            [DMLElement("BYT")] public SByte Paused;
            public byte MessageOrder { get; } = 14;
        }
        public sealed class MSG_COMBATPHASE : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 DuelID;
            [DMLElement("UBYT")] public Byte NewPhase;
            [DMLElement("STR")] public String Data;
            public byte MessageOrder { get; } = 15;
        }
        public sealed class MSG_COMBATPHASEFORSPECTATORS : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 DuelID;
            [DMLElement("UBYT")] public Byte NewPhase;
            [DMLElement("UBYT")] public Byte Time;
            [DMLElement("STR")] public String ParticipantName1;
            [DMLElement("STR")] public String ParticipantName2;
            [DMLElement("STR")] public String ParticipantName3;
            [DMLElement("STR")] public String ParticipantName4;
            [DMLElement("STR")] public String ParticipantName5;
            [DMLElement("STR")] public String ParticipantName6;
            [DMLElement("STR")] public String ParticipantName7;
            [DMLElement("STR")] public String ParticipantName8;
            [DMLElement("UINT")] public UInt32 Subcircles;
            [DMLElement("UINT")] public UInt32 TeamName0;
            [DMLElement("UINT")] public UInt32 TeamName1;
            public byte MessageOrder { get; } = 16;
        }
        public sealed class MSG_COMBATPIPS : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 DuelID;
            [DMLElement("STR")] public String PipData;
            public byte MessageOrder { get; } = 17;
        }
        public sealed class MSG_COMBATREMOVE : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 DuelID;
            [DMLElement("GID")] public UInt64 ParticipantID;
            public byte MessageOrder { get; } = 18;
        }
        public sealed class MSG_COMBATREVEALHANGING : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 ParticipantID;
            [DMLElement("INT")] public Int32 CloakEffectType;
            [DMLElement("INT")] public Int32 SpellTemplateID;
            [DMLElement("INT")] public Int32 EffectType;
            [DMLElement("INT")] public Int32 EffectAmount;
            [DMLElement("INT")] public Int32 DamageType;
            [DMLElement("UBYT")] public Byte ActNum;
            public byte MessageOrder { get; } = 19;
        }
        public sealed class MSG_COMBATSTATS : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 DuelID;
            [DMLElement("GID")] public UInt64 PartID;
            [DMLElement("STR")] public String StatsData;
            public byte MessageOrder { get; } = 20;
        }
        public sealed class MSG_COMBATUPFIRST : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 DuelID;
            [DMLElement("UBYT")] public Byte UpFirst;
            [DMLElement("USHRT")] public UInt16 RoundNum;
            public byte MessageOrder { get; } = 21;
        }
        public sealed class MSG_COMBATVICTORY : INetworkMessage
        {
            public byte MessageOrder { get; } = 22;
        }
        public sealed class MSG_DUEL : INetworkMessage
        {
            [DMLElement("STR")] public String Data;
            public byte MessageOrder { get; } = 23;
        }
        public sealed class MSG_ENDDUEL : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 DuelID;
            public byte MessageOrder { get; } = 24;
        }
        public sealed class MSG_PETWILLCAST : INetworkMessage
        {
            [DMLElement("STR")] public String PetCastingSpell;
            [DMLElement("INT")] public Int32 Target;
            public byte MessageOrder { get; } = 25;
        }
        public sealed class MSG_SETPLANNINGPHASETIMER : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 DuelID;
            [DMLElement("INT")] public Int32 Time;
            public byte MessageOrder { get; } = 26;
        }
        public sealed class MSG_SHOWCOMBATUI : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 DuelID;
            [DMLElement("INT")] public Int32 AltTurn;
            [DMLElement("INT")] public Int32 AltTurnTeam;
            public byte MessageOrder { get; } = 27;
        }
        public sealed class MSG_SHOWPETCARD : INetworkMessage
        {
            [DMLElement("STR")] public String PetData;
            [DMLElement("INT")] public Int32 Cooldown;
            [DMLElement("INT")] public Int32 RequirementFailed;
            public byte MessageOrder { get; } = 28;
        }
        public sealed class MSG_SIGILSPELL : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 DuelID;
            [DMLElement("UINT")] public UInt32 Subcircles;
            [DMLElement("INT")] public Int32 SpellID;
            public byte MessageOrder { get; } = 29;
        }
        public sealed class MSG_UPDATECOMBATPARTICIPANT : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 ObjectID;
            [DMLElement("UBYT")] public Byte HidePVPEnemyChat;
            public byte MessageOrder { get; } = 30;
        }
        public sealed class MSG_UPDATEDUELTIMER : INetworkMessage
        {
            [DMLElement("GID")] public UInt64 DuelID;
            [DMLElement("UINT")] public UInt32 RemainingTime;
            public byte MessageOrder { get; } = 31;
        }
    }
}
