name: CI

on:
  push:
    branches:
      - quality-assurance
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: 'true'
        token: ${{ secrets.GIT_TOKEN }}
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'
    - name: Dotnet Publish
      run: dotnet publish src -c Release -o deploy
    - name: Copy files via ssh rsync
      uses: trendyminds/github-actions-rsync@master
      with:
        RSYNC_OPTIONS: -avzr --delete --exclude node_modules --exclude '.git*'
        RSYNC_TARGET: ${{ secrets.REMOTE_TARGET }}
        RSYNC_SOURCE: /deploy/
      env:
        SSH_PRIVATE_KEY: ${{ secrets.REMOTE_SSH_KEY }}
        SSH_USERNAME: ${{ secrets.REMOTE_USER }}
        SSH_HOSTNAME: ${{ secrets.REMOTE_HOST }}   
    - name: Install .NET Core on the server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.REMOTE_SSH_KEY }}
        port: 22
        script: |
          sudo apt-get update
          sudo apt-get install -y dotnet-runtime-7.0
    - name: Run the application on the server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.REMOTE_SSH_KEY }}
        port: 22
        script: |
          sudo systemctl daemon-reload
          sudo systemctl restart imlight.service
